#!/usr/bin/env python3
"""Deterministic infinite Riverfall terrain generated by native chunk sources.

A continuous global lowland prevents finite scene boundaries. Bounded authored
landmark motifs are transformed and selected from signed cell coordinates:
fractured escarpments, rivers, waterfalls, cabins, paths, and forest clusters.
Every request is evaluated in absolute world coordinates and returns a native
WorldChunkView through WorldGenerator.
"""

from __future__ import annotations

import argparse
import json
import random
import shutil
from collections.abc import Iterable, Sequence
from pathlib import Path

from nucleation import (
    Brush,
    CellularSdfConfig,
    Field3,
    GeneratedChunkOverlayMode,
    InterpolationSpace,
    Palette,
    Sdf,
    SdfCellMode,
    WorldGenerator,
    WorldSink,
)

CELL_X = 192
CELL_Z = 160
MIN_Y = -32
MAX_Y = 64
SOURCE_ID = "riverfall:infinite-forest-escarpment"
SOURCE_VERSION = "riverfall-infinite-v4-cellular-hardened"


def palette(block_ids: list[str]) -> Palette:
    return Palette.from_block_ids(json.dumps(block_ids))


def cell_config(
    presence_numerator: int = 1,
    presence_denominator: int = 1,
    feature_salt: int = 0,
) -> CellularSdfConfig:
    return CellularSdfConfig.create(
        CELL_X,
        CELL_Z,
        0x6A09E667,
        14.0,
        10.0,
        13.0,
        0.88,
        1.14,
        -2,
        3,
        presence_numerator,
        presence_denominator,
        feature_salt,
    )


def union_all(shapes: Sequence[Sdf]) -> Sdf:
    if not shapes:
        raise ValueError("at least one SDF is required")
    result = shapes[0]
    for shape in shapes[1:]:
        result = result.union_with(shape)
    return result


def capsules(points: Sequence[tuple[float, float, float]], radius: float) -> Sdf:
    return union_all(
        [
            Sdf.capsule(*start, *end, radius)
            for start, end in zip(points, points[1:])
        ]
    )


def add_sdf_layer(
    composite: WorldGenerator,
    shape: Sdf,
    brush: Brush,
    min_y: int,
    max_y: int,
    name: str,
) -> None:
    layer = WorldGenerator.sdf(
        shape,
        brush,
        min_y,
        max_y,
        f"{SOURCE_ID}:{name}",
        SOURCE_VERSION,
    )
    composite.add_layer(layer, GeneratedChunkOverlayMode.Replace)


def add_cellular_layer(
    composite: WorldGenerator,
    shape: Sdf,
    brush: Brush,
    min_y: int,
    max_y: int,
    name: str,
    config: CellularSdfConfig,
) -> None:
    layer = WorldGenerator.cellular_sdf(
        shape,
        brush,
        min_y,
        max_y,
        config,
        f"{SOURCE_ID}:{name}",
        SOURCE_VERSION,
    )
    composite.add_layer(layer, GeneratedChunkOverlayMode.Replace)


def lowland_tree_points() -> list[float]:
    """Deterministic district-local forest positions, clear of authored features."""
    rng = random.Random(23)
    offsets: list[float] = []
    for gx in range(-74, 76, 14):
        for gz in range(-68, 69, 14):
            x = gx + rng.randint(-4, 4)
            z = gz + rng.randint(-4, 4)
            near_cabin = -50 <= x <= -28 and 10 <= z <= 34
            near_fall = 3 <= x <= 28 and -7 <= z <= 15
            near_outflow = -66 <= x <= 12 and -28 <= z <= 10
            if near_cabin or near_fall or near_outflow:
                continue
            offsets.extend((float(x), 0.0, float(z)))
    return offsets


def make_source() -> WorldGenerator:
    world = WorldGenerator.composite(SOURCE_ID, SOURCE_VERSION)

    # Continuous non-repeated lowland: distant chunks remain terrain and share
    # absolute-coordinate noise without any finite boundary.
    terrain_field = Field3.value_noise_fbm(frequency=0.027, seed=31, octaves=5)
    ground = Sdf.plane(0.0, 1.0, 0.0, 0.0).offset_by_field(terrain_field, 6.5)
    ground_brush = Brush.field3(
        terrain_field,
        [0.0, 0.48, 1.0],
        [42, 45, 52, 98, 96, 88, 148, 142, 126],
        -1.0,
        1.0,
        InterpolationSpace.Oklab,
    )
    ground_brush.set_palette(
        palette(
            [
                "minecraft:deepslate",
                "minecraft:tuff",
                "minecraft:stone",
                "minecraft:andesite",
            ]
        )
    )
    add_sdf_layer(world, ground, ground_brush, MIN_Y, 10, "lowland")
    lowland_cap = ground.subtract(ground.translate(0.0, -2.0, 0.0))
    lowland_moss = lowland_cap.intersection_with(
        Sdf.cells(0.055, 211, 1.0, SdfCellMode.CellValue, 0.22)
    )
    add_sdf_layer(
        world,
        lowland_cap,
        Brush.solid("minecraft:grass_block"),
        -8,
        10,
        "lowland-grass-cap",
    )
    add_sdf_layer(
        world,
        lowland_moss,
        Brush.solid("minecraft:moss_block"),
        -8,
        10,
        "lowland-moss",
    )

    # The accepted finite scene's central escarpment recipe becomes a bounded
    # hashed-cell motif. Smooth shoulders avoid tile-wide vertical walls.
    plateau_field = Field3.value_noise_fbm(frequency=0.024, seed=73, octaves=4)
    cliff_field = Field3.value_noise_fbm(frequency=0.032, seed=91, octaves=4)
    plateau_top = Sdf.plane(0.0, 1.0, 0.0, -35.0).offset_by_field(
        plateau_field, 5.5
    )
    cliff_front = Sdf.plane(-1.0, 0.0, 0.0, 15.0).offset_by_field(cliff_field, 5.2)
    central = (
        Sdf.box_shape(29.0, 27.0, 34.0, 9.0)
        .translate(44.0, 9.0, 0.0)
        .intersection_with(plateau_top.smooth_intersection(cliff_front, 9.0))
    )
    north = Sdf.round_cone(10, 1, -39, 48, 28, -32, 22, 15).intersection_with(
        plateau_top
    )
    south = Sdf.round_cone(10, 1, 39, 48, 28, 32, 22, 15).intersection_with(
        plateau_top
    )
    cliff = central
    cracks = Sdf.cells(
        0.085, 19, 1.0, SdfCellMode.F2MinusF1, 0.46
    ).rotate(18.0, 27.0, 9.0)
    landmark_config = cell_config()
    fractured = cliff.subtract(cracks)
    cliff_brush = Brush.field3(
        cliff_field,
        [0.0, 0.42, 0.72, 1.0],
        [50, 52, 57, 105, 101, 91, 155, 149, 132, 205, 198, 177],
        -1.0,
        1.0,
        InterpolationSpace.Oklab,
    )
    cliff_brush.set_palette(
        palette(
            [
                "minecraft:cobbled_deepslate",
                "minecraft:tuff",
                "minecraft:andesite",
                "minecraft:stone",
                "minecraft:calcite",
            ]
        )
    )
    add_cellular_layer(
        world, fractured, cliff_brush, -20, 50, "fractured-cliff", landmark_config
    )
    plateau_cap = cliff.subtract(cliff.translate(0.0, -2.0, 0.0))
    plateau_moss = plateau_cap.intersection_with(
        Sdf.cells(0.05, 307, 1.0, SdfCellMode.CellValue, 0.20)
    )
    add_cellular_layer(
        world,
        plateau_cap,
        Brush.solid("minecraft:grass_block"),
        18,
        52,
        "plateau-grass-cap",
        landmark_config,
    )
    add_cellular_layer(
        world,
        plateau_moss,
        Brush.solid("minecraft:moss_block"),
        18,
        52,
        "plateau-moss",
        landmark_config,
    )
    for side, shoulder, salt in (
        ("north", north, 0xC11F_0001),
        ("south", south, 0xC11F_0002),
    ):
        shoulder_config = cell_config(1, 2, salt)
        fractured_shoulder = shoulder.subtract(cracks)
        shoulder_cap = shoulder.subtract(shoulder.translate(0.0, -2.0, 0.0))
        add_cellular_layer(
            world,
            fractured_shoulder,
            cliff_brush,
            -20,
            50,
            f"{side}-shoulder",
            shoulder_config,
        )
        add_cellular_layer(
            world,
            shoulder_cap,
            Brush.solid("minecraft:grass_block"),
            18,
            52,
            f"{side}-shoulder-cap",
            shoulder_config,
        )

    # Authored hydrology motif. The upper reach bends toward the displaced face,
    # falls in a broad sheet, enters a plunge pool, then meanders into lowland.
    upper = capsules(
        [
            (69, 35, 20),
            (58, 35, 17),
            (47, 35, 10),
            (35, 35, 12),
            (25, 35, 6),
            (18, 35, 4),
        ],
        2.4,
    )
    waterfall = Sdf.box_shape(1.8, 17.0, 3.2, 1.0).translate(14.0, 18.0, 4.0)
    pool = Sdf.ellipsoid(10.0, 2.2, 7.5).translate(8.0, 1.0, 4.0)
    outflow = capsules(
        [
            (7, 1, 4),
            (-8, 1, 1),
            (-22, 1, -7),
            (-39, 1, -12),
            (-53, 1, -19),
            (-61, 1, -22),
        ],
        2.2,
    )
    water = upper.union_with(waterfall).union_with(pool).union_with(outflow)
    add_cellular_layer(
        world,
        water,
        Brush.solid("minecraft:water"),
        -5,
        45,
        "water",
        landmark_config,
    )
    tributaries = (
        capsules([(62, 35, -31), (54, 35, -19), (47, 35, 10)], 1.7),
        capsules([(67, 35, 34), (52, 35, 25), (35, 35, 12)], 1.6),
    )
    for index, tributary in enumerate(tributaries):
        add_cellular_layer(
            world,
            tributary,
            Brush.solid("minecraft:water"),
            25,
            45,
            f"tributary-{index}",
            cell_config(1, 2, 0xA7E0_0000 + index),
        )

    # Terrain-following visual trail represented as a shallow bounded ribbon.
    path = capsules(
        [
            (-70, 2, 34),
            (-52, 2, 30),
            (-39, 2, 18),
            (-26, 2, 12),
            (-12, 2, 8),
            (1, 2, 9),
        ],
        1.35,
    )
    cabin_config = cell_config(2, 3, 0xCA81_0003)
    add_cellular_layer(
        world, path, Brush.solid("minecraft:gravel"), -3, 8, "path", cabin_config
    )

    # Optional cabin assembled from coordinated material-specific native volumes.
    foundation = Sdf.box_shape(5.0, 4.5, 4.0, 0.6).translate(-39, -3.5, 22)
    walls = Sdf.box_frame(4.5, 3.5, 3.5, 0.8).translate(-39, 4.0, 22)
    roof = Sdf.box_shape(5.5, 1.2, 4.6, 0.5).translate(-39, 8.2, 22)
    chimney = Sdf.box_shape(0.8, 3.2, 0.8, 0.2).translate(-36, 9.5, 24)
    for shape, block, y0, y1, name in (
        (foundation, "minecraft:cobblestone", -10, 6, "cabin-foundation"),
        (walls, "minecraft:spruce_planks", -3, 14, "cabin-walls"),
        (roof, "minecraft:dark_oak_planks", 3, 17, "cabin-roof"),
        (chimney, "minecraft:cobblestone", 3, 19, "cabin-chimney"),
    ):
        add_cellular_layer(
            world, shape, Brush.solid(block), y0, y1, name, cabin_config
        )

    # Forest clusters are independently selected per hashed cell.
    low_offsets = lowland_tree_points()
    low_trunk = Sdf.capped_cylinder(1.2, 7.0).translate(0, 3.0, 0)
    low_crown = Sdf.round_cone(0, 6, 0, 0, 17, 0, 4.4, 0.4)
    plateau_offsets: list[float] = []
    for x in (31, 47, 63):
        for z in (-37, -20, 21, 38):
            plateau_offsets.extend((float(x), 35.0, float(z)))
    low_points = [
        low_offsets[index : index + 3] for index in range(0, len(low_offsets), 3)
    ]
    plateau_points = [
        plateau_offsets[index : index + 3]
        for index in range(0, len(plateau_offsets), 3)
    ]
    all_points = low_points + plateau_points
    for group in range(3):
        offsets = [
            value
            for index, point in enumerate(all_points)
            if index % 3 == group
            for value in point
        ]
        trunks = low_trunk.repeat_points(offsets)
        crowns = low_crown.repeat_points(offsets)
        forest_config = cell_config(2, 3, 0xF0E5_7000 + group)
        add_cellular_layer(
            world,
            trunks,
            Brush.solid("minecraft:spruce_log"),
            -8,
            60,
            f"forest-trunks-{group}",
            forest_config,
        )
        add_cellular_layer(
            world,
            crowns,
            Brush.solid("minecraft:spruce_leaves"),
            1,
            64,
            f"forest-crowns-{group}",
            forest_config,
        )

    return world


def persist_bounds(
    source: WorldGenerator,
    output: Path,
    min_cx: int,
    min_cz: int,
    max_cx: int,
    max_cz: int,
) -> None:
    if output.exists():
        shutil.rmtree(output)
    sink = WorldSink.create(str(output), "")
    stream = source.stream(min_cx, min_cz, max_cx, max_cz)
    while stream.remaining() > 0:
        sink.write_chunk(stream.next().take_view())
    sink.finish()


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path)
    parser.add_argument("--bounds", type=int, nargs=4, metavar=("MIN_CX", "MIN_CZ", "MAX_CX", "MAX_CZ"))
    parser.add_argument("--sample", type=int, nargs=2, metavar=("CX", "CZ"), default=(0, 0))
    args = parser.parse_args()

    source = make_source()
    generated = source.generate(*args.sample)
    print(
        f"chunk=({generated.cx()},{generated.cz()}) "
        f"coverage={generated.coverage()} source={generated.source_id()} "
        f"version={generated.version()}"
    )
    generated.take_view()

    if args.output is not None:
        bounds = tuple(args.bounds or (-5, -4, 4, 3))
        persist_bounds(source, args.output, *bounds)
        print(f"wrote {args.output} bounds={bounds}")


if __name__ == "__main__":
    main()
