//! Meshing: resource packs, mesh configs/results, atlases, item models, and the
//! polling `MeshJob`. Port of `ffi/meshing.rs`.
//!
//! Porting notes (see `PORTING.md`):
//! - All binary outputs (GLB, NUCM, pixels, ZIPs, raw vertex streams) cross the
//!   boundary as base64 strings (`_b64` methods). Float/int streams are the raw
//!   little-endian bytes of the `f32`/`u32` array, base64-encoded.
//! - `schematic_mesh_chunks_with_atlas_progress` (C callback) is replaced by the
//!   polling `MeshJob` API from `stencil/docs/mesh-progress-api.md`:
//!   `MeshJob::start` spawns a background thread, `poll_progress` reads a shared
//!   progress slot without blocking, `take_result` joins and consumes the job.
//! - String lists (`StringArray` in the old ABI) are written as JSON array
//!   strings (`_json` methods).
//! - `chunkmeshresult_chunk_coordinates` (flat int array) becomes
//!   `chunk_count` + `chunk_coordinate_at(index)` returning a `BlockPos`.
//! - `itemmodel_build_resource_pack` (array-of-pointers input) becomes the
//!   `ItemModelPackBuilder` accumulator plus `ItemModelResult::add_to_pack`
//!   (consuming, per PORTING rule 11).
//! - `meshconfig_set_biome(null)` (clearing) becomes `MeshConfig::clear_biome`.
//!
//! Omitted from port: `resourcepack_free`, `meshconfig_free`, `meshresult_free`,
//! `multimeshresult_free`, `chunkmeshresult_free`, `rawmeshexport_free`,
//! `textureatlas_free`, `itemmodel_config_free`, `itemmodel_result_free`,
//! `itemmodel_zip_data_free` — destructors are generated by Diplomat.

use diplomat_runtime::DiplomatWrite;

/// Shared progress slot written by the mesh worker thread and read by
/// `MeshJob::poll_progress`. Phase: 0 = BuildingAtlas, 1 = MeshingChunks,
/// 2 = Complete, 3 = Failed.
pub(crate) struct MeshJobState {
    pub(crate) phase: u8,
    pub(crate) current: u32,
    pub(crate) total: u32,
}

/// Write `bytes` into `out` as standard base64.
pub(crate) fn write_b64(bytes: &[u8], out: &mut DiplomatWrite) {
    use base64::Engine as _;
    use std::fmt::Write as _;
    let _ = write!(
        out,
        "{}",
        base64::engine::general_purpose::STANDARD.encode(bytes)
    );
}

/// Write a `Vec<String>` into `out` as a JSON array string.
pub(crate) fn write_string_list_json(names: &[String], out: &mut DiplomatWrite) {
    use std::fmt::Write as _;
    let json = serde_json::to_string(names).unwrap_or_else(|_| "[]".to_string());
    let _ = write!(out, "{}", json);
}

/// Little-endian byte view of an `f32` slice.
pub(crate) fn f32s_to_le_bytes(floats: &[f32]) -> Vec<u8> {
    let mut bytes = Vec::with_capacity(floats.len() * 4);
    for f in floats {
        bytes.extend_from_slice(&f.to_le_bytes());
    }
    bytes
}

#[diplomat::bridge]
pub mod ffi {
    use super::super::schematic::ffi::Schematic;
    use super::super::shared::ffi::{BlockPos, Dimensions, NucleationError};
    use diplomat_runtime::DiplomatWrite;
    use std::fmt::Write;

    // ─── ResourcePack ────────────────────────────────────────────────────────

    /// A loaded (possibly merged) Minecraft resource pack.
    /// Wraps [`crate::meshing::ResourcePackSource`].
    #[diplomat::opaque_mut]
    pub struct ResourcePack(pub(crate) crate::meshing::ResourcePackSource);

    /// Ordered list of raw resource-pack ZIP buffers, lowest priority first.
    /// Feed it to [`ResourcePack::from_list`].
    #[diplomat::opaque_mut]
    pub struct ResourcePackList(pub(crate) Vec<Vec<u8>>);

    impl ResourcePackList {
        /// Create an empty resource-pack list.
        pub fn create() -> Box<ResourcePackList> {
            Box::new(ResourcePackList(Vec::new()))
        }

        /// Append one resource-pack ZIP buffer. Later buffers overlay earlier
        /// ones on per-key collision (Minecraft pack-ordering semantics).
        pub fn add(&mut self, data: &[u8]) {
            self.0.push(data.to_vec());
        }

        /// Number of pack buffers added so far.
        pub fn len(&self) -> u32 {
            self.0.len() as u32
        }
    }

    impl ResourcePack {
        /// Load a resource pack from an in-memory ZIP buffer.
        pub fn from_bytes(data: &[u8]) -> Result<Box<ResourcePack>, NucleationError> {
            crate::meshing::ResourcePackSource::from_bytes(data)
                .map(|p| Box::new(ResourcePack(p)))
                .map_err(|_| NucleationError::Parse)
        }

        /// Load and merge multiple resource packs, lowest priority first.
        pub fn from_list(list: &ResourcePackList) -> Result<Box<ResourcePack>, NucleationError> {
            crate::meshing::ResourcePackSource::from_bytes_list(list.0.clone())
                .map(|p| Box::new(ResourcePack(p)))
                .map_err(|_| NucleationError::Parse)
        }

        /// Number of blockstate definitions in the pack.
        pub fn blockstate_count(&self) -> u32 {
            self.0.stats().blockstate_count as u32
        }

        /// Number of model definitions in the pack.
        pub fn model_count(&self) -> u32 {
            self.0.stats().model_count as u32
        }

        /// Number of textures in the pack.
        pub fn texture_count(&self) -> u32 {
            self.0.stats().texture_count as u32
        }

        /// Namespaces present in the pack, as a JSON array string.
        pub fn namespaces_json(&self, out: &mut DiplomatWrite) {
            super::write_string_list_json(&self.0.stats().namespaces, out);
        }

        /// All blockstate identifiers, as a JSON array string.
        pub fn list_blockstates_json(&self, out: &mut DiplomatWrite) {
            super::write_string_list_json(&self.0.list_blockstates(), out);
        }

        /// All model identifiers, as a JSON array string.
        pub fn list_models_json(&self, out: &mut DiplomatWrite) {
            super::write_string_list_json(&self.0.list_models(), out);
        }

        /// All texture identifiers, as a JSON array string.
        pub fn list_textures_json(&self, out: &mut DiplomatWrite) {
            super::write_string_list_json(&self.0.list_textures(), out);
        }

        /// The blockstate definition JSON for `name`; `NotFound` if absent.
        pub fn get_blockstate_json(
            &self,
            name: &DiplomatStr,
            out: &mut DiplomatWrite,
        ) -> Result<(), NucleationError> {
            let name = std::str::from_utf8(name).map_err(|_| NucleationError::InvalidArgument)?;
            match self.0.get_blockstate_json(name) {
                Some(json) => {
                    let _ = write!(out, "{}", json);
                    Ok(())
                }
                None => Err(NucleationError::NotFound),
            }
        }

        /// The model definition JSON for `name`; `NotFound` if absent.
        pub fn get_model_json(
            &self,
            name: &DiplomatStr,
            out: &mut DiplomatWrite,
        ) -> Result<(), NucleationError> {
            let name = std::str::from_utf8(name).map_err(|_| NucleationError::InvalidArgument)?;
            match self.0.get_model_json(name) {
                Some(json) => {
                    let _ = write!(out, "{}", json);
                    Ok(())
                }
                None => Err(NucleationError::NotFound),
            }
        }

        /// Texture metadata (size, animation flag, frame count).
        pub fn get_texture_info(&self, name: &DiplomatStr) -> Result<TextureInfo, NucleationError> {
            let name = std::str::from_utf8(name).map_err(|_| NucleationError::InvalidArgument)?;
            match self.0.get_texture_info(name) {
                Some((width, height, animated, frame_count)) => Ok(TextureInfo {
                    width,
                    height,
                    animated,
                    frame_count,
                }),
                None => Err(NucleationError::NotFound),
            }
        }

        /// Raw RGBA pixels of a texture, base64-encoded.
        pub fn get_texture_pixels_b64(
            &self,
            name: &DiplomatStr,
            out: &mut DiplomatWrite,
        ) -> Result<(), NucleationError> {
            let name = std::str::from_utf8(name).map_err(|_| NucleationError::InvalidArgument)?;
            match self.0.get_texture_pixels(name) {
                Some(pixels) => {
                    super::write_b64(pixels, out);
                    Ok(())
                }
                None => Err(NucleationError::NotFound),
            }
        }

        /// Add (or override) a blockstate definition from a JSON string.
        pub fn add_blockstate_json(
            &mut self,
            name: &DiplomatStr,
            json: &DiplomatStr,
        ) -> Result<(), NucleationError> {
            let name = std::str::from_utf8(name).map_err(|_| NucleationError::InvalidArgument)?;
            let json = std::str::from_utf8(json).map_err(|_| NucleationError::InvalidArgument)?;
            self.0
                .add_blockstate_json(name, json)
                .map_err(|_| NucleationError::Parse)
        }

        /// Add (or override) a model definition from a JSON string.
        pub fn add_model_json(
            &mut self,
            name: &DiplomatStr,
            json: &DiplomatStr,
        ) -> Result<(), NucleationError> {
            let name = std::str::from_utf8(name).map_err(|_| NucleationError::InvalidArgument)?;
            let json = std::str::from_utf8(json).map_err(|_| NucleationError::InvalidArgument)?;
            self.0
                .add_model_json(name, json)
                .map_err(|_| NucleationError::Parse)
        }

        /// Add a raw RGBA texture (`pixels` length must be `width * height * 4`).
        pub fn add_texture(
            &mut self,
            name: &DiplomatStr,
            width: u32,
            height: u32,
            pixels: &[u8],
        ) -> Result<(), NucleationError> {
            let name = std::str::from_utf8(name).map_err(|_| NucleationError::InvalidArgument)?;
            self.0
                .add_texture(name, width, height, pixels.to_vec())
                .map_err(|_| NucleationError::InvalidArgument)
        }

        /// Register a MeshExporter with the FormatManager so `save_as("mesh", ...)`
        /// works. (Old ABI: `schematic_register_mesh_exporter`.)
        pub fn register_mesh_exporter(&self) -> Result<(), NucleationError> {
            let exporter = crate::meshing::MeshExporter::new(
                crate::meshing::ResourcePackSource::from_resource_pack(self.0.pack().clone()),
            );
            let manager = crate::formats::manager::get_manager();
            let mut manager = manager.lock().map_err(|_| NucleationError::Lock)?;
            manager.register_exporter(exporter);
            Ok(())
        }
    }

    // ─── MeshConfig ──────────────────────────────────────────────────────────

    /// Texture size/animation metadata for one texture in a resource pack.
    pub struct TextureInfo {
        pub width: u32,
        pub height: u32,
        pub animated: bool,
        pub frame_count: u32,
    }

    /// Mesh generation configuration. Wraps [`crate::meshing::MeshConfig`].
    #[diplomat::opaque_mut]
    pub struct MeshConfig(pub(crate) crate::meshing::MeshConfig);

    impl MeshConfig {
        /// Create a config with default settings: hidden-face culling on,
        /// ambient occlusion on (intensity 0.4), no biome, atlas max size 4096,
        /// occluded-block culling on, greedy meshing off.
        pub fn create() -> Box<MeshConfig> {
            Box::new(MeshConfig(crate::meshing::MeshConfig::default()))
        }

        /// Enable face culling between adjacent solid blocks (default: true).
        pub fn set_cull_hidden_faces(&mut self, val: bool) {
            self.0.cull_hidden_faces = val;
        }

        /// Whether hidden-face culling is enabled.
        pub fn cull_hidden_faces(&self) -> bool {
            self.0.cull_hidden_faces
        }

        /// Enable ambient occlusion (default: true).
        pub fn set_ambient_occlusion(&mut self, val: bool) {
            self.0.ambient_occlusion = val;
        }

        /// Whether ambient occlusion is enabled.
        pub fn ambient_occlusion(&self) -> bool {
            self.0.ambient_occlusion
        }

        /// Set ambient-occlusion intensity, 0.0 (no darkening) to 1.0 (full
        /// darkening). Default: 0.4.
        pub fn set_ao_intensity(&mut self, val: f32) {
            self.0.ao_intensity = val;
        }

        /// The ambient-occlusion intensity (0.0–1.0).
        pub fn ao_intensity(&self) -> f32 {
            self.0.ao_intensity
        }

        /// Set the biome used for tinting (e.g. "plains", "swamp").
        pub fn set_biome(&mut self, biome: &DiplomatStr) -> Result<(), NucleationError> {
            let biome = std::str::from_utf8(biome).map_err(|_| NucleationError::InvalidArgument)?;
            self.0.biome = Some(biome.to_string());
            Ok(())
        }

        /// Clear the biome (old ABI: `meshconfig_set_biome(NULL)`).
        pub fn clear_biome(&mut self) {
            self.0.biome = None;
        }

        /// The configured biome; `NotFound` if none is set.
        pub fn biome(&self, out: &mut DiplomatWrite) -> Result<(), NucleationError> {
            match &self.0.biome {
                Some(biome) => {
                    let _ = write!(out, "{}", biome);
                    Ok(())
                }
                None => Err(NucleationError::NotFound),
            }
        }

        /// Set the maximum texture-atlas dimension in pixels (default: 4096).
        pub fn set_atlas_max_size(&mut self, size: u32) {
            self.0.atlas_max_size = size;
        }

        /// The maximum texture-atlas dimension in pixels.
        pub fn atlas_max_size(&self) -> u32 {
            self.0.atlas_max_size
        }

        /// Skip blocks fully hidden by opaque neighbors on all 6 sides
        /// (default: true).
        pub fn set_cull_occluded_blocks(&mut self, val: bool) {
            self.0.cull_occluded_blocks = val;
        }

        /// Whether occluded-block culling is enabled.
        pub fn cull_occluded_blocks(&self) -> bool {
            self.0.cull_occluded_blocks
        }

        /// Merge adjacent coplanar faces into larger quads to reduce triangle
        /// count (default: false).
        pub fn set_greedy_meshing(&mut self, val: bool) {
            self.0.greedy_meshing = val;
        }

        /// Whether greedy meshing is enabled.
        pub fn greedy_meshing(&self) -> bool {
            self.0.greedy_meshing
        }
    }

    // ─── MeshResult ──────────────────────────────────────────────────────────

    /// Axis-aligned bounding box of a mesh result.
    pub struct MeshBounds {
        pub min_x: f32,
        pub min_y: f32,
        pub min_z: f32,
        pub max_x: f32,
        pub max_y: f32,
        pub max_z: f32,
    }

    /// A single mesh output. Wraps [`crate::meshing::MeshResult`].
    #[diplomat::opaque]
    pub struct MeshResult(pub(crate) crate::meshing::MeshResult);

    impl MeshResult {
        /// Mesh an entire schematic in one pass (old ABI: `schematic_to_mesh`).
        pub fn create(
            schematic: &Schematic,
            pack: &ResourcePack,
            config: &MeshConfig,
        ) -> Result<Box<MeshResult>, NucleationError> {
            schematic
                .0
                .to_mesh(&pack.0, &config.0)
                .map(|r| Box::new(MeshResult(r)))
                .map_err(|_| NucleationError::Mesh)
        }

        /// Mesh a schematic with USDZ-compatible output (old ABI: `schematic_to_usdz`).
        pub fn create_usdz(
            schematic: &Schematic,
            pack: &ResourcePack,
            config: &MeshConfig,
        ) -> Result<Box<MeshResult>, NucleationError> {
            schematic
                .0
                .to_usdz(&pack.0, &config.0)
                .map(|r| Box::new(MeshResult(r)))
                .map_err(|_| NucleationError::Mesh)
        }

        /// The mesh as a binary GLB, base64-encoded.
        pub fn glb_data_b64(&self, out: &mut DiplomatWrite) -> Result<(), NucleationError> {
            let data = self.0.to_glb().map_err(|_| NucleationError::Serialize)?;
            super::write_b64(&data, out);
            Ok(())
        }

        /// The mesh serialized in the NUCM cache format, base64-encoded.
        pub fn nucm_data_b64(&self, out: &mut DiplomatWrite) {
            let data = crate::meshing::cache::serialize_meshes(&[self.0.clone()]);
            super::write_b64(&data, out);
        }

        /// Total number of vertices in the mesh.
        pub fn vertex_count(&self) -> u32 {
            self.0.total_vertices() as u32
        }

        /// Total number of triangles in the mesh.
        pub fn triangle_count(&self) -> u32 {
            self.0.total_triangles() as u32
        }

        /// Whether the mesh contains any transparent or translucent geometry.
        pub fn has_transparency(&self) -> bool {
            self.0.has_transparency()
        }

        /// Axis-aligned bounding box of the mesh, in world units.
        pub fn bounds(&self) -> MeshBounds {
            MeshBounds {
                min_x: self.0.bounds.min[0],
                min_y: self.0.bounds.min[1],
                min_z: self.0.bounds.min[2],
                max_x: self.0.bounds.max[0],
                max_y: self.0.bounds.max[1],
                max_z: self.0.bounds.max[2],
            }
        }
    }

    // ─── MultiMeshResult ─────────────────────────────────────────────────────

    /// Per-region mesh results. Wraps [`crate::meshing::MultiMeshResult`].
    #[diplomat::opaque]
    pub struct MultiMeshResult(pub(crate) crate::meshing::MultiMeshResult);

    impl MultiMeshResult {
        /// Mesh each region separately (old ABI: `schematic_mesh_by_region`).
        pub fn create(
            schematic: &Schematic,
            pack: &ResourcePack,
            config: &MeshConfig,
        ) -> Result<Box<MultiMeshResult>, NucleationError> {
            schematic
                .0
                .mesh_by_region(&pack.0, &config.0)
                .map(|r| Box::new(MultiMeshResult(r)))
                .map_err(|_| NucleationError::Mesh)
        }

        /// Region names, as a JSON array string.
        pub fn region_names_json(&self, out: &mut DiplomatWrite) {
            let names: Vec<String> = self.0.keys().cloned().collect();
            super::write_string_list_json(&names, out);
        }

        /// The mesh for one region (cloned).
        pub fn get_mesh(
            &self,
            region_name: &DiplomatStr,
        ) -> Result<Box<MeshResult>, NucleationError> {
            let name =
                std::str::from_utf8(region_name).map_err(|_| NucleationError::InvalidArgument)?;
            match self.0.get(name) {
                Some(mesh) => Ok(Box::new(MeshResult(mesh.clone()))),
                None => Err(NucleationError::NotFound),
            }
        }

        /// Total vertex count across all region meshes.
        pub fn total_vertex_count(&self) -> u32 {
            self.0.values().map(|m| m.total_vertices()).sum::<usize>() as u32
        }

        /// Total triangle count across all region meshes.
        pub fn total_triangle_count(&self) -> u32 {
            self.0.values().map(|m| m.total_triangles()).sum::<usize>() as u32
        }

        /// Number of region meshes.
        pub fn mesh_count(&self) -> u32 {
            self.0.len() as u32
        }
    }

    // ─── ChunkMeshResult ─────────────────────────────────────────────────────

    /// Per-chunk mesh results. Wraps [`crate::meshing::ChunkMeshResult`].
    #[diplomat::opaque]
    pub struct ChunkMeshResult(pub(crate) crate::meshing::ChunkMeshResult);

    impl ChunkMeshResult {
        /// Mesh with the default chunk size (old ABI: `schematic_mesh_by_chunk`).
        pub fn create(
            schematic: &Schematic,
            pack: &ResourcePack,
            config: &MeshConfig,
        ) -> Result<Box<ChunkMeshResult>, NucleationError> {
            schematic
                .0
                .mesh_by_chunk(&pack.0, &config.0)
                .map(|r| Box::new(ChunkMeshResult(r)))
                .map_err(|_| NucleationError::Mesh)
        }

        /// Mesh with an explicit chunk size (old ABI: `schematic_mesh_by_chunk_size`).
        pub fn create_with_size(
            schematic: &Schematic,
            pack: &ResourcePack,
            config: &MeshConfig,
            chunk_size: i32,
        ) -> Result<Box<ChunkMeshResult>, NucleationError> {
            schematic
                .0
                .mesh_by_chunk_size(&pack.0, &config.0, chunk_size)
                .map(|r| Box::new(ChunkMeshResult(r)))
                .map_err(|_| NucleationError::Mesh)
        }

        /// Mesh chunks against a pre-built shared atlas, synchronously
        /// (old ABI: `schematic_mesh_chunks_with_atlas`). For progress
        /// reporting use [`MeshJob::start`] instead.
        pub fn create_with_atlas(
            schematic: &Schematic,
            pack: &ResourcePack,
            config: &MeshConfig,
            chunk_size: i32,
            atlas: &TextureAtlas,
        ) -> Result<Box<ChunkMeshResult>, NucleationError> {
            let iter =
                schematic
                    .0
                    .mesh_chunks_with_atlas(&pack.0, &config.0, chunk_size, atlas.0.clone());
            let mut meshes = std::collections::HashMap::new();
            let mut total_vertex_count = 0;
            let mut total_triangle_count = 0;
            for result in iter {
                let mesh = result.map_err(|_| NucleationError::Mesh)?;
                total_vertex_count += mesh.total_vertices();
                total_triangle_count += mesh.total_triangles();
                if let Some(coord) = mesh.chunk_coord {
                    meshes.insert(coord, mesh);
                }
            }
            Ok(Box::new(ChunkMeshResult(crate::meshing::ChunkMeshResult {
                meshes,
                total_vertex_count,
                total_triangle_count,
            })))
        }

        /// Number of chunk meshes.
        pub fn chunk_count(&self) -> u32 {
            self.0.meshes.len() as u32
        }

        /// Coordinate of the `index`-th chunk (old ABI:
        /// `chunkmeshresult_chunk_coordinates` returned all of them flat).
        pub fn chunk_coordinate_at(&self, index: u32) -> Result<BlockPos, NucleationError> {
            match self.0.meshes.keys().nth(index as usize) {
                Some(&(x, y, z)) => Ok(BlockPos { x, y, z }),
                None => Err(NucleationError::NotFound),
            }
        }

        /// The mesh for one chunk coordinate (cloned).
        pub fn get_mesh(
            &self,
            cx: i32,
            cy: i32,
            cz: i32,
        ) -> Result<Box<MeshResult>, NucleationError> {
            match self.0.meshes.get(&(cx, cy, cz)) {
                Some(mesh) => Ok(Box::new(MeshResult(mesh.clone()))),
                None => Err(NucleationError::NotFound),
            }
        }

        /// Total vertex count across all chunk meshes.
        pub fn total_vertex_count(&self) -> u32 {
            self.0.total_vertex_count as u32
        }

        /// Total triangle count across all chunk meshes.
        pub fn total_triangle_count(&self) -> u32 {
            self.0.total_triangle_count as u32
        }

        /// All chunk meshes serialized in the NUCM cache format, base64-encoded.
        pub fn nucm_data_b64(&self, out: &mut DiplomatWrite) {
            let meshes: Vec<crate::meshing::MeshOutput> = self.0.meshes.values().cloned().collect();
            let data = crate::meshing::cache::serialize_meshes(&meshes);
            super::write_b64(&data, out);
        }

        /// NUCM v2 with a shared atlas, base64-encoded.
        pub fn nucm_data_with_atlas_b64(&self, atlas: &TextureAtlas, out: &mut DiplomatWrite) {
            let meshes: Vec<crate::meshing::MeshOutput> = self.0.meshes.values().cloned().collect();
            let data = crate::meshing::cache::serialize_meshes_with_atlas(&meshes, &atlas.0);
            super::write_b64(&data, out);
        }
    }

    // ─── RawMeshExport ───────────────────────────────────────────────────────

    /// Raw vertex streams for custom rendering. Wraps [`crate::meshing::RawMeshExport`].
    #[diplomat::opaque]
    pub struct RawMeshExport(pub(crate) crate::meshing::RawMeshExport);

    impl RawMeshExport {
        /// Export raw mesh data (old ABI: `schematic_to_raw_mesh`).
        pub fn create(
            schematic: &Schematic,
            pack: &ResourcePack,
            config: &MeshConfig,
        ) -> Result<Box<RawMeshExport>, NucleationError> {
            schematic
                .0
                .to_raw_mesh(&pack.0, &config.0)
                .map(|r| Box::new(RawMeshExport(r)))
                .map_err(|_| NucleationError::Mesh)
        }

        /// Number of vertices in the exported mesh.
        pub fn vertex_count(&self) -> u32 {
            self.0.vertex_count() as u32
        }

        /// Number of triangles in the exported mesh.
        pub fn triangle_count(&self) -> u32 {
            self.0.triangle_count() as u32
        }

        /// Flat `[x,y,z,...]` positions as little-endian `f32` bytes, base64-encoded.
        pub fn positions_b64(&self, out: &mut DiplomatWrite) {
            super::write_b64(&super::f32s_to_le_bytes(&self.0.positions_flat()), out);
        }

        /// Flat normals as little-endian `f32` bytes, base64-encoded.
        pub fn normals_b64(&self, out: &mut DiplomatWrite) {
            super::write_b64(&super::f32s_to_le_bytes(&self.0.normals_flat()), out);
        }

        /// Flat UVs as little-endian `f32` bytes, base64-encoded.
        pub fn uvs_b64(&self, out: &mut DiplomatWrite) {
            super::write_b64(&super::f32s_to_le_bytes(&self.0.uvs_flat()), out);
        }

        /// Flat vertex colors as little-endian `f32` bytes, base64-encoded.
        pub fn colors_b64(&self, out: &mut DiplomatWrite) {
            super::write_b64(&super::f32s_to_le_bytes(&self.0.colors_flat()), out);
        }

        /// Triangle indices as little-endian `u32` bytes, base64-encoded.
        pub fn indices_b64(&self, out: &mut DiplomatWrite) {
            let mut bytes = Vec::with_capacity(self.0.indices().len() * 4);
            for i in self.0.indices() {
                bytes.extend_from_slice(&i.to_le_bytes());
            }
            super::write_b64(&bytes, out);
        }

        /// Raw RGBA texture pixels, base64-encoded.
        pub fn texture_rgba_b64(&self, out: &mut DiplomatWrite) {
            super::write_b64(self.0.texture_rgba(), out);
        }

        /// Width of the baked texture in pixels.
        pub fn texture_width(&self) -> u32 {
            self.0.texture_width()
        }

        /// Height of the baked texture in pixels.
        pub fn texture_height(&self) -> u32 {
            self.0.texture_height()
        }
    }

    // ─── TextureAtlas ────────────────────────────────────────────────────────

    /// A packed texture atlas. Wraps [`schematic_mesher::TextureAtlas`].
    #[diplomat::opaque]
    pub struct TextureAtlas(pub(crate) schematic_mesher::TextureAtlas);

    impl TextureAtlas {
        /// Build a single shared atlas from every unique block state in the
        /// schematic (old ABI: `schematic_build_global_atlas`).
        pub fn build_global(
            schematic: &Schematic,
            pack: &ResourcePack,
            config: &MeshConfig,
        ) -> Result<Box<TextureAtlas>, NucleationError> {
            crate::meshing::build_global_atlas(&schematic.0, &pack.0, &config.0)
                .map(|a| Box::new(TextureAtlas(a)))
                .map_err(|_| NucleationError::Mesh)
        }

        /// Atlas width in pixels.
        pub fn width(&self) -> u32 {
            self.0.width
        }

        /// Atlas height in pixels.
        pub fn height(&self) -> u32 {
            self.0.height
        }

        /// Raw RGBA atlas pixels, base64-encoded.
        pub fn rgba_data_b64(&self, out: &mut DiplomatWrite) {
            super::write_b64(&self.0.pixels, out);
        }
    }

    // ─── MeshJob: polling replacement for the progress callback ─────────────

    /// Phase of a running [`MeshJob`].
    #[derive(PartialEq, Eq)]
    pub enum MeshPhase {
        /// Scanning palettes / building the shared texture atlas.
        BuildingAtlas,
        /// Meshing individual chunks (`current` / `total` advance here).
        MeshingChunks,
        /// All chunks meshed; `take_result` will not block.
        Complete,
        /// The job failed; `take_result` returns the error.
        Failed,
    }

    /// Snapshot of a [`MeshJob`]'s progress.
    pub struct MeshProgress {
        pub phase: MeshPhase,
        /// Chunks completed so far.
        pub current: u32,
        /// Total chunks to mesh (0 until known).
        pub total: u32,
    }

    /// A chunk-meshing job running on a background thread. Replaces the old
    /// `schematic_mesh_chunks_with_atlas_progress` C callback: poll it from a
    /// timer loop with [`MeshJob::poll_progress`], then call
    /// [`MeshJob::take_result`] once (it blocks until the job finishes and
    /// consumes the job — a second call returns `AlreadyConsumed`).
    #[diplomat::opaque_mut]
    pub struct MeshJob {
        pub(crate) state: std::sync::Arc<std::sync::Mutex<super::MeshJobState>>,
        pub(crate) handle:
            Option<std::thread::JoinHandle<Result<crate::meshing::ChunkMeshResult, String>>>,
    }

    impl MeshJob {
        /// Kick off chunk meshing with a shared atlas on a background thread
        /// and return immediately. Takes the same parameters as
        /// [`ChunkMeshResult::create_with_atlas`].
        pub fn start(
            schematic: &Schematic,
            pack: &ResourcePack,
            config: &MeshConfig,
            chunk_size: i32,
            atlas: &TextureAtlas,
        ) -> Box<MeshJob> {
            let schematic = schematic.0.clone();
            let pack =
                crate::meshing::ResourcePackSource::from_resource_pack(pack.0.pack().clone());
            let config = config.0.clone();
            let atlas = atlas.0.clone();

            let state = std::sync::Arc::new(std::sync::Mutex::new(super::MeshJobState {
                phase: 0,
                current: 0,
                total: 0,
            }));
            let thread_state = state.clone();

            let handle = std::thread::spawn(move || {
                let mut iter = schematic.mesh_chunks_with_atlas(&pack, &config, chunk_size, atlas);
                if let Ok(mut s) = thread_state.lock() {
                    s.phase = 1;
                    s.total = iter.chunk_count() as u32;
                }
                let cb_state = thread_state.clone();
                iter.set_progress_callback(Box::new(move |p: crate::meshing::MeshProgress| {
                    if let Ok(mut s) = cb_state.lock() {
                        s.phase = match p.phase {
                            crate::meshing::MeshPhase::BuildingAtlas => 0,
                            crate::meshing::MeshPhase::MeshingChunks => 1,
                            crate::meshing::MeshPhase::Complete => 2,
                        };
                        s.current = p.chunks_done;
                        s.total = p.chunks_total;
                    }
                }));

                let mut meshes = std::collections::HashMap::new();
                let mut total_vertex_count = 0;
                let mut total_triangle_count = 0;
                for result in iter {
                    match result {
                        Ok(mesh) => {
                            total_vertex_count += mesh.total_vertices();
                            total_triangle_count += mesh.total_triangles();
                            if let Some(coord) = mesh.chunk_coord {
                                meshes.insert(coord, mesh);
                            }
                        }
                        Err(e) => {
                            if let Ok(mut s) = thread_state.lock() {
                                s.phase = 3;
                            }
                            return Err(e.to_string());
                        }
                    }
                }
                if let Ok(mut s) = thread_state.lock() {
                    s.phase = 2;
                    s.current = s.total;
                }
                Ok(crate::meshing::ChunkMeshResult {
                    meshes,
                    total_vertex_count,
                    total_triangle_count,
                })
            });

            Box::new(MeshJob {
                state,
                handle: Some(handle),
            })
        }

        /// Cheap, non-blocking progress snapshot. Call from a timer/poll loop.
        pub fn poll_progress(&self) -> MeshProgress {
            match self.state.lock() {
                Ok(s) => MeshProgress {
                    phase: match s.phase {
                        0 => MeshPhase::BuildingAtlas,
                        1 => MeshPhase::MeshingChunks,
                        2 => MeshPhase::Complete,
                        _ => MeshPhase::Failed,
                    },
                    current: s.current,
                    total: s.total,
                },
                Err(_) => MeshProgress {
                    phase: MeshPhase::Failed,
                    current: 0,
                    total: 0,
                },
            }
        }

        /// Block until the job finishes (if it hasn't already) and return the
        /// result. Consumes the job: a second call returns `AlreadyConsumed`.
        pub fn take_result(&mut self) -> Result<Box<ChunkMeshResult>, NucleationError> {
            let handle = self.handle.take().ok_or(NucleationError::AlreadyConsumed)?;
            let result = handle.join().map_err(|_| NucleationError::Mesh)?;
            result
                .map(|r| Box::new(ChunkMeshResult(r)))
                .map_err(|_| NucleationError::Mesh)
        }
    }

    // ─── Item models ─────────────────────────────────────────────────────────

    /// Non-uniform model scale factors.
    pub struct ItemScale {
        pub x: f32,
        pub y: f32,
        pub z: f32,
    }

    /// Item model generation configuration. Wraps [`crate::meshing::ItemModelConfig`].
    #[diplomat::opaque_mut]
    pub struct ItemModelConfig(pub(crate) crate::meshing::ItemModelConfig);

    impl ItemModelConfig {
        /// Create a config for a model named `model_name` (used in resource-pack
        /// file paths). Other options start at their defaults: namespace
        /// "nucleation", centered, 16px texture resolution, item "paper",
        /// custom model data "1", auto scale.
        pub fn create(model_name: &DiplomatStr) -> Result<Box<ItemModelConfig>, NucleationError> {
            let name =
                std::str::from_utf8(model_name).map_err(|_| NucleationError::InvalidArgument)?;
            Ok(Box::new(ItemModelConfig(
                crate::meshing::ItemModelConfig::new(name),
            )))
        }

        /// Set the resource-pack namespace (default: "nucleation").
        pub fn set_namespace(&mut self, namespace: &DiplomatStr) -> Result<(), NucleationError> {
            let ns =
                std::str::from_utf8(namespace).map_err(|_| NucleationError::InvalidArgument)?;
            self.0.namespace = ns.to_string();
            Ok(())
        }

        /// Center the schematic within the model bounds (default: true).
        pub fn set_center(&mut self, center: bool) {
            self.0.center = center;
        }

        /// Set the texture resolution in pixels per block face (default: 16).
        pub fn set_texture_resolution(&mut self, resolution: u32) {
            self.0.texture_resolution = resolution;
        }

        /// Set the Minecraft item the model binds to (default: "paper").
        pub fn set_item(&mut self, item: &DiplomatStr) -> Result<(), NucleationError> {
            let item = std::str::from_utf8(item).map_err(|_| NucleationError::InvalidArgument)?;
            self.0.item = item.to_string();
            Ok(())
        }

        /// Set the custom-model-data string used to select this model in game
        /// (default: "1").
        pub fn set_custom_model_data(&mut self, cmd: &DiplomatStr) -> Result<(), NucleationError> {
            let cmd = std::str::from_utf8(cmd).map_err(|_| NucleationError::InvalidArgument)?;
            self.0.custom_model_data = cmd.to_string();
            Ok(())
        }

        /// Uniform scale.
        pub fn set_scale(&mut self, scale: f32) {
            self.0.scale = crate::meshing::ItemModelScale::Uniform(scale);
        }

        /// Per-axis scale.
        pub fn set_scale_xyz(&mut self, sx: f32, sy: f32, sz: f32) {
            self.0.scale = crate::meshing::ItemModelScale::NonUniform(sx, sy, sz);
        }

        /// Auto-fit scale.
        pub fn set_scale_auto(&mut self) {
            self.0.scale = crate::meshing::ItemModelScale::Auto;
        }
    }

    /// A generated item model. Wraps [`crate::meshing::ItemModelResult`].
    ///
    /// Holds `Option<...>` because [`ItemModelResult::add_to_pack`] moves the
    /// inner value into an [`ItemModelPackBuilder`] (PORTING rule 11); accessors
    /// return `AlreadyConsumed` afterwards.
    #[diplomat::opaque_mut]
    pub struct ItemModelResult(pub(crate) Option<crate::meshing::ItemModelResult>);

    impl ItemModelResult {
        /// Generate an item model from a schematic (old ABI: `schematic_to_item_model`).
        pub fn create(
            schematic: &Schematic,
            pack: &ResourcePack,
            config: &ItemModelConfig,
        ) -> Result<Box<ItemModelResult>, NucleationError> {
            schematic
                .0
                .to_item_model(&pack.0, &config.0)
                .map(|r| Box::new(ItemModelResult(Some(r))))
                .map_err(|_| NucleationError::Mesh)
        }

        /// The Minecraft item model JSON.
        pub fn model_json(&self, out: &mut DiplomatWrite) -> Result<(), NucleationError> {
            let inner = self.0.as_ref().ok_or(NucleationError::AlreadyConsumed)?;
            let _ = write!(out, "{}", inner.model_json);
            Ok(())
        }

        /// Number of elements (cuboids) in the generated model.
        pub fn element_count(&self) -> Result<u32, NucleationError> {
            let inner = self.0.as_ref().ok_or(NucleationError::AlreadyConsumed)?;
            Ok(inner.stats.element_count as u32)
        }

        /// Number of textures the generated model uses.
        pub fn texture_count(&self) -> Result<u32, NucleationError> {
            let inner = self.0.as_ref().ok_or(NucleationError::AlreadyConsumed)?;
            Ok(inner.stats.texture_count as u32)
        }

        /// Number of textured planes in the generated model.
        pub fn plane_count(&self) -> Result<u32, NucleationError> {
            let inner = self.0.as_ref().ok_or(NucleationError::AlreadyConsumed)?;
            Ok(inner.stats.plane_count as u32)
        }

        /// Source schematic dimensions in blocks.
        pub fn dimensions(&self) -> Result<Dimensions, NucleationError> {
            let inner = self.0.as_ref().ok_or(NucleationError::AlreadyConsumed)?;
            let (x, y, z) = inner.stats.dimensions;
            Ok(Dimensions { x, y, z })
        }

        /// The applied model scale (old ABI: `itemmodel_result_scale`).
        pub fn scale(&self) -> Result<ItemScale, NucleationError> {
            let inner = self.0.as_ref().ok_or(NucleationError::AlreadyConsumed)?;
            let (x, y, z) = inner.stats.scale;
            Ok(ItemScale { x, y, z })
        }

        /// A single-model resource pack ZIP, base64-encoded.
        pub fn to_resource_pack_zip_b64(
            &self,
            out: &mut DiplomatWrite,
        ) -> Result<(), NucleationError> {
            let inner = self.0.as_ref().ok_or(NucleationError::AlreadyConsumed)?;
            let data = inner
                .to_resource_pack_zip()
                .map_err(|_| NucleationError::Serialize)?;
            super::write_b64(&data, out);
            Ok(())
        }

        /// Move this result into a pack builder. Consumes the result: further
        /// accessor calls return `AlreadyConsumed`.
        pub fn add_to_pack(
            &mut self,
            builder: &ItemModelPackBuilder,
        ) -> Result<(), NucleationError> {
            let inner = self.0.take().ok_or(NucleationError::AlreadyConsumed)?;
            builder
                .0
                .try_borrow_mut()
                .map_err(|_| NucleationError::Lock)?
                .push(inner);
            Ok(())
        }
    }

    /// Accumulates [`ItemModelResult`]s to build a combined resource pack ZIP
    /// (old ABI: `itemmodel_build_resource_pack` took an array of pointers).
    #[diplomat::opaque]
    pub struct ItemModelPackBuilder(
        pub(crate) std::cell::RefCell<Vec<crate::meshing::ItemModelResult>>,
    );

    impl ItemModelPackBuilder {
        /// Create an empty pack builder.
        pub fn create() -> Box<ItemModelPackBuilder> {
            Box::new(ItemModelPackBuilder(std::cell::RefCell::new(Vec::new())))
        }

        /// Number of results added so far.
        pub fn len(&self) -> u32 {
            self.0.borrow().len() as u32
        }

        /// Build a resource pack ZIP from every added result, base64-encoded.
        pub fn build_zip_b64(&self, out: &mut DiplomatWrite) -> Result<(), NucleationError> {
            let items = self.0.try_borrow().map_err(|_| NucleationError::Lock)?;
            if items.is_empty() {
                return Err(NucleationError::InvalidArgument);
            }
            let refs: Vec<&crate::meshing::ItemModelResult> = items.iter().collect();
            let data = crate::meshing::build_resource_pack(&refs)
                .map_err(|_| NucleationError::Serialize)?;
            super::write_b64(&data, out);
            Ok(())
        }
    }
}
