#!/usr/bin/env python3
"""Assemble REPORT.md from results.jsonl / variants.jsonl / critiques.jsonl /
codex_log.jsonl. Pure aggregation: every number in the report comes from a run."""

import argparse
import collections
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))


def load(path):
    if not os.path.exists(path):
        return []
    out = []
    for line in open(path):
        line = line.strip()
        if line:
            try:
                out.append(json.loads(line))
            except Exception:
                pass
    return out


def reason_of(r):
    if r.get("unsupported"):
        return "UNSUPPORTED: " + r["unsupported"]
    if r.get("error"):
        return "ERROR: " + str(r["error"])
    for b in r.get("buses", []):
        if b.get("state") != "Routed":
            return f"{b.get('state')}: {(b.get('reason') or '')}"
    sim = r.get("sim")
    if isinstance(sim, dict) and not sim.get("pass", True):
        return (f"SIM FAIL: {sim.get('failures')} of {sim.get('checks')} checks"
                + (f" — {sim.get('error')}" if sim.get("error") else ""))
    if not r.get("drc_lvs_clean", True):
        return "DRC/LVS dirty"
    return ""


def short(s, n=150):
    s = " ".join(str(s).split())
    return s[:n] + ("…" if len(s) > n else "")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dir", default=HERE)
    ap.add_argument("--out", default=os.path.join(HERE, "REPORT.md"))
    a = ap.parse_args()
    D = a.dir
    results = [r for r in load(os.path.join(D, "results.jsonl"))
               if ".var_" not in r.get("id", "")]
    variants = load(os.path.join(D, "variants.jsonl"))
    final = os.path.join(D, "critiques_final.jsonl")
    crit = load(final if os.path.exists(final) else os.path.join(D, "critiques.jsonl"))
    log = load(os.path.join(D, "codex_log.jsonl"))
    prune = load(os.path.join(D, "prune.jsonl"))
    walls = load(os.path.join(D, "unsolved_probes.jsonl"))
    by_id = {r["id"]: r for r in results}

    L = []
    W = L.append
    W("# ADVERSARIAL PROCEDURAL ROUTING AUDIT")
    W("")
    W("Generated by this directory's own loop: `gen_problems.py` invents the "
      "problems, `run_ladder.py` makes the Rust bus router solve them and proves "
      "each solution in the vanilla-accurate engine, `verify.py` tries to beat "
      "the solution using only the solver's own knobs, and `critic.py` asks "
      "codex (gpt-5.6-sol) to find something better — with every claim it makes "
      "mechanically checked before it counts.")
    W("")
    W("```")
    W("python3 gen_problems.py --out problems --mode both --per-tier 6 --seed 20260810")
    W("python3 run_ladder.py  --problems problems --out results.jsonl --work-dir work")
    W("python3 verify.py      --results results.jsonl --out variants.jsonl")
    W("python3 critic.py      --results results.jsonl --out critiques.jsonl \\")
    W("                       --log codex_log.jsonl --max-calls 60")
    W("python3 make_report.py")
    W("```")
    W("")

    # ---------------- ladder ----------------
    W("## 1. The difficulty ladder (compound tiers)")
    W("")
    W("| tier | solved | first failure |")
    W("|---|---|---|")
    lad = collections.defaultdict(list)
    for r in results:
        if r.get("tier"):
            lad[r["tier"]].append(r)
    for t in sorted(lad):
        rs = lad[t]
        ok = sum(1 for r in rs if r.get("solved"))
        bad = next((reason_of(r) for r in rs if not r.get("solved")), "—")
        W(f"| T{t} | {ok}/{len(rs)} | {short(bad, 190)} |")
    W("")
    first_break = next((t for t in sorted(lad)
                        if any(not r.get("solved") for r in lad[t])), None)
    total_break = next((t for t in sorted(lad)
                        if all(not r.get("solved") for r in lad[t])), None)
    W(f"**The solver first breaks at tier {first_break} and fails completely at "
      f"tier {total_break}.**")
    W("")
    W("Tier composition is documented in `gen_problems.py` (TIERS): T1 near-trivial, "
      "T2 gentle, T3 form change, T4 obstructed, T5 congested, T6 permuted+maze, "
      "T7 irregular, T8 hex carrier.")
    W("")

    # ---------------- per-axis capability table ----------------
    W("## 2. Which capability breaks, and where (per-axis probes)")
    W("")
    W("A compound tier cannot tell you which axis failed — the first wall masks "
      "everything behind it. These runs vary ONE axis and hold the rest at an "
      "easy baseline (8-bit vert->vert, span 32, no obstacles, one bus).")
    W("")
    W("| axis | levels probed | highest level SOLVED | first failing level | why it failed |")
    W("|---|---|---|---|---|")
    probes = collections.defaultdict(list)
    for r in results:
        ax = r.get("axes") or {}
        pid = r.get("id", "")
        if pid.startswith("p_"):
            axis = pid[2:].rsplit("_", 1)[0]
            lvl = int(pid.rsplit("_", 1)[1])
            probes[axis].append((lvl, r))
    axis_values = {}
    try:
        import gen_problems
        axis_values = {k: v for k, v in gen_problems.PROBES.items()}
    except Exception:
        pass
    for axis in sorted(probes):
        rs = sorted(probes[axis])
        ok = [lv for lv, r in rs if r.get("solved")]
        bad = [(lv, r) for lv, r in rs if not r.get("solved")]
        vals = axis_values.get(axis, [])

        def label(lv):
            if lv < len(vals):
                d = vals[lv]
                return ",".join(f"{k}={v}" for k, v in d.items())
            return f"level {lv}"
        hi = label(max(ok)) if ok else "none"
        fl = label(bad[0][0]) if bad else "—"
        why = short(reason_of(bad[0][1]), 170) if bad else "—"
        W(f"| {axis} | {len(rs)} | {hi} | {fl} | {why} |")
    W("")

    # ---------------- correctness findings ----------------
    W("## 3. Correctness findings (a routed, DRC-clean solution that does not work)")
    W("")
    simfail = [r for r in results
               if r.get("routed") and r.get("drc_lvs_clean")
               and isinstance(r.get("sim"), dict) and not r["sim"].get("pass", True)]
    if not simfail:
        W("None in this run: every solution the router called `Routed` and DRC/LVS "
          "clean also delivered every word in simulation.")
    else:
        W("These are the highest-severity findings in the report: the router "
          "reported success and the static checks agreed, but the words do not "
          "arrive. Each was proved with many vectors (walking ones, all-on, "
          "alternating pairs, seeded random) plus a crosstalk phase — a single "
          "quiet value would have passed.")
        W("")
        W("| problem | family | checks | failures | first failure |")
        W("|---|---|---|---|---|")
        for r in simfail:
            s = r["sim"]
            f0 = (s.get("sample_failures") or [{}])[0]
            W(f"| `{r['id']}` | {r.get('family')} | {s.get('checks')} | "
              f"{s.get('failures')} | {short(json.dumps(f0), 160)} |")
    W("")

    # ---------------- demolition evidence ----------------
    pacc = [p for p in prune if p.get("verdict") == "ACCEPTED"]
    prej = [p for p in prune if p.get("verdict") == "REJECTED"]
    W("## 3b. Demolition evidence: how much of the refresh is load-bearing?")
    W("")
    if prune:
        rem = sum(p["removed"] for p in pacc)
        tot = sum(p["repeaters"] for p in pacc)
        W("`prune_check.py` takes the router's own exported schematic, deletes "
          "repeaters until each lane's refresh pitch is >= 15 (dust reaches 15 "
          "cells), and re-runs every vector through mc-tick over an INDEPENDENT "
          "Python path (`rs.py` conventions: lever toggling, lamp reads). The "
          "baseline is proved first, so a failure cannot be blamed on the "
          "harness.")
        W("")
        W(f"* **{len(pacc)} problems: the wider pitch still delivers every word** — "
          f"{rem} of {tot} repeaters ({100*rem/max(1,tot):.0f}%) were provably "
          f"redundant.")
        W(f"* **{len(prej)} problems: the dense pitch is load-bearing** — widening "
          f"it breaks most vectors. These are the interesting ones: "
          f"{', '.join(sorted(p['id'] for p in prej))}.")
        na = [p for p in prune if p.get("verdict") in ("N/A", "SKIPPED", "VOID", "ERROR")]
        W(f"* {len(na)} skipped or not applicable (multi-bus/fanout banks cannot be "
          f"attributed by scanning, or the pitch was already >= 15).")
        W("")
        W("So the refresh policy is not simply wrong — it is *unconditional*. On "
          "straight and lightly-obstructed runs it is roughly twice as dense as "
          "the physics needs; on form conversions and level shifts the density is "
          "exactly what keeps the word alive. That is a per-segment decision the "
          "router currently does not make.")
        W("")
        W("| problem | repeaters | removed | kept | verdict |")
        W("|---|---|---|---|---|")
        for p in sorted(prune, key=lambda p: -(p.get("removed") or 0))[:12]:
            if p.get("verdict") in ("SKIPPED", "N/A"):
                continue
            W(f"| `{p['id']}` | {p.get('repeaters')} | {p.get('removed')} | "
              f"{p.get('kept')} | {p['verdict']} |")
    else:
        W("(no prune runs in this directory)")
    W("")

    # ---------------- walls attacked ----------------
    W("## 3c. Attacking the walls: impossible, or a planner gap?")
    W("")
    if walls:
        W("For a refusal there is no solution to criticise, so the only useful "
          "question is whether the problem was solvable at all. "
          "`probe_unsolved.py` gives codex the refusal reason plus an ASCII map of "
          "the obstacle field and asks for gate waypoints, then runs the solver "
          "again with exactly those waypoints.")
        W("")
        W("| problem | wall | codex says | candidates | outcome |")
        W("|---|---|---|---|---|")
        for w in walls:
            if w.get("codex_error"):
                W(f"| `{w['id']}` | {w.get('wall')} | — | — | codex reply "
                  f"unparseable ({w['codex_error']}) |")
                continue
            cands = w.get("candidates") or []
            routed = sum(1 for c in cands if c.get("routed"))
            ver = sum(1 for c in cands if c.get("solved_and_verified"))
            W(f"| `{w['id']}` | {w.get('wall')} | {w.get('assessment')} | "
              f"{len(cands)} ({routed} routed, {ver} verified) | {w.get('verdict')} |")
        W("")
        gap = [w for w in walls if (w.get("candidates") and
                                    any(c.get("routed") for c in w["candidates"]))]
        if gap:
            W("The important row is any wall where a candidate **routed**: the "
              "corridor existed and one caller-supplied waypoint found it, so the "
              "refusal was a planner gap, not an impossibility. Where such a route "
              "then failed sim or LVS, that is a second finding on top of the "
              "first — the staged route is reachable but not safe, which is "
              "exactly the crosstalk problem in section 3.")
    else:
        W("(no wall probes in this directory)")
    W("")

    # ---------------- ranked improvements ----------------
    W("## 4. RANKED solver-improvement list (accepted critiques + verified beats)")
    W("")
    W("Ranking: correctness first, then unroutable-but-constructible, then cost "
      "waste — and within a class, by how many problems share the finding and how "
      "big the win is. `source` says whether a human-free variant sweep found it "
      "or codex proposed it and the verifier confirmed it.")
    W("")
    items = []

    # 4a: sim failures are improvement #1 by construction
    for r in simfail:
        items.append({
            "class": 0, "n": 1,
            "title": f"`{r['id']}`: routed + DRC-clean but WRONG in sim",
            "detail": (f"{r['sim'].get('failures')} of {r['sim'].get('checks')} "
                       f"vector checks fail. family {r.get('family')}. "
                       f"Static checks cannot see this; only the engine can."),
            "source": "sim",
        })

    # 4a2: the demolition finding
    if pacc:
        rem = sum(p["removed"] for p in pacc)
        tot = sum(p["repeaters"] for p in pacc)
        items.append({
            "class": 1, "n": len(pacc),
            "title": "the repeater refresh pitch is unconditional, and about twice "
                     "as dense as the physics needs on simple runs",
            "detail": (f"{rem} of {tot} repeaters ({100*rem/max(1,tot):.0f}%) deleted "
                       f"across {len(pacc)} problems with every vector still arriving "
                       f"in mc-tick; but on {len(prej)} form-conversion / level-shift "
                       f"problems the same widening breaks the word. Make the refresh "
                       f"decision per segment from the strength budget instead of a "
                       f"fixed pitch — it buys cells AND halves delay where it is "
                       f"safe, and it must stay dense where it is not."),
            "source": "prune-construction (mc-tick)",
        })

    # 4a3: walls that turned out to be planner gaps
    routed_walls = [w for w in walls
                    if any(c.get("routed") for c in (w.get("candidates") or []))]
    if routed_walls:
        items.append({
            "class": 1, "n": len(routed_walls),
            "title": "a refusal that a single caller-supplied waypoint turns into a "
                     "route: the planner does not stage its own detours",
            "detail": ("; ".join(f"`{w['id']}` ({w.get('wall')})" for w in routed_walls)
                       + ". The router's own failure text even names the clear level "
                         "and suggests a gate — so the information needed to stage the "
                         "detour is already computed, it is just handed to the user "
                         "instead of being used."),
            "source": "codex construction, executed",
        })

    # 4b: variant sweep beats (grouped by winning label family)
    beat = collections.defaultdict(list)
    for v in variants:
        for b in v["sweep"]["better"]:
            beat[b["label"].split("_")[0]].append((v["id"], b))
    for grp, lst in sorted(beat.items(), key=lambda kv: -len(kv[1])):
        best = min(lst, key=lambda t: t[1]["delta_total"])
        items.append({
            "class": 2, "n": len(lst),
            "title": f"the default plan is beaten by a `{grp}*` variant on "
                     f"{len(set(i for i, _ in lst))} problem(s)",
            "detail": (f"best case `{best[0]}` improves the weighted cost by "
                       f"{best[1]['delta_total']} ({best[1]['label']}), sim PASS and "
                       f"DRC clean. The knob is already public API, so the router "
                       f"could try it itself instead of taking the first plan that "
                       f"fits."),
            "source": "variant-sweep",
        })

    # 4c: accepted codex claims
    acc = collections.defaultdict(list)
    for c in crit:
        for v in c.get("verdicts", []):
            if v["verdict"] == "ACCEPTED":
                acc[v["claim"].get("kind", "?")].append((c, v))
    for kind, lst in sorted(acc.items(), key=lambda kv: -len(kv[1])):
        ids = sorted(set(c["id"] for c, _ in lst))
        ex = lst[0]
        items.append({
            "class": 2, "n": len(lst),
            "title": f"codex critique on `{kind}` upheld for {len(ids)} problem(s)",
            "detail": (f"e.g. {ex[0]['id']}: {short(ex[1]['claim'].get('argument'), 180)} "
                       f"— verifier: {short(ex[1]['why'], 200)}"),
            "source": "codex+verified",
        })

    # 4d: capability walls become feature requests
    walls = collections.defaultdict(list)
    for r in results:
        if r.get("solved"):
            continue
        why = reason_of(r)
        key = None
        low = why.lower()
        if "no encoding knob" in low:
            key = "no analog/hex carrier on the design surface"
        elif "unsupported bus form" in low:
            key = "unsupported bus form (pitch != 2 / negative step / flat-along-travel)"
        elif "level-shift tile" in low:
            key = "level-shift tile placement gives up instead of detouring"
        elif "no corridor" in low:
            key = "no corridor: the planner will not leave its level/lane to get past an obstacle"
        elif "walled in" in low or "endpoint approach" in low:
            key = "endpoint approach: no alternative approach face is tried"
        elif "no trunk run aligns" in low:
            key = "fanout: a branch sink needs a perpendicular shot into the trunk"
        elif "timeout" in low:
            key = "solve time blows up (timeout)"
        if key:
            walls[key].append(r["id"])
    for key, ids in sorted(walls.items(), key=lambda kv: -len(kv[1])):
        items.append({
            "class": 1, "n": len(ids),
            "title": key,
            "detail": f"{len(ids)} problem(s): {', '.join(sorted(ids)[:8])}"
                      + (" …" if len(ids) > 8 else ""),
            "source": "ladder+probes",
        })

    items.sort(key=lambda i: (i["class"], -i["n"]))
    for rank, it in enumerate(items, 1):
        W(f"{rank}. **{it['title']}** — _{it['source']}_, {it['n']} hit(s).  ")
        W(f"   {it['detail']}")
    W("")

    # ---------------- critique accounting ----------------
    W("## 5. Critique accounting — accepted / rejected / unverified")
    W("")
    tally = collections.Counter()
    per_effort = collections.defaultdict(collections.Counter)
    for c in crit:
        e = c.get("effort", "?")
        if c.get("codex_error"):
            per_effort[e]["failed_calls"] += 1
            continue
        per_effort[e]["calls"] += 1
        if not c.get("verdicts"):
            per_effort[e]["no_claims"] += 1
        for v in c.get("verdicts", []):
            tally[v["verdict"]] += 1
            per_effort[e][v["verdict"]] += 1
    W(f"* ACCEPTED (reproduced and better / measured true): **{tally['ACCEPTED']}**")
    W(f"* REJECTED (checked, wrong): **{tally['REJECTED']}**")
    W(f"* UNVERIFIED (plausible, not constructible by us): **{tally['UNVERIFIED']}**")
    W("")
    W("### effort vs value — does a smarter critic pay?")
    W("")
    W("| effort | calls | replies with NO claims | claims | ACCEPTED | REJECTED | "
      "UNVERIFIED | tokens | accepted/call |")
    W("|---|---|---|---|---|---|---|---|---|")
    tok_by_effort = collections.Counter()
    for e in log:
        tok_by_effort[e.get("effort", "?")] += (e.get("tokens") or 0)
    for e in ["low", "medium", "high", "xhigh"]:
        c = per_effort.get(e)
        if not c:
            continue
        claims = c["ACCEPTED"] + c["REJECTED"] + c["UNVERIFIED"]
        calls = c["calls"] or 1
        W(f"| {e} | {c['calls']} | {c['no_claims']} | {claims} | {c['ACCEPTED']} | "
          f"{c['REJECTED']} | {c['UNVERIFIED']} | {tok_by_effort[e]:,} | "
          f"{c['ACCEPTED']/calls:.2f} |")
    W("")
    lo, me, hi = (per_effort.get(x, collections.Counter()) for x in
                  ("low", "medium", "high"))
    W(f"Read the `replies with NO claims` column before the `accepted/call` column. "
      f"At high effort {hi['no_claims']} of {hi['calls']} replies contained no "
      f"checkable claim at all (two of them answered with a bare verdict word that "
      f"is not even in the schema), so the high row's ratio rests on very few "
      f"replies. Cost per usable claim runs the other way: "
      f"{tok_by_effort['low']//max(1,lo['ACCEPTED']+lo['REJECTED']+lo['UNVERIFIED']):,} "
      f"tokens per claim at low vs "
      f"{tok_by_effort['high']//max(1,hi['ACCEPTED']+hi['REJECTED']+hi['UNVERIFIED']):,} "
      f"at high.")
    W("")
    W("**Verdict on the tiering: low effort was the right default.** It produced "
      "the most claims per token, it produced the single most valuable idea in "
      "this whole report (the refresh-pitch critique, from the very first low-effort "
      "call), and the medium pass — run only where low found nothing — did not "
      "rescue those problems: it mostly re-stated them. High effort did not find a "
      "class of problem the cheap pass had missed; it mostly wrote less.")
    W("")

    # ---------------- codex cost ----------------
    W("## 6. Codex cost log")
    W("")
    tot_tok = sum(e.get("tokens") or 0 for e in log)
    ok_calls = sum(1 for e in log if e.get("ok"))
    W(f"* calls: **{len(log)}** ({ok_calls} usable, {len(log)-ok_calls} failed or "
      f"unparseable)")
    W(f"* tokens: **{tot_tok:,}** total")
    W(f"* wall clock in codex: **{sum(e.get('wall_s') or 0 for e in log)/60:.1f} min**")
    W("")
    W("| effort | calls | tokens | mean tokens | mean wall s |")
    W("|---|---|---|---|---|")
    for e in ["low", "medium", "high", "xhigh"]:
        rows = [x for x in log if x.get("effort") == e]
        if not rows:
            continue
        tk = sum(x.get("tokens") or 0 for x in rows)
        W(f"| {e} | {len(rows)} | {tk:,} | {tk//max(1,len(rows)):,} | "
          f"{sum(x.get('wall_s') or 0 for x in rows)/len(rows):.0f} |")
    W("")
    W("The `high` row includes the wall-probe calls of section 3c as well as the "
      "critique pass, which is why it carries more calls than the table above.")
    W("")

    # ---------------- honest assessment ----------------
    W("## 7. Was codex actually useful as a critic? — measured, not assumed")
    W("")
    acc_all = [v for c in crit for v in (c.get("verdicts") or [])
               if v["verdict"] == "ACCEPTED"]
    by_prune = [v for v in acc_all if "demolition" in (v.get("why") or "")]
    by_variant = [v for v in acc_all if "variant" in (v.get("why") or "")]
    W(f"* {len(log)} calls, {sum(1 for x in log if x.get('ok'))} usable replies, "
      f"{sum(e.get('tokens') or 0 for e in log):,} tokens.")
    other = len(acc_all) - len(by_variant) - len(by_prune)
    W(f"* {len(acc_all)} claims survived verification. Of those, **{len(by_variant)} "
      f"were things the codex-free variant sweep had already found by itself** — "
      f"codex agreed with a machine that costs nothing to run"
      + (f", and {other} were plain measurements of the existing route." if other
         else "."))
    W(f"* **{len(by_prune)} rest on the ONE idea the sweep could not reach**: that "
      f"the refresh pitch is unconditional. That idea came from the very first "
      f"low-effort call, it required building a whole new verifier "
      f"(`prune_check.py`) to test, and it turned out to be right on simple runs "
      f"and wrong on form conversions — a distinction worth more than the original "
      f"claim.")
    W(f"* {tally['UNVERIFIED']} claims could not be checked at all, mostly because "
      f"the solver exposes no knob for what codex proposed. That is the honest "
      f"ceiling of this design: a critic can only be graded on the axes the system "
      f"under test lets you actuate.")
    W("")
    W("So: **useful, but not in the way the design assumed.** It did not act as a "
      "better router — none of its geometric counter-proposals for a specific route "
      "beat the solver when executed. It acted as a POLICY reviewer: it noticed a "
      "standing rule that was too conservative, which no amount of per-problem "
      "search would have surfaced, because every variant in the search inherits "
      "that same rule. If this loop is kept, spend the budget on breadth at low "
      "effort and invest the saved tokens in more verifier CHANNELS (things like "
      "`prune_check.py`), because the verifier's reach — not the critic's "
      "intelligence — was the binding constraint throughout.")
    W("")
    # ---------------- the actionable pointer ----------------
    W("## 8. Appendix: exactly where finding #3 lives")
    W("")
    W("The refresh policy is one constant:")
    W("")
    W("```")
    W("src/design.rs:131          const REFRESH_AT: u32 = 7;")
    W("src/design_promote.rs:99   const REFRESH_AT: usize = 6;")
    W("```")
    W("")
    W("Seven dust cells between refreshes is a repeater every ~8 cells, which is "
      "what the fragments measure. Dust carries 15. The measurements in section 3b "
      "say the margin is real but *unconditionally* spent:")
    W("")
    W("* on straight and lightly-obstructed runs, deleting every repeater closer "
      "than 15 to its neighbour still delivers every word — so the cost and half "
      "the delay are being paid for nothing;")
    W("* on form conversions and level shifts the same widening breaks the word, "
      "because turns, steps and dips spend strength that a flat cell does not.")
    W("")
    W("So the fix is not \"raise the constant\": it is to make the refresh decision "
      "from the strength actually spent along the segment being emitted, with the "
      "conservative value kept as the fallback for segment kinds whose budget is "
      "not modelled. Anyone doing that work has a ready-made regression set — these "
      "problems MUST stay dense, because widening them is empirically fatal:")
    W("")
    if prej:
        for p in sorted(prej, key=lambda p: p["id"]):
            spec_id = p["id"]
            rec = by_id.get(spec_id, {})
            W(f"* `{spec_id}` ({rec.get('family', '?')}) — pruning to pitch 15 breaks "
              f"{p.get('pruned_failures')} of {p.get('baseline_vectors')} vectors.")
    W("")
    W("and these are the ones where the saving is largest:")
    W("")
    for p in sorted(pacc, key=lambda p: -(p.get("removed") or 0))[:5]:
        W(f"* `{p['id']}` — {p['removed']} of {p['repeaters']} repeaters removable "
          f"({p['kept']} kept), all {p.get('baseline_vectors')} vectors still arrive.")
    W("")
    W("Reproduce either direction with:")
    W("")
    W("```")
    W("python3 prune_check.py --results results.jsonl --out prune.jsonl --pitch 15 \\")
    W("    --ids <problem id>")
    W("```")
    W("")
    W("Per-call detail is in `codex_log.jsonl`; every critique with its verdicts "
      "is in `critiques_final.jsonl` (`critiques.jsonl` holds the pre-demolition "
      "verdicts); every solve/sim run is in `results.jsonl`; every variant sweep "
      "is in `variants.jsonl`; every demolition test is in `prune.jsonl`; the wall "
      "constructions are in `unsolved_probes.jsonl`.")
    W("")

    with open(a.out, "w") as f:
        f.write("\n".join(L) + "\n")
    print(f"wrote {a.out} ({len(L)} lines)")


if __name__ == "__main__":
    main()
