// generated by diplomat-tool
import { NucleationError } from "./NucleationError.mjs"
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";

const Blocks_box_destroy_registry = new FinalizationRegistry((ptr) => {
    wasm.Blocks_destroy(ptr);
});

/**
 * Namespace for read-only queries over the built-in block table
 * (Java 26.2 blocks + official semantics extracted from the vanilla
 * jars: definition kinds, base-block links, block tags, model
 * geometry). All list results are JSON array strings sorted by id;
 * block/tag/kind arguments accept both `minecraft:`-prefixed and
 * short forms (`minecraft:oak_stairs` / `oak_stairs`).
 */
export class Blocks {
    // Internal ptr reference:
    #ptr = null;

    // Lifetimes are only to keep dependencies alive.
    // Since JS won't garbage collect until there are no incoming edges.
    #selfEdge = [];

    #internalConstructor(symbol, ptr, selfEdge) {
        if (symbol !== diplomatRuntime.internalConstructor) {
            console.error("Blocks is an Opaque type. You cannot call its constructor.");
            return;
        }
        this.#ptr = ptr;
        this.#selfEdge = selfEdge;

        // Are we being borrowed? If not, we can register.
        if (this.#selfEdge.length === 0) {
            Blocks_box_destroy_registry.register(this, this.#ptr);
        }

        return this;
    }
    /** @internal */
    get ffiValue() {
        return this.#ptr;
    }


    /**
     * Full facts for one block as a JSON object:
     * `{id, kind, base_block, tags: [...], full_cube, transparent,
     * color: [r, g, b] | null, properties: {name: [values...]},
     * default_state: {name: value}}`. `kind` is the official
     * definition kind (`minecraft:stair`, plain full blocks are
     * `minecraft:block`); `base_block` is the block this one is a
     * shape variant of (or `null`); `color` is the texture-derived
     * average RGB. Errors with `NotFound` for unknown ids.
     */
    static getJson(id) {
        let functionCleanupArena = new diplomatRuntime.CleanupArena();

        const idSlice = functionCleanupArena.alloc(diplomatRuntime.DiplomatBuf.sliceWrapper(wasm, diplomatRuntime.DiplomatBuf.str8(wasm, id)));
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);

        const write = new diplomatRuntime.DiplomatWriteBuf(wasm);


        const result = wasm.Blocks_get_json(diplomatReceive.buffer, idSlice.ptr, write.buffer);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new NucleationError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('NucleationError.' + cause.value, { cause });
            }
            return write.readString8();
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            functionCleanupArena.free();

            diplomatReceive.free();
            write.free();
        }
    }

    /**
     * All known block ids as a sorted JSON array string.
     */
    static idsJson() {
        const write = new diplomatRuntime.DiplomatWriteBuf(wasm);

    wasm.Blocks_ids_json(write.buffer);

        try {
            return write.readString8();
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            write.free();
        }
    }

    /**
     * Ids of every block carrying the vanilla block tag, as a sorted
     * JSON array string (`[]` for unknown tags). Accepts
     * `minecraft:wool` and short `wool` forms, including nested paths
     * like `mineable/pickaxe`.
     */
    static byTagJson(tag) {
        let functionCleanupArena = new diplomatRuntime.CleanupArena();

        const tagSlice = functionCleanupArena.alloc(diplomatRuntime.DiplomatBuf.sliceWrapper(wasm, diplomatRuntime.DiplomatBuf.str8(wasm, tag)));
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);

        const write = new diplomatRuntime.DiplomatWriteBuf(wasm);


        const result = wasm.Blocks_by_tag_json(diplomatReceive.buffer, tagSlice.ptr, write.buffer);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new NucleationError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('NucleationError.' + cause.value, { cause });
            }
            return write.readString8();
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            functionCleanupArena.free();

            diplomatReceive.free();
            write.free();
        }
    }

    /**
     * Ids of every block of the given official definition kind
     * (`minecraft:stair`, `minecraft:slab`, `minecraft:door`, ...), as
     * a sorted JSON array string (`[]` for unknown kinds).
     */
    static byKindJson(kind) {
        let functionCleanupArena = new diplomatRuntime.CleanupArena();

        const kindSlice = functionCleanupArena.alloc(diplomatRuntime.DiplomatBuf.sliceWrapper(wasm, diplomatRuntime.DiplomatBuf.str8(wasm, kind)));
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);

        const write = new diplomatRuntime.DiplomatWriteBuf(wasm);


        const result = wasm.Blocks_by_kind_json(diplomatReceive.buffer, kindSlice.ptr, write.buffer);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new NucleationError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('NucleationError.' + cause.value, { cause });
            }
            return write.readString8();
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            functionCleanupArena.free();

            diplomatReceive.free();
            write.free();
        }
    }

    /**
     * The base block followed by all its shape variants — blocks whose
     * `base_block` is `base_id` (stairs, slabs, walls, fences of the
     * base) — as a JSON array string. The base itself is always first;
     * variants follow sorted by id. Errors with `NotFound` for unknown
     * base ids.
     */
    static variantsOfJson(baseId) {
        let functionCleanupArena = new diplomatRuntime.CleanupArena();

        const baseIdSlice = functionCleanupArena.alloc(diplomatRuntime.DiplomatBuf.sliceWrapper(wasm, diplomatRuntime.DiplomatBuf.str8(wasm, baseId)));
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);

        const write = new diplomatRuntime.DiplomatWriteBuf(wasm);


        const result = wasm.Blocks_variants_of_json(diplomatReceive.buffer, baseIdSlice.ptr, write.buffer);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new NucleationError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('NucleationError.' + cause.value, { cause });
            }
            return write.readString8();
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            functionCleanupArena.free();

            diplomatReceive.free();
            write.free();
        }
    }

    /**
     * All known vanilla block tag names as a sorted JSON array string
     * (`minecraft:`-prefixed, e.g. `minecraft:wool`).
     */
    static tagsJson() {
        const write = new diplomatRuntime.DiplomatWriteBuf(wasm);

    wasm.Blocks_tags_json(write.buffer);

        try {
            return write.readString8();
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            write.free();
        }
    }

    /**
     * Every property-value combination of the block as a JSON array of
     * `{prop: value}` objects (a single `{}` entry for property-less
     * blocks). Errors with `NotFound` for unknown ids and with
     * `InvalidArgument` if the combination count exceeds 4096 (guard
     * against pathological output; the current data tops out at 1350
     * for `minecraft:note_block`).
     */
    static statesJson(id) {
        let functionCleanupArena = new diplomatRuntime.CleanupArena();

        const idSlice = functionCleanupArena.alloc(diplomatRuntime.DiplomatBuf.sliceWrapper(wasm, diplomatRuntime.DiplomatBuf.str8(wasm, id)));
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);

        const write = new diplomatRuntime.DiplomatWriteBuf(wasm);


        const result = wasm.Blocks_states_json(diplomatReceive.buffer, idSlice.ptr, write.buffer);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new NucleationError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('NucleationError.' + cause.value, { cause });
            }
            return write.readString8();
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            functionCleanupArena.free();

            diplomatReceive.free();
            write.free();
        }
    }

    /**
     * Total number of blocks in the table.
     */
    static count() {

        const result = wasm.Blocks_count();

        try {
            return result;
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    constructor(symbol, ptr, selfEdge) {
        return this.#internalConstructor(...arguments)
    }
}