// generated by diplomat-tool
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";

export type BlockPos_obj = {
    x: number;
    y: number;
    z: number;
};



export class BlockPos {
    get x(): number;
    set x(value: number);
    get y(): number;
    set y(value: number);
    get z(): number;
    set z(value: number);
    /** @internal */
    static fromFields(structObj : BlockPos_obj) : BlockPos;

    /**
    * Create `BlockPos` from an object that contains all of `BlockPos`s fields.
    * Optional fields do not need to be included in the provided object.
    */
    constructor(structObj: BlockPos_obj);

}