// generated by diplomat-tool
import { InterpolationSpace } from "./InterpolationSpace.mjs"
import { NucleationError } from "./NucleationError.mjs"
import { Palette } from "./Palette.mjs"
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";

const Brush_box_destroy_registry = new FinalizationRegistry((ptr) => {
    wasm.Brush_destroy(ptr);
});

/**
 * Decides which block goes at each point of a filled shape. Wraps `BrushEnum`.
 */
export class Brush {
    // Internal ptr reference:
    #ptr = null;

    // Lifetimes are only to keep dependencies alive.
    // Since JS won't garbage collect until there are no incoming edges.
    #selfEdge = [];

    #internalConstructor(symbol, ptr, selfEdge) {
        if (symbol !== diplomatRuntime.internalConstructor) {
            console.error("Brush is an Opaque type. You cannot call its constructor.");
            return;
        }
        this.#ptr = ptr;
        this.#selfEdge = selfEdge;

        // Are we being borrowed? If not, we can register.
        if (this.#selfEdge.length === 0) {
            Brush_box_destroy_registry.register(this, this.#ptr);
        }

        return this;
    }
    /** @internal */
    get ffiValue() {
        return this.#ptr;
    }


    /**
     * Every point becomes `block_name` (a block-state string).
     */
    static solid(blockName) {
        let functionCleanupArena = new diplomatRuntime.CleanupArena();

        const blockNameSlice = functionCleanupArena.alloc(diplomatRuntime.DiplomatBuf.sliceWrapper(wasm, diplomatRuntime.DiplomatBuf.str8(wasm, blockName)));
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);


        const result = wasm.Brush_solid(diplomatReceive.buffer, blockNameSlice.ptr);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new NucleationError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('NucleationError.' + cause.value, { cause });
            }
            return new Brush(diplomatRuntime.internalConstructor, diplomatRuntime.ptrRead(wasm, diplomatReceive.buffer), []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            functionCleanupArena.free();

            diplomatReceive.free();
        }
    }

    /**
     * Nearest-block-to-RGB-color brush.
     */
    static color(r, g, b) {

        const result = wasm.Brush_color(r, g, b);

        try {
            return new Brush(diplomatRuntime.internalConstructor, result, []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    /**
     * Linear color gradient between two anchored points.
     */
    static linearGradient(x1, y1, z1, r1, g1, b1, x2, y2, z2, r2, g2, b2, space) {

        const result = wasm.Brush_linear_gradient(x1, y1, z1, r1, g1, b1, x2, y2, z2, r2, g2, b2, space.ffiValue);

        try {
            return new Brush(diplomatRuntime.internalConstructor, result, []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    /**
     * Base color shaded by surface normal against light direction
     * (`lx`, `ly`, `lz`).
     */
    static shaded(r, g, b, lx, ly, lz) {

        const result = wasm.Brush_shaded(r, g, b, lx, ly, lz);

        try {
            return new Brush(diplomatRuntime.internalConstructor, result, []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    /**
     * Bilinear gradient over the patch `origin + s*u + t*v` with corner colors
     * c00/c10/c01/c11.
     */
    static bilinearGradient(ox, oy, oz, ux, uy, uz, vx, vy, vz, r00, g00, b00, r10, g10, b10, r01, g01, b01, r11, g11, b11, space) {

        const result = wasm.Brush_bilinear_gradient(ox, oy, oz, ux, uy, uz, vx, vy, vz, r00, g00, b00, r10, g10, b10, r01, g01, b01, r11, g11, b11, space.ffiValue);

        try {
            return new Brush(diplomatRuntime.internalConstructor, result, []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    /**
     * Inverse-distance-weighted gradient between colored anchor points.
     * `positions` is flat `[x0, y0, z0, x1, …]` and `colors` is flat
     * `[r0, g0, b0, r1, …]`; both must describe the same non-zero number of
     * points (`positions.len() == colors.len()`, a multiple of 3).
     */
    static pointGradient(positions, colors, falloff, space) {
        let functionCleanupArena = new diplomatRuntime.CleanupArena();

        const positionsSlice = functionCleanupArena.alloc(diplomatRuntime.DiplomatBuf.sliceWrapper(wasm, diplomatRuntime.DiplomatBuf.slice(wasm, positions, "i32")));
        const colorsSlice = functionCleanupArena.alloc(diplomatRuntime.DiplomatBuf.sliceWrapper(wasm, diplomatRuntime.DiplomatBuf.slice(wasm, colors, "u8")));
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);


        const result = wasm.Brush_point_gradient(diplomatReceive.buffer, positionsSlice.ptr, colorsSlice.ptr, falloff, space.ffiValue);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new NucleationError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('NucleationError.' + cause.value, { cause });
            }
            return new Brush(diplomatRuntime.internalConstructor, diplomatRuntime.ptrRead(wasm, diplomatReceive.buffer), []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            functionCleanupArena.free();

            diplomatReceive.free();
        }
    }

    /**
     * Spotlight-lit base color (`r`, `g`, `b`): Lambert shading toward a
     * cone light at (`px`, `py`, `pz`) aimed along (`dx`, `dy`, `dz`).
     * Full intensity inside 0.7 × `cone_angle_deg`, smoothstep falloff
     * to zero at the cone edge; surfaces facing away or outside the cone
     * drop to a 4% ambient floor.
     */
    static spotlight(px, py, pz, dx, dy, dz, coneAngleDeg, r, g, b) {

        const result = wasm.Brush_spotlight(px, py, pz, dx, dy, dz, coneAngleDeg, r, g, b);

        try {
            return new Brush(diplomatRuntime.internalConstructor, result, []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    /**
     * Use `palette` for this brush's color→block snapping instead of the
     * default all-blocks palette. No-op for `solid` brushes, which place
     * a fixed block state. Set it before filling; the palette is shared,
     * not copied.
     */
    setPalette(palette) {
    wasm.Brush_set_palette(this.ffiValue, palette.ffiValue);

        try {}

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    /**
     * Gradient along a parametric curve: `stops` holds the curve parameters in
     * `[0, 1]` and `colors` the matching flat RGB triples
     * (`colors.len() == stops.len() * 3`, `stops` non-empty).
     */
    static curveGradient(stops, colors, space) {
        let functionCleanupArena = new diplomatRuntime.CleanupArena();

        const stopsSlice = functionCleanupArena.alloc(diplomatRuntime.DiplomatBuf.sliceWrapper(wasm, diplomatRuntime.DiplomatBuf.slice(wasm, stops, "f32")));
        const colorsSlice = functionCleanupArena.alloc(diplomatRuntime.DiplomatBuf.sliceWrapper(wasm, diplomatRuntime.DiplomatBuf.slice(wasm, colors, "u8")));
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);


        const result = wasm.Brush_curve_gradient(diplomatReceive.buffer, stopsSlice.ptr, colorsSlice.ptr, space.ffiValue);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new NucleationError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('NucleationError.' + cause.value, { cause });
            }
            return new Brush(diplomatRuntime.internalConstructor, diplomatRuntime.ptrRead(wasm, diplomatReceive.buffer), []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            functionCleanupArena.free();

            diplomatReceive.free();
        }
    }

    constructor(symbol, ptr, selfEdge) {
        return this.#internalConstructor(...arguments)
    }
}