// generated by diplomat-tool
import type { NucleationError } from "./NucleationError"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * A sampled 3D polyline. Closed curves include the final segment back to
 * the first point and retain arc-length parameterisation for animation.
 * Oversized point sets and overflowing segment lengths are rejected.
 */
export class Curve3D {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    /**
     * Create a curve from flat `[x0, y0, z0, x1, y1, z1, …]` coordinates.
     */
    static fromPoints(coordinates: Array<number>, closed: boolean): Curve3D;

    pointCount(): number;

    isClosed(): boolean;
}