// generated by diplomat-tool
import { BlockPos } from "./BlockPos.mjs"
import { Dimensions } from "./Dimensions.mjs"
import { NucleationError } from "./NucleationError.mjs"
import { RegionBounds } from "./RegionBounds.mjs"
import { Schematic } from "./Schematic.mjs"
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";

const DefinitionRegion_box_destroy_registry = new FinalizationRegistry((ptr) => {
    wasm.DefinitionRegion_destroy(ptr);
});

/**
 * A named sub-volume of a schematic: a union of boxes plus a metadata map.
 */
export class DefinitionRegion {
    // Internal ptr reference:
    #ptr = null;

    // Lifetimes are only to keep dependencies alive.
    // Since JS won't garbage collect until there are no incoming edges.
    #selfEdge = [];

    #internalConstructor(symbol, ptr, selfEdge) {
        if (symbol !== diplomatRuntime.internalConstructor) {
            console.error("DefinitionRegion is an Opaque type. You cannot call its constructor.");
            return;
        }
        this.#ptr = ptr;
        this.#selfEdge = selfEdge;

        // Are we being borrowed? If not, we can register.
        if (this.#selfEdge.length === 0) {
            DefinitionRegion_box_destroy_registry.register(this, this.#ptr);
        }

        return this;
    }
    /** @internal */
    get ffiValue() {
        return this.#ptr;
    }


    static create() {

        const result = wasm.DefinitionRegion_create();

        try {
            return new DefinitionRegion(diplomatRuntime.internalConstructor, result, []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    static fromBounds(minX, minY, minZ, maxX, maxY, maxZ) {

        const result = wasm.DefinitionRegion_from_bounds(minX, minY, minZ, maxX, maxY, maxZ);

        try {
            return new DefinitionRegion(diplomatRuntime.internalConstructor, result, []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    /**
     * Build a region from single-block positions crossing as flat `[i32]`
     * chunked in threes (PORTING rule 7). Errors with `InvalidArgument` if
     * the length is not a multiple of 3.
     */
    static fromPositions(positions) {
        let functionCleanupArena = new diplomatRuntime.CleanupArena();

        const positionsSlice = functionCleanupArena.alloc(diplomatRuntime.DiplomatBuf.sliceWrapper(wasm, diplomatRuntime.DiplomatBuf.slice(wasm, positions, "i32")));
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);


        const result = wasm.DefinitionRegion_from_positions(diplomatReceive.buffer, positionsSlice.ptr);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new NucleationError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('NucleationError.' + cause.value, { cause });
            }
            return new DefinitionRegion(diplomatRuntime.internalConstructor, diplomatRuntime.ptrRead(wasm, diplomatReceive.buffer), []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            functionCleanupArena.free();

            diplomatReceive.free();
        }
    }

    /**
     * Build a region from bounding boxes crossing as flat `[i32]` chunked in
     * sixes (`min_x, min_y, min_z, max_x, max_y, max_z` per box). Errors
     * with `InvalidArgument` if the length is not a multiple of 6.
     */
    static fromBoundingBoxes(boxes) {
        let functionCleanupArena = new diplomatRuntime.CleanupArena();

        const boxesSlice = functionCleanupArena.alloc(diplomatRuntime.DiplomatBuf.sliceWrapper(wasm, diplomatRuntime.DiplomatBuf.slice(wasm, boxes, "i32")));
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);


        const result = wasm.DefinitionRegion_from_bounding_boxes(diplomatReceive.buffer, boxesSlice.ptr);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new NucleationError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('NucleationError.' + cause.value, { cause });
            }
            return new DefinitionRegion(diplomatRuntime.internalConstructor, diplomatRuntime.ptrRead(wasm, diplomatReceive.buffer), []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            functionCleanupArena.free();

            diplomatReceive.free();
        }
    }

    addBounds(minX, minY, minZ, maxX, maxY, maxZ) {
    wasm.DefinitionRegion_add_bounds(this.ffiValue, minX, minY, minZ, maxX, maxY, maxZ);

        try {}

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    addPoint(x, y, z) {
    wasm.DefinitionRegion_add_point(this.ffiValue, x, y, z);

        try {}

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    setMetadata(key, value) {
        let functionCleanupArena = new diplomatRuntime.CleanupArena();

        const keySlice = functionCleanupArena.alloc(diplomatRuntime.DiplomatBuf.sliceWrapper(wasm, diplomatRuntime.DiplomatBuf.str8(wasm, key)));
        const valueSlice = functionCleanupArena.alloc(diplomatRuntime.DiplomatBuf.sliceWrapper(wasm, diplomatRuntime.DiplomatBuf.str8(wasm, value)));
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);


        const result = wasm.DefinitionRegion_set_metadata(diplomatReceive.buffer, this.ffiValue, keySlice.ptr, valueSlice.ptr);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new NucleationError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('NucleationError.' + cause.value, { cause });
            }
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            functionCleanupArena.free();

            diplomatReceive.free();
        }
    }

    /**
     * Errors with `NotFound` when the key is absent.
     */
    getMetadata(key) {
        let functionCleanupArena = new diplomatRuntime.CleanupArena();

        const keySlice = functionCleanupArena.alloc(diplomatRuntime.DiplomatBuf.sliceWrapper(wasm, diplomatRuntime.DiplomatBuf.str8(wasm, key)));
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);

        const write = new diplomatRuntime.DiplomatWriteBuf(wasm);


        const result = wasm.DefinitionRegion_get_metadata(diplomatReceive.buffer, this.ffiValue, keySlice.ptr, write.buffer);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new NucleationError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('NucleationError.' + cause.value, { cause });
            }
            return write.readString8();
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            functionCleanupArena.free();

            diplomatReceive.free();
            write.free();
        }
    }

    /**
     * The full metadata map, written as a JSON object string (the old ABI
     * returned an array of `"key=value"` strings).
     */
    allMetadataJson() {
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);

        const write = new diplomatRuntime.DiplomatWriteBuf(wasm);


        const result = wasm.DefinitionRegion_all_metadata_json(diplomatReceive.buffer, this.ffiValue, write.buffer);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new NucleationError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('NucleationError.' + cause.value, { cause });
            }
            return write.readString8();
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            diplomatReceive.free();
            write.free();
        }
    }

    /**
     * The metadata keys, written as a JSON array string.
     */
    metadataKeysJson() {
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);

        const write = new diplomatRuntime.DiplomatWriteBuf(wasm);


        const result = wasm.DefinitionRegion_metadata_keys_json(diplomatReceive.buffer, this.ffiValue, write.buffer);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new NucleationError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('NucleationError.' + cause.value, { cause });
            }
            return write.readString8();
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            diplomatReceive.free();
            write.free();
        }
    }

    /**
     * Store a filter expression in the region's metadata under the `filter`
     * key.
     */
    addFilter(filter) {
        let functionCleanupArena = new diplomatRuntime.CleanupArena();

        const filterSlice = functionCleanupArena.alloc(diplomatRuntime.DiplomatBuf.sliceWrapper(wasm, diplomatRuntime.DiplomatBuf.str8(wasm, filter)));
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);


        const result = wasm.DefinitionRegion_add_filter(diplomatReceive.buffer, this.ffiValue, filterSlice.ptr);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new NucleationError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('NucleationError.' + cause.value, { cause });
            }
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            functionCleanupArena.free();

            diplomatReceive.free();
        }
    }

    isEmpty() {

        const result = wasm.DefinitionRegion_is_empty(this.ffiValue);

        try {
            return result;
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    volume() {

        const result = wasm.DefinitionRegion_volume(this.ffiValue);

        try {
            return result;
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    contains(x, y, z) {

        const result = wasm.DefinitionRegion_contains(this.ffiValue, x, y, z);

        try {
            return result;
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    shift(dx, dy, dz) {
    wasm.DefinitionRegion_shift(this.ffiValue, dx, dy, dz);

        try {}

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    expand(x, y, z) {
    wasm.DefinitionRegion_expand(this.ffiValue, x, y, z);

        try {}

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    contract(amount) {
    wasm.DefinitionRegion_contract(this.ffiValue, amount);

        try {}

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    /**
     * A new region: the intersection of `self` and `other`.
     */
    intersected(other) {

        const result = wasm.DefinitionRegion_intersected(this.ffiValue, other.ffiValue);

        try {
            return new DefinitionRegion(diplomatRuntime.internalConstructor, result, []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    /**
     * A new region: the union of `self` and `other`.
     */
    unionWith(other) {

        const result = wasm.DefinitionRegion_union_with(this.ffiValue, other.ffiValue);

        try {
            return new DefinitionRegion(diplomatRuntime.internalConstructor, result, []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    /**
     * A new region: `self` minus `other`.
     */
    subtracted(other) {

        const result = wasm.DefinitionRegion_subtracted(this.ffiValue, other.ffiValue);

        try {
            return new DefinitionRegion(diplomatRuntime.internalConstructor, result, []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    /**
     * Merge `other`'s boxes and metadata into `self`.
     */
    merge(other) {
    wasm.DefinitionRegion_merge(this.ffiValue, other.ffiValue);

        try {}

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    /**
     * Union `other`'s boxes into `self` in place.
     */
    unionInto(other) {
    wasm.DefinitionRegion_union_into(this.ffiValue, other.ffiValue);

        try {}

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    /**
     * The overall bounding box. Errors with `NotFound` when the region is
     * empty.
     */
    bounds() {
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 25, 4, true);


        const result = wasm.DefinitionRegion_bounds(diplomatReceive.buffer, this.ffiValue);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new NucleationError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('NucleationError.' + cause.value, { cause });
            }
            return RegionBounds._fromFFI(diplomatRuntime.internalConstructor, diplomatReceive.buffer);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            diplomatReceive.free();
        }
    }

    dimensions() {
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 12, 4, false);


        const result = wasm.DefinitionRegion_dimensions(diplomatReceive.buffer, this.ffiValue);

        try {
            return Dimensions._fromFFI(diplomatRuntime.internalConstructor, diplomatReceive.buffer);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            diplomatReceive.free();
        }
    }

    /**
     * The center block position. Errors with `NotFound` when the region is
     * empty.
     */
    center() {
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 13, 4, true);


        const result = wasm.DefinitionRegion_center(diplomatReceive.buffer, this.ffiValue);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new NucleationError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('NucleationError.' + cause.value, { cause });
            }
            return BlockPos._fromFFI(diplomatRuntime.internalConstructor, diplomatReceive.buffer);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            diplomatReceive.free();
        }
    }

    /**
     * The exact (fractional) center, written as a JSON `[x, y, z]` array of
     * floats. Errors with `NotFound` when the region is empty.
     */
    centerF32Json() {
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);

        const write = new diplomatRuntime.DiplomatWriteBuf(wasm);


        const result = wasm.DefinitionRegion_center_f32_json(diplomatReceive.buffer, this.ffiValue, write.buffer);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new NucleationError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('NucleationError.' + cause.value, { cause });
            }
            return write.readString8();
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            diplomatReceive.free();
            write.free();
        }
    }

    /**
     * Every contained position, written as a flat JSON array of ints
     * (`[x0, y0, z0, x1, y1, z1, …]`), deduplicated, in box order.
     */
    positionsJson() {
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);

        const write = new diplomatRuntime.DiplomatWriteBuf(wasm);


        const result = wasm.DefinitionRegion_positions_json(diplomatReceive.buffer, this.ffiValue, write.buffer);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new NucleationError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('NucleationError.' + cause.value, { cause });
            }
            return write.readString8();
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            diplomatReceive.free();
            write.free();
        }
    }

    /**
     * Every contained position in sorted (y, z, x) order, written as a flat
     * JSON array of ints.
     */
    positionsSortedJson() {
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);

        const write = new diplomatRuntime.DiplomatWriteBuf(wasm);


        const result = wasm.DefinitionRegion_positions_sorted_json(diplomatReceive.buffer, this.ffiValue, write.buffer);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new NucleationError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('NucleationError.' + cause.value, { cause });
            }
            return write.readString8();
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            diplomatReceive.free();
            write.free();
        }
    }

    /**
     * The number of boxes making up this region.
     */
    boxCount() {

        const result = wasm.DefinitionRegion_box_count(this.ffiValue);

        try {
            return result;
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    /**
     * The box at `index`. Errors with `NotFound` when out of range.
     */
    getBox(index) {
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 25, 4, true);


        const result = wasm.DefinitionRegion_get_box(diplomatReceive.buffer, this.ffiValue, index);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new NucleationError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('NucleationError.' + cause.value, { cause });
            }
            return RegionBounds._fromFFI(diplomatRuntime.internalConstructor, diplomatReceive.buffer);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            diplomatReceive.free();
        }
    }

    /**
     * Every box, written as a flat JSON array of ints (six ints per box:
     * `min_x, min_y, min_z, max_x, max_y, max_z`).
     */
    boxesJson() {
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);

        const write = new diplomatRuntime.DiplomatWriteBuf(wasm);


        const result = wasm.DefinitionRegion_boxes_json(diplomatReceive.buffer, this.ffiValue, write.buffer);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new NucleationError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('NucleationError.' + cause.value, { cause });
            }
            return write.readString8();
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            diplomatReceive.free();
            write.free();
        }
    }

    isContiguous() {

        const result = wasm.DefinitionRegion_is_contiguous(this.ffiValue);

        try {
            return result;
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    connectedComponents() {

        const result = wasm.DefinitionRegion_connected_components(this.ffiValue);

        try {
            return result;
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    /**
     * Merge overlapping/adjacent boxes into a minimal representation.
     */
    simplify() {
    wasm.DefinitionRegion_simplify(this.ffiValue);

        try {}

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    /**
     * A new region containing only the positions where `schematic` has a
     * block named `block_name`.
     */
    filterByBlock(schematic, blockName) {
        let functionCleanupArena = new diplomatRuntime.CleanupArena();

        const blockNameSlice = functionCleanupArena.alloc(diplomatRuntime.DiplomatBuf.sliceWrapper(wasm, diplomatRuntime.DiplomatBuf.str8(wasm, blockName)));
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);


        const result = wasm.DefinitionRegion_filter_by_block(diplomatReceive.buffer, this.ffiValue, schematic.ffiValue, blockNameSlice.ptr);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new NucleationError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('NucleationError.' + cause.value, { cause });
            }
            return new DefinitionRegion(diplomatRuntime.internalConstructor, diplomatRuntime.ptrRead(wasm, diplomatReceive.buffer), []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            functionCleanupArena.free();

            diplomatReceive.free();
        }
    }

    /**
     * A new region containing only the positions where the block in
     * `schematic` matches every property in `properties_json` (a JSON
     * object of property name → value strings).
     */
    filterByProperties(schematic, propertiesJson) {
        let functionCleanupArena = new diplomatRuntime.CleanupArena();

        const propertiesJsonSlice = functionCleanupArena.alloc(diplomatRuntime.DiplomatBuf.sliceWrapper(wasm, diplomatRuntime.DiplomatBuf.str8(wasm, propertiesJson)));
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);


        const result = wasm.DefinitionRegion_filter_by_properties(diplomatReceive.buffer, this.ffiValue, schematic.ffiValue, propertiesJsonSlice.ptr);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new NucleationError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('NucleationError.' + cause.value, { cause });
            }
            return new DefinitionRegion(diplomatRuntime.internalConstructor, diplomatRuntime.ptrRead(wasm, diplomatReceive.buffer), []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            functionCleanupArena.free();

            diplomatReceive.free();
        }
    }

    /**
     * Remove every position where `schematic` has a block named
     * `block_name` (in place).
     */
    excludeBlock(schematic, blockName) {
        let functionCleanupArena = new diplomatRuntime.CleanupArena();

        const blockNameSlice = functionCleanupArena.alloc(diplomatRuntime.DiplomatBuf.sliceWrapper(wasm, diplomatRuntime.DiplomatBuf.str8(wasm, blockName)));
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);


        const result = wasm.DefinitionRegion_exclude_block(diplomatReceive.buffer, this.ffiValue, schematic.ffiValue, blockNameSlice.ptr);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new NucleationError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('NucleationError.' + cause.value, { cause });
            }
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            functionCleanupArena.free();

            diplomatReceive.free();
        }
    }

    intersectsBounds(minX, minY, minZ, maxX, maxY, maxZ) {

        const result = wasm.DefinitionRegion_intersects_bounds(this.ffiValue, minX, minY, minZ, maxX, maxY, maxZ);

        try {
            return result;
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    /**
     * A new region shifted by (`dx`, `dy`, `dz`).
     */
    shifted(dx, dy, dz) {

        const result = wasm.DefinitionRegion_shifted(this.ffiValue, dx, dy, dz);

        try {
            return new DefinitionRegion(diplomatRuntime.internalConstructor, result, []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    /**
     * A new region expanded by (`x`, `y`, `z`) on each axis.
     */
    expanded(x, y, z) {

        const result = wasm.DefinitionRegion_expanded(this.ffiValue, x, y, z);

        try {
            return new DefinitionRegion(diplomatRuntime.internalConstructor, result, []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    /**
     * A new region contracted by `amount` on every axis.
     */
    contracted(amount) {

        const result = wasm.DefinitionRegion_contracted(this.ffiValue, amount);

        try {
            return new DefinitionRegion(diplomatRuntime.internalConstructor, result, []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    /**
     * A deep copy of this region.
     */
    copy() {

        const result = wasm.DefinitionRegion_copy(this.ffiValue);

        try {
            return new DefinitionRegion(diplomatRuntime.internalConstructor, result, []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    /**
     * Store a display color (`0xRRGGBB`) in the region's metadata.
     */
    setColor(color) {
    wasm.DefinitionRegion_set_color(this.ffiValue, color);

        try {}

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    /**
     * The blocks of `schematic` inside this region, written as a JSON array
     * of `{"x", "y", "z", "name", "properties"}` objects (the old ABI
     * returned a `CBlockArray`).
     */
    blocksJson(schematic) {
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);

        const write = new diplomatRuntime.DiplomatWriteBuf(wasm);


        const result = wasm.DefinitionRegion_blocks_json(diplomatReceive.buffer, this.ffiValue, schematic.ffiValue, write.buffer);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new NucleationError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('NucleationError.' + cause.value, { cause });
            }
            return write.readString8();
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            diplomatReceive.free();
            write.free();
        }
    }

    /**
     * Write this region into `schematic`'s definition-region map under
     * `name` (insert or overwrite).
     */
    sync(schematic, name) {
        let functionCleanupArena = new diplomatRuntime.CleanupArena();

        const nameSlice = functionCleanupArena.alloc(diplomatRuntime.DiplomatBuf.sliceWrapper(wasm, diplomatRuntime.DiplomatBuf.str8(wasm, name)));
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);


        const result = wasm.DefinitionRegion_sync(diplomatReceive.buffer, this.ffiValue, schematic.ffiValue, nameSlice.ptr);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new NucleationError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('NucleationError.' + cause.value, { cause });
            }
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            functionCleanupArena.free();

            diplomatReceive.free();
        }
    }

    constructor(symbol, ptr, selfEdge) {
        return this.#internalConstructor(...arguments)
    }
}