// generated by diplomat-tool
import type { NucleationError } from "./NucleationError.mjs"
import type { Schematic } from "./Schematic.mjs"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * A composition document: loose blocks + cell instances + bus layers
 * over a shared coordinate space.
 */
export class Design {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    /**
     * An empty design.
     */
    static create(name: string): Design;

    /**
     * A design whose loose block layer is a copy of `base` (endpoint
     * hardware placed with raw `set_block`).
     */
    static forSchematic(name: string, base: Schematic): Design;

    /**
     * Register a library cell; its contract is resolved from the
     * schematic (embedded metadata first, Insign signs as fallback)
     * and registration fails loudly when no source defines one.
     * Writes resolution warnings as a JSON array of strings.
     */
    addCell(name: string, cell: Schematic): string;

    /**
     * Place an instance layer referencing a library cell. `rot_y` is
     * in degrees, a multiple of 90.
     */
    place(name: string, cell: string, x: number, y: number, z: number, rotY: number): void;

    /**
     * Declare a drivable input port: anchor = bit-0 connection cell,
     * step to the next bit, `width` bits of `ty` (`"uint"` or
     * `"bool"`). The hardware is scanned (adjacent lever per bit) and
     * validated loudly.
     */
    declareInput(name: string, ax: number, ay: number, az: number, sx: number, sy: number, sz: number, width: number, ty: string): void;

    /**
     * Declare a readable output port (adjacent lamp per bit); same
     * shape as `declare_input`.
     */
    declareOutput(name: string, ax: number, ay: number, az: number, sx: number, sy: number, sz: number, width: number, ty: string): void;

    /**
     * Declare AND realize a bus. `sinks_json` is a JSON array of port
     * names; `gates_json` an array of `{"name", "anchor": [x,y,z],
     * "step": [x,y,z]}` (pass `[]` for none); `style_json` an object
     * with optional `bus_block` / `transparent_block`. Declaration
     * errors are error returns; geometric unroutability is the
     * written STATE: `"routed"` or `"failed: reason"` — realization
     * is atomic, never half-routed.
     */
    routeBus(name: string, driver: string, sinksJson: string, gatesJson: string, styleJson: string): string;

    /**
     * Declare AND realize a wired-OR bus: `drivers_json` is a JSON
     * array of port names — multiple drivers are legal ONLY through
     * this explicit merge (`merge="or"`). Extra drivers join the
     * trunk as diode-isolated dust-merge branches; the LVS intent
     * stays ONE net per bit. Same shapes as `route_bus` otherwise.
     */
    routeBusOr(name: string, driversJson: string, sinksJson: string, gatesJson: string, styleJson: string): string;

    /**
     * Edit the loose block layer: plain `set_block` on the base
     * schematic (participates in occupancy and flatten).
     */
    setBlock(x: number, y: number, z: number, block: string): void;

    /**
     * Drag an instance layer to a new position/rotation. The move
     * itself ALWAYS succeeds (the document's truth); the affected bus
     * set — fragments intersecting the old or new footprint +
     * influence halo, plus every already-failed bus — is ripped and
     * co-rerouted deterministically with bounded retry rounds.
     * Writes `{"rerouted": [...], "failed": {name: reason}}`.
     */
    moveInstance(name: string, x: number, y: number, z: number, rotY: number): string;

    /**
     * Remove an instance layer. Buses that terminate on one of its
     * ports are DELETED (they lost an endpoint); buses that merely
     * crossed its space are ripped and co-rerouted. Writes
     * `{"removed_buses": [...], "rerouted": [...], "failed": {...}}`.
     */
    removeInstance(name: string): string;

    /**
     * Re-realize a bus from its stored declaration (the counterpart to
     * `rip`); writes the resulting bus state.
     */
    reroute(name: string): string;

    /**
     * Delete a bus outright — fragment AND declaration, freeing the
     * name. `rip` keeps the declaration so the bus can be rerouted.
     */
    removeBus(name: string): void;

    /**
     * The flattened artifact as `.schem` bytes, base64. Unlike
     * `flatten()` + the schematic writer, this composites the layer
     * stack into ONE region first: `.schem` has no layers, and the
     * region merge drops named-layer cells that the loose layer's
     * bounding box shadows.
     */
    toSchemB64(): string;

    /**
     * The flattened artifact composited into ONE region (see
     * `to_schem_b64`) — the shape an interchange export wants.
     */
    flattenComposite(): Schematic;

    /**
     * Every routing endpoint the placed instances expose, as a JSON
     * array of `{name, instance, port, role, ty, width, hardware,
     * wires, step, routable, blocked}`. `name` is `{instance}.{port}`
     * — exactly what `route_bus` accepts; `role` is the CELL-facing
     * direction, so `"output"` drives a bus and `"input"` receives
     * one. A port whose bits have no dust connection cell (a lever
     * input, say) reports `routable: false` and why in `blocked`.
     */
    instancePorts(): string;

    /**
     * Resolve one routing endpoint name — a declared design port or an
     * instance port `{instance}.{port}` — to the geometry a bus would
     * use: `{"name","anchor","step","width","direction","connectable"}`.
     * `direction` is DESIGN-facing (`"input"` drives buses).
     */
    resolvePort(name: string): string;

    /**
     * Add a gate to an existing bus (splitting the segment it lands
     * in) and re-realize it. Writes the resulting bus state.
     */
    addGate(bus: string, gate: string, x: number, y: number, z: number, sx: number, sy: number, sz: number): string;

    /**
     * Drag a gate: the anchor moves unconditionally, then EXACTLY the
     * two adjacent segments are ripped and rerouted atomically. An
     * unroutable move leaves the bus `failed: reason` — visible,
     * never half-routed. Writes `{"state": "...",
     * "rerouted_segments": n}`.
     */
    moveGate(bus: string, gate: string, x: number, y: number, z: number): string;

    /**
     * Attach a net-class discipline to a bus (JSON `NetClassRule`:
     * optional `max_len_rt` delay budget, `y_band` layer band, …);
     * `check()` enforces it.
     */
    setBusRule(bus: string, ruleJson: string): void;

    /**
     * Per-bus skew from the routed fragment: writes
     * `{"per_bit_rt": [...], "skew_rt": n, "max_rt": n}`.
     */
    busSkew(name: string): string;

    /**
     * The lifecycle state of a bus: `"intended"`, `"routed"` or
     * `"failed: reason"`.
     */
    busState(name: string): string;

    /**
     * Rip a bus: clear its fragment, back to `intended`.
     */
    rip(name: string): void;

    /**
     * Collapse the layer stack into ONE self-describing schematic:
     * named regions per layer (`inst:x`, `bus:y`) and the merged
     * contract embedded in the metadata — itself placeable as a cell.
     */
    flatten(): Schematic;

    /**
     * DRC + LVS over the flattened artifact. Writes `{"clean",
     * "drc": [...], "lvs": {...}, "buses": {...}}`.
     */
    check(): string;

    /**
     * Settle the flattened artifact in the vanilla-accurate tick
     * engine and return it with every settled state written back and
     * `InitialState::Baked` stamped into the embedded contract (needs
     * the `mc-tick` feature, else errors).
     */
    bake(budget: number): Schematic;

    /**
     * Serialize the FULL design document to `.nucm` project-tier
     * bytes (magic `NUCM`): cells deduped by content hash, instance
     * transforms, ports with scanned hardware, every bus layer with
     * its fragment, runs and `intended`/`routed`/`failed: reason`
     * state, and the loose base layer. Base64 across the bridge.
     */
    toNucmB64(): string;

    /**
     * Reopen a `.nucm` design document from raw bytes. The reloaded
     * design is the same model mid-edit: rerouting works.
     */
    static fromNucm(data: Array<number>): Design;

    /**
     * Export the design as a LAYERED `.litematic` (interchange tier):
     * one named region per layer (`inst:{name}`, `bus:{name}`, loose
     * base) plus the design manifest as a root-level
     * `NucleationDesign` tag. Opens in Litematica as a plain
     * multi-region litematic; reimports as a design whose cell
     * references have degraded to embedded copies. Base64 across the
     * bridge.
     */
    toLitematicB64(): string;

    /**
     * Import a layered `.litematic` (with a `NucleationDesign`
     * manifest) from raw bytes; a plain litematic errors loudly —
     * open those with `Schematic.from_litematic`.
     */
    static fromLitematic(data: Array<number>): Design;
}