// generated by diplomat-tool
import type { NucleationError } from "./NucleationError"
import type { OutputCondition } from "./OutputCondition"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * How long to run the circuit for one `execute` call (PORTING rule 10).
 */
export class ExecutionMode {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    static fixedTicks(ticks: number): ExecutionMode;

    static untilCondition(outputName: string, condition: OutputCondition, maxTicks: number, checkInterval: number): ExecutionMode;

    static untilChange(maxTicks: number, checkInterval: number): ExecutionMode;

    static untilStable(stableTicks: number, maxTicks: number): ExecutionMode;
}