// generated by diplomat-tool
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * The closed interval a field's values are analytically proven to lie in.
 */
export class FieldRange {
    get min(): number;
    get max(): number;
    /** @internal */
    constructor();

}