// generated by diplomat-tool
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * What kind of distance a field program's output represents.
 */
export class FieldProgramDistanceKind {

    /** @internal */
    static fromValue(value: FieldProgramDistanceKind | string): FieldProgramDistanceKind;

    get value(): string;

    /** @internal */
    get ffiValue(): number;

    static Exact : FieldProgramDistanceKind;
    static LowerBound : FieldProgramDistanceKind;
    static Estimate : FieldProgramDistanceKind;
    static Implicit : FieldProgramDistanceKind;


    constructor(value: FieldProgramDistanceKind | string );
}