// generated by diplomat-tool
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";



/**
 * The type of a value on a {@link FieldProgramBuilder}'s stack or in a slot.
 */
export class FieldProgramValueType {
    #value = undefined;

    static #values = new Map([
        ["Scalar", 0],
        ["Vec3", 1],
        ["Bool", 2]
    ]);

    static getAllEntries() {
        return FieldProgramValueType.#values.entries();
    }

    #internalConstructor(value) {
        if (arguments.length > 1 && arguments[0] === diplomatRuntime.internalConstructor) {
            // We pass in two internalConstructor arguments to create *new*
            // instances of this type, otherwise the enums are treated as singletons.
            if (arguments[1] === diplomatRuntime.internalConstructor ) {
                this.#value = arguments[2];
                return this;
            }
            return FieldProgramValueType.#objectValues[arguments[1]];
        }

        if (value instanceof FieldProgramValueType) {
            return value;
        }

        let intVal = FieldProgramValueType.#values.get(value);

        // Nullish check, checks for null or undefined
        if (intVal != null) {
            return FieldProgramValueType.#objectValues[intVal];
        }

        throw TypeError(value + " is not a FieldProgramValueType and does not correspond to any of its enumerator values.");
    }

    /** @internal */
    static fromValue(value) {
        return new FieldProgramValueType(value);
    }

    get value(){
        return [...FieldProgramValueType.#values.keys()][this.#value];
    }

    /** @internal */
    get ffiValue(){
        return this.#value;
    }
    static #objectValues = [
        new FieldProgramValueType(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 0),
        new FieldProgramValueType(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 1),
        new FieldProgramValueType(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 2),
    ];

    static Scalar = FieldProgramValueType.#objectValues[0];
    static Vec3 = FieldProgramValueType.#objectValues[1];
    static Bool = FieldProgramValueType.#objectValues[2];


    constructor(value) {
        return this.#internalConstructor(...arguments)
    }
}