// generated by diplomat-tool
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";



/**
 * Unary field-program operations (see `crate::sdf::UnaryOp`).
 */
export class FieldProgramUnaryOp {
    #value = undefined;

    static #values = new Map([
        ["Neg", 0],
        ["Abs", 1],
        ["Sqrt", 2],
        ["Log", 3],
        ["Sin", 4],
        ["Cos", 5],
        ["Acos", 6],
        ["VecX", 7],
        ["VecY", 8],
        ["VecZ", 9],
        ["Length", 10],
        ["Normalize", 11]
    ]);

    static getAllEntries() {
        return FieldProgramUnaryOp.#values.entries();
    }

    #internalConstructor(value) {
        if (arguments.length > 1 && arguments[0] === diplomatRuntime.internalConstructor) {
            // We pass in two internalConstructor arguments to create *new*
            // instances of this type, otherwise the enums are treated as singletons.
            if (arguments[1] === diplomatRuntime.internalConstructor ) {
                this.#value = arguments[2];
                return this;
            }
            return FieldProgramUnaryOp.#objectValues[arguments[1]];
        }

        if (value instanceof FieldProgramUnaryOp) {
            return value;
        }

        let intVal = FieldProgramUnaryOp.#values.get(value);

        // Nullish check, checks for null or undefined
        if (intVal != null) {
            return FieldProgramUnaryOp.#objectValues[intVal];
        }

        throw TypeError(value + " is not a FieldProgramUnaryOp and does not correspond to any of its enumerator values.");
    }

    /** @internal */
    static fromValue(value) {
        return new FieldProgramUnaryOp(value);
    }

    get value(){
        return [...FieldProgramUnaryOp.#values.keys()][this.#value];
    }

    /** @internal */
    get ffiValue(){
        return this.#value;
    }
    static #objectValues = [
        new FieldProgramUnaryOp(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 0),
        new FieldProgramUnaryOp(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 1),
        new FieldProgramUnaryOp(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 2),
        new FieldProgramUnaryOp(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 3),
        new FieldProgramUnaryOp(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 4),
        new FieldProgramUnaryOp(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 5),
        new FieldProgramUnaryOp(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 6),
        new FieldProgramUnaryOp(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 7),
        new FieldProgramUnaryOp(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 8),
        new FieldProgramUnaryOp(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 9),
        new FieldProgramUnaryOp(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 10),
        new FieldProgramUnaryOp(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 11),
    ];

    static Neg = FieldProgramUnaryOp.#objectValues[0];
    static Abs = FieldProgramUnaryOp.#objectValues[1];
    static Sqrt = FieldProgramUnaryOp.#objectValues[2];
    static Log = FieldProgramUnaryOp.#objectValues[3];
    static Sin = FieldProgramUnaryOp.#objectValues[4];
    static Cos = FieldProgramUnaryOp.#objectValues[5];
    static Acos = FieldProgramUnaryOp.#objectValues[6];
    static VecX = FieldProgramUnaryOp.#objectValues[7];
    static VecY = FieldProgramUnaryOp.#objectValues[8];
    static VecZ = FieldProgramUnaryOp.#objectValues[9];
    static Length = FieldProgramUnaryOp.#objectValues[10];
    static Normalize = FieldProgramUnaryOp.#objectValues[11];


    constructor(value) {
        return this.#internalConstructor(...arguments)
    }
}