// generated by diplomat-tool
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";



/**
 * Binary field-program operations (see `crate::sdf::BinaryOp`). `Add`
 * and `Sub` accept either two scalars or two vec3s.
 */
export class FieldProgramBinaryOp {
    #value = undefined;

    static #values = new Map([
        ["Add", 0],
        ["Sub", 1],
        ["Mul", 2],
        ["Div", 3],
        ["Min", 4],
        ["Max", 5],
        ["Pow", 6],
        ["Atan2", 7],
        ["Lt", 8],
        ["Le", 9],
        ["Gt", 10],
        ["Ge", 11],
        ["Eq", 12],
        ["Dot", 13],
        ["Cross", 14],
        ["Scale", 15]
    ]);

    static getAllEntries() {
        return FieldProgramBinaryOp.#values.entries();
    }

    #internalConstructor(value) {
        if (arguments.length > 1 && arguments[0] === diplomatRuntime.internalConstructor) {
            // We pass in two internalConstructor arguments to create *new*
            // instances of this type, otherwise the enums are treated as singletons.
            if (arguments[1] === diplomatRuntime.internalConstructor ) {
                this.#value = arguments[2];
                return this;
            }
            return FieldProgramBinaryOp.#objectValues[arguments[1]];
        }

        if (value instanceof FieldProgramBinaryOp) {
            return value;
        }

        let intVal = FieldProgramBinaryOp.#values.get(value);

        // Nullish check, checks for null or undefined
        if (intVal != null) {
            return FieldProgramBinaryOp.#objectValues[intVal];
        }

        throw TypeError(value + " is not a FieldProgramBinaryOp and does not correspond to any of its enumerator values.");
    }

    /** @internal */
    static fromValue(value) {
        return new FieldProgramBinaryOp(value);
    }

    get value(){
        return [...FieldProgramBinaryOp.#values.keys()][this.#value];
    }

    /** @internal */
    get ffiValue(){
        return this.#value;
    }
    static #objectValues = [
        new FieldProgramBinaryOp(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 0),
        new FieldProgramBinaryOp(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 1),
        new FieldProgramBinaryOp(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 2),
        new FieldProgramBinaryOp(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 3),
        new FieldProgramBinaryOp(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 4),
        new FieldProgramBinaryOp(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 5),
        new FieldProgramBinaryOp(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 6),
        new FieldProgramBinaryOp(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 7),
        new FieldProgramBinaryOp(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 8),
        new FieldProgramBinaryOp(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 9),
        new FieldProgramBinaryOp(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 10),
        new FieldProgramBinaryOp(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 11),
        new FieldProgramBinaryOp(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 12),
        new FieldProgramBinaryOp(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 13),
        new FieldProgramBinaryOp(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 14),
        new FieldProgramBinaryOp(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 15),
    ];

    static Add = FieldProgramBinaryOp.#objectValues[0];
    static Sub = FieldProgramBinaryOp.#objectValues[1];
    static Mul = FieldProgramBinaryOp.#objectValues[2];
    static Div = FieldProgramBinaryOp.#objectValues[3];
    static Min = FieldProgramBinaryOp.#objectValues[4];
    static Max = FieldProgramBinaryOp.#objectValues[5];
    static Pow = FieldProgramBinaryOp.#objectValues[6];
    static Atan2 = FieldProgramBinaryOp.#objectValues[7];
    static Lt = FieldProgramBinaryOp.#objectValues[8];
    static Le = FieldProgramBinaryOp.#objectValues[9];
    static Gt = FieldProgramBinaryOp.#objectValues[10];
    static Ge = FieldProgramBinaryOp.#objectValues[11];
    static Eq = FieldProgramBinaryOp.#objectValues[12];
    static Dot = FieldProgramBinaryOp.#objectValues[13];
    static Cross = FieldProgramBinaryOp.#objectValues[14];
    /**
     * `vec3 * scalar`, componentwise.
     */
    static Scale = FieldProgramBinaryOp.#objectValues[15];


    constructor(value) {
        return this.#internalConstructor(...arguments)
    }
}