// generated by diplomat-tool
import type { NucleationError } from "./NucleationError"
import type { Schematic } from "./Schematic"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * Namespace type for the fingerprint free functions (PORTING rule 12).
 */
export class Fingerprint {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    /**
     * The fingerprint of a schematic for the given preset, as a hex string.
     * Errors with `InvalidArgument` on an unknown preset.
     */
    static compute(schematic: Schematic, preset: string): string;

    /**
     * The structural signature (JSON) of a schematic for the given preset.
     */
    static signatureJson(schematic: Schematic, preset: string): string;

    /**
     * Translation-invariant fuzzy distance between two builds' footprints.
     */
    static footprintDistance(a: Schematic, b: Schematic, preset: string): number;

    /**
     * The schematic's translation/scale-invariant FFT shape footprint as a
     * JSON array of floats.
     */
    static footprintJson(schematic: Schematic, preset: string): string;

    /**
     * Whether two schematics share the same fingerprint for the given preset.
     */
    static isDuplicate(a: Schematic, b: Schematic, preset: string): boolean;
}