// generated by diplomat-tool
import type { GeneratedChunkCoverage } from "./GeneratedChunkCoverage.mjs"
import type { NucleationError } from "./NucleationError.mjs"
import type { WorldChunkView } from "./WorldChunkView.mjs"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * One generated chunk plus coverage and source-version metadata.
 * Call `take_view` once to move its chunk into the existing world-stream API.
 */
export class GeneratedChunk {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    cx(): number;

    cz(): number;

    coverage(): GeneratedChunkCoverage;

    sourceId(): string;

    version(): string;

    /**
     * Consume the generated chunk payload. Metadata access and a second call
     * return `AlreadyConsumed` afterwards.
     */
    takeView(): WorldChunkView;
}