// generated by diplomat-tool
import { NucleationError } from "./NucleationError.mjs"
import { Schematic } from "./Schematic.mjs"
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";

const Geo_box_destroy_registry = new FinalizationRegistry((ptr) => {
    wasm.Geo_destroy(ptr);
});

/**
 * Namespace for the geodata entry points (no network — data goes in,
 * blocks come out).
 */
export class Geo {
    // Internal ptr reference:
    #ptr = null;

    // Lifetimes are only to keep dependencies alive.
    // Since JS won't garbage collect until there are no incoming edges.
    #selfEdge = [];

    #internalConstructor(symbol, ptr, selfEdge) {
        if (symbol !== diplomatRuntime.internalConstructor) {
            console.error("Geo is an Opaque type. You cannot call its constructor.");
            return;
        }
        this.#ptr = ptr;
        this.#selfEdge = selfEdge;

        // Are we being borrowed? If not, we can register.
        if (this.#selfEdge.length === 0) {
            Geo_box_destroy_registry.register(this, this.#ptr);
        }

        return this;
    }
    /** @internal */
    get ffiValue() {
        return this.#ptr;
    }


    /**
     * Extrude building footprints into a massed schematic. `buildings_json`
     * is a JSON array of objects:
     * `{"polygon": [[x, z], ...], "height": <blocks>, "block": "minecraft:...",
     * "min_y": <optional base, default 1>}`. Footprints are stamped
     * tallest-last, so overlaps keep the tallest occupant per column.
     * `base_block` (empty string = none) lays a ground slab at y=0 under the
     * whole extent. Errors `Parse` on bad JSON, `InvalidArgument` on non-UTF-8.
     */
    static extrudeFootprints(buildingsJson, baseBlock, name) {
        let functionCleanupArena = new diplomatRuntime.CleanupArena();

        const buildingsJsonSlice = functionCleanupArena.alloc(diplomatRuntime.DiplomatBuf.sliceWrapper(wasm, diplomatRuntime.DiplomatBuf.str8(wasm, buildingsJson)));
        const baseBlockSlice = functionCleanupArena.alloc(diplomatRuntime.DiplomatBuf.sliceWrapper(wasm, diplomatRuntime.DiplomatBuf.str8(wasm, baseBlock)));
        const nameSlice = functionCleanupArena.alloc(diplomatRuntime.DiplomatBuf.sliceWrapper(wasm, diplomatRuntime.DiplomatBuf.str8(wasm, name)));
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);


        const result = wasm.Geo_extrude_footprints(diplomatReceive.buffer, buildingsJsonSlice.ptr, baseBlockSlice.ptr, nameSlice.ptr);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new NucleationError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('NucleationError.' + cause.value, { cause });
            }
            return new Schematic(diplomatRuntime.internalConstructor, diplomatRuntime.ptrRead(wasm, diplomatReceive.buffer), []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            functionCleanupArena.free();

            diplomatReceive.free();
        }
    }

    /**
     * Raise terrain from a heightmap. `heights_json` is a flat row-major
     * JSON array of per-column heights (blocks); `width` is columns per row.
     * `surface_blocks_json` is a JSON array of block names — one entry (the
     * same surface everywhere) or one per column, row-major and the same
     * length as `heights`, for elevation/slope banding. Each column's top
     * `surface_depth` blocks are its surface block, the rest are
     * `subsurface_block`. Errors `Parse` on bad JSON, `InvalidArgument` on a
     * non-positive width, empty surface list, or non-UTF-8.
     */
    static heightmapTerrain(heightsJson, width, surfaceBlocksJson, subsurfaceBlock, surfaceDepth, name) {
        let functionCleanupArena = new diplomatRuntime.CleanupArena();

        const heightsJsonSlice = functionCleanupArena.alloc(diplomatRuntime.DiplomatBuf.sliceWrapper(wasm, diplomatRuntime.DiplomatBuf.str8(wasm, heightsJson)));
        const surfaceBlocksJsonSlice = functionCleanupArena.alloc(diplomatRuntime.DiplomatBuf.sliceWrapper(wasm, diplomatRuntime.DiplomatBuf.str8(wasm, surfaceBlocksJson)));
        const subsurfaceBlockSlice = functionCleanupArena.alloc(diplomatRuntime.DiplomatBuf.sliceWrapper(wasm, diplomatRuntime.DiplomatBuf.str8(wasm, subsurfaceBlock)));
        const nameSlice = functionCleanupArena.alloc(diplomatRuntime.DiplomatBuf.sliceWrapper(wasm, diplomatRuntime.DiplomatBuf.str8(wasm, name)));
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);


        const result = wasm.Geo_heightmap_terrain(diplomatReceive.buffer, heightsJsonSlice.ptr, width, surfaceBlocksJsonSlice.ptr, subsurfaceBlockSlice.ptr, surfaceDepth, nameSlice.ptr);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new NucleationError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('NucleationError.' + cause.value, { cause });
            }
            return new Schematic(diplomatRuntime.internalConstructor, diplomatRuntime.ptrRead(wasm, diplomatReceive.buffer), []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            functionCleanupArena.free();

            diplomatReceive.free();
        }
    }

    constructor(symbol, ptr, selfEdge) {
        return this.#internalConstructor(...arguments)
    }
}