// generated by diplomat-tool
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";



/**
 * Color interpolation space for gradient brushes. The old ABI passed this as
 * `space: c_int` (`1` = Oklab, anything else = RGB).
 */
export class InterpolationSpace {
    #value = undefined;

    static #values = new Map([
        ["Rgb", 0],
        ["Oklab", 1]
    ]);

    static getAllEntries() {
        return InterpolationSpace.#values.entries();
    }

    #internalConstructor(value) {
        if (arguments.length > 1 && arguments[0] === diplomatRuntime.internalConstructor) {
            // We pass in two internalConstructor arguments to create *new*
            // instances of this type, otherwise the enums are treated as singletons.
            if (arguments[1] === diplomatRuntime.internalConstructor ) {
                this.#value = arguments[2];
                return this;
            }
            return InterpolationSpace.#objectValues[arguments[1]];
        }

        if (value instanceof InterpolationSpace) {
            return value;
        }

        let intVal = InterpolationSpace.#values.get(value);

        // Nullish check, checks for null or undefined
        if (intVal != null) {
            return InterpolationSpace.#objectValues[intVal];
        }

        throw TypeError(value + " is not a InterpolationSpace and does not correspond to any of its enumerator values.");
    }

    /** @internal */
    static fromValue(value) {
        return new InterpolationSpace(value);
    }

    get value(){
        return [...InterpolationSpace.#values.keys()][this.#value];
    }

    /** @internal */
    get ffiValue(){
        return this.#value;
    }
    static #objectValues = [
        new InterpolationSpace(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 0),
        new InterpolationSpace(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 1),
    ];

    static Rgb = InterpolationSpace.#objectValues[0];
    static Oklab = InterpolationSpace.#objectValues[1];


    constructor(value) {
        return this.#internalConstructor(...arguments)
    }
}