// generated by diplomat-tool
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";



/**
 * Non-uniform model scale factors.
 */
export class ItemScale {
    #x;
    get x() {
        return this.#x;
    }
    set x(value){
        this.#x = value;
    }
    #y;
    get y() {
        return this.#y;
    }
    set y(value){
        this.#y = value;
    }
    #z;
    get z() {
        return this.#z;
    }
    set z(value){
        this.#z = value;
    }
    /** @internal */
    static fromFields(structObj) {
        return new ItemScale(structObj);
    }

    #internalConstructor(structObj) {
        if (typeof structObj !== "object") {
            throw new Error("ItemScale's constructor takes an object of ItemScale's fields.");
        }

        if ("x" in structObj) {
            this.#x = structObj.x;
        } else {
            throw new Error("Missing required field x.");
        }

        if ("y" in structObj) {
            this.#y = structObj.y;
        } else {
            throw new Error("Missing required field y.");
        }

        if ("z" in structObj) {
            this.#z = structObj.z;
        } else {
            throw new Error("Missing required field z.");
        }

        return this;
    }

    // Return this struct in FFI function friendly format.
    // Returns an array that can be expanded with spread syntax (...)
    _intoFFI(
        dst,
        functionCleanupArena,
        appendArrayMap
    ) {

        this._writeToArrayBuffer(wasm.memory.buffer, dst, functionCleanupArena, appendArrayMap);

        return dst;
    }

    static get _sizeBytes() {
        return 12;
    }

    /// Currently unused, we may want to use later on though:
    static get _sizeAlign() {
        return 4;
    }

    static _fromSuppliedValue(internalConstructor, obj) {
        if (internalConstructor !== diplomatRuntime.internalConstructor) {
            throw new Error("_fromSuppliedValue cannot be called externally.");
        }

        if (obj instanceof ItemScale) {
            return obj;
        }

        return ItemScale.fromFields(obj);
    }

    _writeToArrayBuffer(
        arrayBuffer,
        offset,
        functionCleanupArena,
        appendArrayMap
    ) {
        diplomatRuntime.writeToArrayBuffer(arrayBuffer, offset + 0, this.#x, Float32Array);
        diplomatRuntime.writeToArrayBuffer(arrayBuffer, offset + 4, this.#y, Float32Array);
        diplomatRuntime.writeToArrayBuffer(arrayBuffer, offset + 8, this.#z, Float32Array);
    }

    // This struct contains borrowed fields, so this takes in a list of
    // "edges" corresponding to where each lifetime's data may have been borrowed from
    // and passes it down to individual fields containing the borrow.
    // This method does not attempt to handle any dependencies between lifetimes, the caller
    // should handle this when constructing edge arrays.
    static _fromFFI(internalConstructor, ptr) {
        if (internalConstructor !== diplomatRuntime.internalConstructor) {
            throw new Error("ItemScale._fromFFI is not meant to be called externally. Please use the default constructor.");
        }
        let structObj = {};
        const xDeref = (new Float32Array(wasm.memory.buffer, ptr, 1))[0];
        structObj.x = xDeref;
        const yDeref = (new Float32Array(wasm.memory.buffer, ptr + 4, 1))[0];
        structObj.y = yDeref;
        const zDeref = (new Float32Array(wasm.memory.buffer, ptr + 8, 1))[0];
        structObj.z = zDeref;

        return new ItemScale(structObj);
    }


    constructor(structObj) {
        return this.#internalConstructor(...arguments)
    }
}