// generated by diplomat-tool
import { NucleationError } from "./NucleationError.mjs"
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";

const LayoutFunction_box_destroy_registry = new FinalizationRegistry((ptr) => {
    wasm.LayoutFunction_destroy(ptr);
});

/**
 * Maps logical bits to physical positions (PORTING rule 10).
 */
export class LayoutFunction {
    // Internal ptr reference:
    #ptr = null;

    // Lifetimes are only to keep dependencies alive.
    // Since JS won't garbage collect until there are no incoming edges.
    #selfEdge = [];

    #internalConstructor(symbol, ptr, selfEdge) {
        if (symbol !== diplomatRuntime.internalConstructor) {
            console.error("LayoutFunction is an Opaque type. You cannot call its constructor.");
            return;
        }
        this.#ptr = ptr;
        this.#selfEdge = selfEdge;

        // Are we being borrowed? If not, we can register.
        if (this.#selfEdge.length === 0) {
            LayoutFunction_box_destroy_registry.register(this, this.#ptr);
        }

        return this;
    }
    /** @internal */
    get ffiValue() {
        return this.#ptr;
    }


    /**
     * One bit per position: signal strength 0 = false, 15 = true.
     * The most common layout for traditional redstone circuits.
     */
    static oneToOne() {

        const result = wasm.LayoutFunction_one_to_one();

        try {
            return new LayoutFunction(diplomatRuntime.internalConstructor, result, []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    /**
     * Four bits per position, packed as a hex nibble (0-15) with the
     * lowest bit first; uses `ceil(bits / 4)` positions (4x denser than
     * one-to-one).
     */
    static packed4() {

        const result = wasm.LayoutFunction_packed4();

        try {
            return new LayoutFunction(diplomatRuntime.internalConstructor, result, []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    /**
     * Custom bit-to-position mapping.
     */
    static custom(mapping) {
        let functionCleanupArena = new diplomatRuntime.CleanupArena();

        const mappingSlice = functionCleanupArena.alloc(diplomatRuntime.DiplomatBuf.sliceWrapper(wasm, diplomatRuntime.DiplomatBuf.slice(wasm, mapping, "u32")));
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);


        const result = wasm.LayoutFunction_custom(diplomatReceive.buffer, mappingSlice.ptr);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new NucleationError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('NucleationError.' + cause.value, { cause });
            }
            return new LayoutFunction(diplomatRuntime.internalConstructor, diplomatRuntime.ptrRead(wasm, diplomatReceive.buffer), []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            functionCleanupArena.free();

            diplomatReceive.free();
        }
    }

    /**
     * 2D matrix layout, elements laid out row by row; element bits are
     * packed 4 per position (nibbles).
     */
    static rowMajor(rows, cols, bitsPerElement) {

        const result = wasm.LayoutFunction_row_major(rows, cols, bitsPerElement);

        try {
            return new LayoutFunction(diplomatRuntime.internalConstructor, result, []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    /**
     * 2D matrix layout, elements laid out column by column; element bits
     * are packed 4 per position (nibbles).
     */
    static columnMajor(rows, cols, bitsPerElement) {

        const result = wasm.LayoutFunction_column_major(rows, cols, bitsPerElement);

        try {
            return new LayoutFunction(diplomatRuntime.internalConstructor, result, []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    /**
     * Screen layout: pixels laid out row by row, left to right; pixel
     * bits are packed 4 per position (nibbles).
     */
    static scanline(width, height, bitsPerPixel) {

        const result = wasm.LayoutFunction_scanline(width, height, bitsPerPixel);

        try {
            return new LayoutFunction(diplomatRuntime.internalConstructor, result, []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    constructor(symbol, ptr, selfEdge) {
        return this.#internalConstructor(...arguments)
    }
}