// generated by diplomat-tool
import { NucleationError } from "./NucleationError.mjs"
import { RedstoneGraph } from "./RedstoneGraph.mjs"
import { Schematic } from "./Schematic.mjs"
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";

const MchprsWorld_box_destroy_registry = new FinalizationRegistry((ptr) => {
    wasm.MchprsWorld_destroy(ptr);
});

/**
 * A running MCHPRS redstone simulation. Wraps {@link crate::simulation::MchprsWorld}.
 */
export class MchprsWorld {
    // Internal ptr reference:
    #ptr = null;

    // Lifetimes are only to keep dependencies alive.
    // Since JS won't garbage collect until there are no incoming edges.
    #selfEdge = [];

    #internalConstructor(symbol, ptr, selfEdge) {
        if (symbol !== diplomatRuntime.internalConstructor) {
            console.error("MchprsWorld is an Opaque type. You cannot call its constructor.");
            return;
        }
        this.#ptr = ptr;
        this.#selfEdge = selfEdge;

        // Are we being borrowed? If not, we can register.
        if (this.#selfEdge.length === 0) {
            MchprsWorld_box_destroy_registry.register(this, this.#ptr);
        }

        return this;
    }
    /** @internal */
    get ffiValue() {
        return this.#ptr;
    }


    /**
     * Create a simulation world from a schematic with default options.
     */
    static create(schematic) {
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);


        const result = wasm.MchprsWorld_create(diplomatReceive.buffer, schematic.ffiValue);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new NucleationError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('NucleationError.' + cause.value, { cause });
            }
            return new MchprsWorld(diplomatRuntime.internalConstructor, diplomatRuntime.ptrRead(wasm, diplomatReceive.buffer), []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            diplomatReceive.free();
        }
    }

    /**
     * Create a simulation world with explicit options.
     */
    static createWithOptions(schematic, optimize, ioOnly) {
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);


        const result = wasm.MchprsWorld_create_with_options(diplomatReceive.buffer, schematic.ffiValue, optimize, ioOnly);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new NucleationError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('NucleationError.' + cause.value, { cause });
            }
            return new MchprsWorld(diplomatRuntime.internalConstructor, diplomatRuntime.ptrRead(wasm, diplomatReceive.buffer), []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            diplomatReceive.free();
        }
    }

    /**
     * Create a simulation world with custom IO positions
     * (`custom_io_positions` is flat `[x,y,z, x,y,z, ...]`).
     */
    static createWithCustomIo(schematic, optimize, ioOnly, customIoPositions) {
        let functionCleanupArena = new diplomatRuntime.CleanupArena();

        const customIoPositionsSlice = functionCleanupArena.alloc(diplomatRuntime.DiplomatBuf.sliceWrapper(wasm, diplomatRuntime.DiplomatBuf.slice(wasm, customIoPositions, "i32")));
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);


        const result = wasm.MchprsWorld_create_with_custom_io(diplomatReceive.buffer, schematic.ffiValue, optimize, ioOnly, customIoPositionsSlice.ptr);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new NucleationError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('NucleationError.' + cause.value, { cause });
            }
            return new MchprsWorld(diplomatRuntime.internalConstructor, diplomatRuntime.ptrRead(wasm, diplomatReceive.buffer), []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            functionCleanupArena.free();

            diplomatReceive.free();
        }
    }

    /**
     * One-shot convenience (old ABI: `schematic_simulate_use_block`):
     * build a world from `schematic`, fire an `on_use_block` event per
     * triple in `events_xyz`, run `ticks` ticks, and return the simulated
     * schematic. Unlike the old ABI (which mutated in place), this returns
     * a new `Schematic`.
     */
    static simulateUseBlock(schematic, ticks, eventsXyz) {
        let functionCleanupArena = new diplomatRuntime.CleanupArena();

        const eventsXyzSlice = functionCleanupArena.alloc(diplomatRuntime.DiplomatBuf.sliceWrapper(wasm, diplomatRuntime.DiplomatBuf.slice(wasm, eventsXyz, "i32")));
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);


        const result = wasm.MchprsWorld_simulate_use_block(diplomatReceive.buffer, schematic.ffiValue, ticks, eventsXyzSlice.ptr);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new NucleationError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('NucleationError.' + cause.value, { cause });
            }
            return new Schematic(diplomatRuntime.internalConstructor, diplomatRuntime.ptrRead(wasm, diplomatReceive.buffer), []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            functionCleanupArena.free();

            diplomatReceive.free();
        }
    }

    /**
     * Advance the simulation by `ticks` ticks.
     */
    tick(ticks) {
    wasm.MchprsWorld_tick(this.ffiValue, ticks);

        try {}

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    /**
     * Flush pending changes from the compiler to the world.
     */
    flush() {
    wasm.MchprsWorld_flush(this.ffiValue);

        try {}

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    /**
     * Set the power state of a lever.
     */
    setLeverPower(x, y, z, powered) {
    wasm.MchprsWorld_set_lever_power(this.ffiValue, x, y, z, powered);

        try {}

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    /**
     * Get the power state of a lever.
     */
    getLeverPower(x, y, z) {

        const result = wasm.MchprsWorld_get_lever_power(this.ffiValue, x, y, z);

        try {
            return result;
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    /**
     * Whether a redstone lamp is lit at the given position.
     */
    isLit(x, y, z) {

        const result = wasm.MchprsWorld_is_lit(this.ffiValue, x, y, z);

        try {
            return result;
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    /**
     * Set the signal strength (0-15) at a custom IO position.
     */
    setSignalStrength(x, y, z, strength) {
    wasm.MchprsWorld_set_signal_strength(this.ffiValue, x, y, z, strength);

        try {}

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    /**
     * Get the signal strength (0-15) at a position.
     */
    getSignalStrength(x, y, z) {

        const result = wasm.MchprsWorld_get_signal_strength(this.ffiValue, x, y, z);

        try {
            return result;
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    /**
     * Simulate a right-click on a block (typically a lever).
     */
    onUseBlock(x, y, z) {
    wasm.MchprsWorld_on_use_block(this.ffiValue, x, y, z);

        try {}

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    /**
     * Sync the simulation state back to the internal schematic.
     */
    syncToSchematic() {
    wasm.MchprsWorld_sync_to_schematic(this.ffiValue);

        try {}

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    /**
     * A clone of the world's schematic.
     */
    getSchematic() {

        const result = wasm.MchprsWorld_get_schematic(this.ffiValue);

        try {
            return new Schematic(diplomatRuntime.internalConstructor, result, []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    /**
     * The redstone power level (0-15) at a position.
     */
    getRedstonePower(x, y, z) {

        const result = wasm.MchprsWorld_get_redstone_power(this.ffiValue, x, y, z);

        try {
            return result;
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    /**
     * Check for custom IO changes since the last check. Call before
     * `poll_custom_io_changes_json`.
     */
    checkCustomIoChanges() {
    wasm.MchprsWorld_check_custom_io_changes(this.ffiValue);

        try {}

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    /**
     * Queued custom IO changes as a JSON array
     * (`[{"x":..,"y":..,"z":..,"old_power":..,"new_power":..}, ...]`),
     * clearing the queue.
     */
    pollCustomIoChangesJson() {
        const write = new diplomatRuntime.DiplomatWriteBuf(wasm);

    wasm.MchprsWorld_poll_custom_io_changes_json(this.ffiValue, write.buffer);

        try {
            return write.readString8();
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            write.free();
        }
    }

    /**
     * Queued custom IO changes as JSON without clearing the queue.
     */
    peekCustomIoChangesJson() {
        const write = new diplomatRuntime.DiplomatWriteBuf(wasm);

    wasm.MchprsWorld_peek_custom_io_changes_json(this.ffiValue, write.buffer);

        try {
            return write.readString8();
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            write.free();
        }
    }

    /**
     * Clear all queued custom IO changes.
     */
    clearCustomIoChanges() {
    wasm.MchprsWorld_clear_custom_io_changes(this.ffiValue);

        try {}

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    /**
     * Extract the compiled (post-optimization) redstone logic graph.
     */
    exportGraph() {
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);


        const result = wasm.MchprsWorld_export_graph(diplomatReceive.buffer, this.ffiValue);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new NucleationError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('NucleationError.' + cause.value, { cause });
            }
            return new RedstoneGraph(diplomatRuntime.internalConstructor, diplomatRuntime.ptrRead(wasm, diplomatReceive.buffer), []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            diplomatReceive.free();
        }
    }

    /**
     * Extract the structural (pre-fold, as-built) redstone logic graph.
     */
    exportGraphStructural() {
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);


        const result = wasm.MchprsWorld_export_graph_structural(diplomatReceive.buffer, this.ffiValue);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new NucleationError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('NucleationError.' + cause.value, { cause });
            }
            return new RedstoneGraph(diplomatRuntime.internalConstructor, diplomatRuntime.ptrRead(wasm, diplomatReceive.buffer), []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            diplomatReceive.free();
        }
    }

    constructor(symbol, ptr, selfEdge) {
        return this.#internalConstructor(...arguments)
    }
}