// generated by diplomat-tool
import { MeshPhase } from "./MeshPhase.mjs"
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";



/**
 * Snapshot of a {@link MeshJob}'s progress.
 */
export class MeshProgress {
    #phase;
    get phase() {
        return this.#phase;
    }
    set phase(value){
        this.#phase = value;
    }
    #current;
    get current() {
        return this.#current;
    }
    set current(value){
        this.#current = value;
    }
    #total;
    get total() {
        return this.#total;
    }
    set total(value){
        this.#total = value;
    }
    /** @internal */
    static fromFields(structObj) {
        return new MeshProgress(structObj);
    }

    #internalConstructor(structObj) {
        if (typeof structObj !== "object") {
            throw new Error("MeshProgress's constructor takes an object of MeshProgress's fields.");
        }

        if ("phase" in structObj) {
            this.#phase = structObj.phase;
        } else {
            throw new Error("Missing required field phase.");
        }

        if ("current" in structObj) {
            this.#current = structObj.current;
        } else {
            throw new Error("Missing required field current.");
        }

        if ("total" in structObj) {
            this.#total = structObj.total;
        } else {
            throw new Error("Missing required field total.");
        }

        return this;
    }

    // Return this struct in FFI function friendly format.
    // Returns an array that can be expanded with spread syntax (...)
    _intoFFI(
        dst,
        functionCleanupArena,
        appendArrayMap
    ) {

        this._writeToArrayBuffer(wasm.memory.buffer, dst, functionCleanupArena, appendArrayMap);

        return dst;
    }

    static get _sizeBytes() {
        return 12;
    }

    /// Currently unused, we may want to use later on though:
    static get _sizeAlign() {
        return 4;
    }

    static _fromSuppliedValue(internalConstructor, obj) {
        if (internalConstructor !== diplomatRuntime.internalConstructor) {
            throw new Error("_fromSuppliedValue cannot be called externally.");
        }

        if (obj instanceof MeshProgress) {
            return obj;
        }

        return MeshProgress.fromFields(obj);
    }

    _writeToArrayBuffer(
        arrayBuffer,
        offset,
        functionCleanupArena,
        appendArrayMap
    ) {
        diplomatRuntime.writeToArrayBuffer(arrayBuffer, offset + 0, this.#phase.ffiValue, Int32Array);
        diplomatRuntime.writeToArrayBuffer(arrayBuffer, offset + 4, this.#current, Uint32Array);
        diplomatRuntime.writeToArrayBuffer(arrayBuffer, offset + 8, this.#total, Uint32Array);
    }

    // This struct contains borrowed fields, so this takes in a list of
    // "edges" corresponding to where each lifetime's data may have been borrowed from
    // and passes it down to individual fields containing the borrow.
    // This method does not attempt to handle any dependencies between lifetimes, the caller
    // should handle this when constructing edge arrays.
    static _fromFFI(internalConstructor, ptr) {
        if (internalConstructor !== diplomatRuntime.internalConstructor) {
            throw new Error("MeshProgress._fromFFI is not meant to be called externally. Please use the default constructor.");
        }
        let structObj = {};
        const phaseDeref = diplomatRuntime.enumDiscriminant(wasm, ptr);
        structObj.phase = new MeshPhase(diplomatRuntime.internalConstructor, phaseDeref);
        const currentDeref = (new Uint32Array(wasm.memory.buffer, ptr + 4, 1))[0];
        structObj.current = currentDeref;
        const totalDeref = (new Uint32Array(wasm.memory.buffer, ptr + 8, 1))[0];
        structObj.total = totalDeref;

        return new MeshProgress(structObj);
    }


    constructor(structObj) {
        return this.#internalConstructor(...arguments)
    }
}