// generated by diplomat-tool
import type { MeshPhase } from "./MeshPhase"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";

export type MeshProgress_obj = {
    phase: MeshPhase;
    current: number;
    total: number;
};



/**
 * Snapshot of a {@link MeshJob}'s progress.
 */
export class MeshProgress {
    get phase(): MeshPhase;
    set phase(value: MeshPhase);
    get current(): number;
    set current(value: number);
    get total(): number;
    set total(value: number);
    /** @internal */
    static fromFields(structObj : MeshProgress_obj) : MeshProgress;

    /**
    * Create `MeshProgress` from an object that contains all of `MeshProgress`s fields.
    * Optional fields do not need to be included in the provided object.
    */
    constructor(structObj: MeshProgress_obj);

}