// generated by diplomat-tool
import type { MeshBounds } from "./MeshBounds"
import type { MeshConfig } from "./MeshConfig"
import type { NucleationError } from "./NucleationError"
import type { ResourcePack } from "./ResourcePack"
import type { Schematic } from "./Schematic"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * A single mesh output. Wraps {@link crate::meshing::MeshResult}.
 */
export class MeshResult {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    /**
     * Mesh an entire schematic in one pass (old ABI: `schematic_to_mesh`).
     */
    static create(schematic: Schematic, pack: ResourcePack, config: MeshConfig): MeshResult;

    /**
     * Mesh a schematic with USDZ-compatible output (old ABI: `schematic_to_usdz`).
     */
    static createUsdz(schematic: Schematic, pack: ResourcePack, config: MeshConfig): MeshResult;

    /**
     * The mesh as a binary GLB, base64-encoded.
     */
    glbDataB64(): string;

    /**
     * The mesh serialized in the NUCM cache format, base64-encoded.
     */
    nucmDataB64(): string;

    vertexCount(): number;

    triangleCount(): number;

    hasTransparency(): boolean;

    bounds(): MeshBounds;
}