// generated by diplomat-tool
import type { NucleationError } from "./NucleationError"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * Mesh generation configuration. Wraps {@link crate::meshing::MeshConfig}.
 */
export class MeshConfig {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    static create(): MeshConfig;

    setCullHiddenFaces(val: boolean): void;

    cullHiddenFaces(): boolean;

    setAmbientOcclusion(val: boolean): void;

    ambientOcclusion(): boolean;

    setAoIntensity(val: number): void;

    aoIntensity(): number;

    /**
     * Set the biome used for tinting (e.g. "plains", "swamp").
     */
    setBiome(biome: string): void;

    /**
     * Clear the biome (old ABI: `meshconfig_set_biome(NULL)`).
     */
    clearBiome(): void;

    /**
     * The configured biome; `NotFound` if none is set.
     */
    biome(): string;

    setAtlasMaxSize(size: number): void;

    atlasMaxSize(): number;

    setCullOccludedBlocks(val: boolean): void;

    cullOccludedBlocks(): boolean;

    setGreedyMeshing(val: boolean): void;

    greedyMeshing(): boolean;
}