// generated by diplomat-tool
import type { MeshConfig } from "./MeshConfig"
import type { MeshResult } from "./MeshResult"
import type { NucleationError } from "./NucleationError"
import type { ResourcePack } from "./ResourcePack"
import type { Schematic } from "./Schematic"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * Per-region mesh results. Wraps {@link crate::meshing::MultiMeshResult}.
 */
export class MultiMeshResult {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    /**
     * Mesh each region separately (old ABI: `schematic_mesh_by_region`).
     */
    static create(schematic: Schematic, pack: ResourcePack, config: MeshConfig): MultiMeshResult;

    /**
     * Region names, as a JSON array string.
     */
    regionNamesJson(): string;

    /**
     * The mesh for one region (cloned).
     */
    getMesh(regionName: string): MeshResult;

    /**
     * Total vertex count across all region meshes.
     */
    totalVertexCount(): number;

    /**
     * Total triangle count across all region meshes.
     */
    totalTriangleCount(): number;

    /**
     * Number of region meshes.
     */
    meshCount(): number;
}