// generated by diplomat-tool
import type { MeshConfig } from "./MeshConfig"
import type { NucleationError } from "./NucleationError"
import type { ResourcePack } from "./ResourcePack"
import type { Schematic } from "./Schematic"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * Raw vertex streams for custom rendering. Wraps {@link crate::meshing::RawMeshExport}.
 */
export class RawMeshExport {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    /**
     * Export raw mesh data (old ABI: `schematic_to_raw_mesh`).
     */
    static create(schematic: Schematic, pack: ResourcePack, config: MeshConfig): RawMeshExport;

    vertexCount(): number;

    triangleCount(): number;

    /**
     * Flat `[x,y,z,...]` positions as little-endian `f32` bytes, base64-encoded.
     */
    positionsB64(): string;

    /**
     * Flat normals as little-endian `f32` bytes, base64-encoded.
     */
    normalsB64(): string;

    /**
     * Flat UVs as little-endian `f32` bytes, base64-encoded.
     */
    uvsB64(): string;

    /**
     * Flat vertex colors as little-endian `f32` bytes, base64-encoded.
     */
    colorsB64(): string;

    /**
     * Triangle indices as little-endian `u32` bytes, base64-encoded.
     */
    indicesB64(): string;

    /**
     * Raw RGBA texture pixels, base64-encoded.
     */
    textureRgbaB64(): string;

    textureWidth(): number;

    textureHeight(): number;
}