// generated by diplomat-tool
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";



/**
 * An inclusive block-coordinate box (a definition region is a union of
 * these).
 */
export class RegionBounds {
    #minX;
    get minX() {
        return this.#minX;
    }
    set minX(value){
        this.#minX = value;
    }
    #minY;
    get minY() {
        return this.#minY;
    }
    set minY(value){
        this.#minY = value;
    }
    #minZ;
    get minZ() {
        return this.#minZ;
    }
    set minZ(value){
        this.#minZ = value;
    }
    #maxX;
    get maxX() {
        return this.#maxX;
    }
    set maxX(value){
        this.#maxX = value;
    }
    #maxY;
    get maxY() {
        return this.#maxY;
    }
    set maxY(value){
        this.#maxY = value;
    }
    #maxZ;
    get maxZ() {
        return this.#maxZ;
    }
    set maxZ(value){
        this.#maxZ = value;
    }
    /** @internal */
    static fromFields(structObj) {
        return new RegionBounds(structObj);
    }

    #internalConstructor(structObj) {
        if (typeof structObj !== "object") {
            throw new Error("RegionBounds's constructor takes an object of RegionBounds's fields.");
        }

        if ("minX" in structObj) {
            this.#minX = structObj.minX;
        } else {
            throw new Error("Missing required field minX.");
        }

        if ("minY" in structObj) {
            this.#minY = structObj.minY;
        } else {
            throw new Error("Missing required field minY.");
        }

        if ("minZ" in structObj) {
            this.#minZ = structObj.minZ;
        } else {
            throw new Error("Missing required field minZ.");
        }

        if ("maxX" in structObj) {
            this.#maxX = structObj.maxX;
        } else {
            throw new Error("Missing required field maxX.");
        }

        if ("maxY" in structObj) {
            this.#maxY = structObj.maxY;
        } else {
            throw new Error("Missing required field maxY.");
        }

        if ("maxZ" in structObj) {
            this.#maxZ = structObj.maxZ;
        } else {
            throw new Error("Missing required field maxZ.");
        }

        return this;
    }

    // Return this struct in FFI function friendly format.
    // Returns an array that can be expanded with spread syntax (...)
    _intoFFI(
        dst,
        functionCleanupArena,
        appendArrayMap
    ) {

        this._writeToArrayBuffer(wasm.memory.buffer, dst, functionCleanupArena, appendArrayMap);

        return dst;
    }

    static get _sizeBytes() {
        return 24;
    }

    /// Currently unused, we may want to use later on though:
    static get _sizeAlign() {
        return 4;
    }

    static _fromSuppliedValue(internalConstructor, obj) {
        if (internalConstructor !== diplomatRuntime.internalConstructor) {
            throw new Error("_fromSuppliedValue cannot be called externally.");
        }

        if (obj instanceof RegionBounds) {
            return obj;
        }

        return RegionBounds.fromFields(obj);
    }

    _writeToArrayBuffer(
        arrayBuffer,
        offset,
        functionCleanupArena,
        appendArrayMap
    ) {
        diplomatRuntime.writeToArrayBuffer(arrayBuffer, offset + 0, this.#minX, Int32Array);
        diplomatRuntime.writeToArrayBuffer(arrayBuffer, offset + 4, this.#minY, Int32Array);
        diplomatRuntime.writeToArrayBuffer(arrayBuffer, offset + 8, this.#minZ, Int32Array);
        diplomatRuntime.writeToArrayBuffer(arrayBuffer, offset + 12, this.#maxX, Int32Array);
        diplomatRuntime.writeToArrayBuffer(arrayBuffer, offset + 16, this.#maxY, Int32Array);
        diplomatRuntime.writeToArrayBuffer(arrayBuffer, offset + 20, this.#maxZ, Int32Array);
    }

    // This struct contains borrowed fields, so this takes in a list of
    // "edges" corresponding to where each lifetime's data may have been borrowed from
    // and passes it down to individual fields containing the borrow.
    // This method does not attempt to handle any dependencies between lifetimes, the caller
    // should handle this when constructing edge arrays.
    static _fromFFI(internalConstructor, ptr) {
        if (internalConstructor !== diplomatRuntime.internalConstructor) {
            throw new Error("RegionBounds._fromFFI is not meant to be called externally. Please use the default constructor.");
        }
        let structObj = {};
        const minXDeref = (new Int32Array(wasm.memory.buffer, ptr, 1))[0];
        structObj.minX = minXDeref;
        const minYDeref = (new Int32Array(wasm.memory.buffer, ptr + 4, 1))[0];
        structObj.minY = minYDeref;
        const minZDeref = (new Int32Array(wasm.memory.buffer, ptr + 8, 1))[0];
        structObj.minZ = minZDeref;
        const maxXDeref = (new Int32Array(wasm.memory.buffer, ptr + 12, 1))[0];
        structObj.maxX = maxXDeref;
        const maxYDeref = (new Int32Array(wasm.memory.buffer, ptr + 16, 1))[0];
        structObj.maxY = maxYDeref;
        const maxZDeref = (new Int32Array(wasm.memory.buffer, ptr + 20, 1))[0];
        structObj.maxZ = maxZDeref;

        return new RegionBounds(structObj);
    }


    constructor(structObj) {
        return this.#internalConstructor(...arguments)
    }
}