// generated by diplomat-tool
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * Camera / output configuration for rendering.
 */
export class RenderConfig {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    static create(width: number, height: number): RenderConfig;

    setYaw(yaw: number): void;

    setPitch(pitch: number): void;

    setZoom(zoom: number): void;

    setFov(fov: number): void;

    /**
     * Set a solid RGBA clear color (linear 0.0–1.0). Alpha < 1.0 yields a
     * transparent PNG. Ignored when HDRI is enabled.
     */
    setBackground(r: number, g: number, b: number, a: number): void;

    /**
     * Clear the custom background — revert to default sky / HDRI.
     */
    clearBackground(): void;

    /**
     * Enable (`true`) or disable orthographic projection.
     */
    setOrthographic(orthographic: boolean): void;

    /**
     * Configure a true isometric view: orthographic at yaw 45° /
     * pitch ≈35.264° (preserves the current width/height).
     */
    setIsometric(): void;
}