// generated by diplomat-tool
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * Camera / output configuration for rendering.
 */
export class RenderConfig {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    /**
     * Create a config with the given output size in pixels. Camera starts
     * at the defaults: yaw 45°, pitch 30°, zoom 1.0, fov 45°, perspective
     * projection, default sky background.
     */
    static create(width: number, height: number): RenderConfig;

    /**
     * Set the camera yaw (horizontal orbit angle) in degrees. Default: 45.
     */
    setYaw(yaw: number): void;

    /**
     * Set the camera pitch (downward tilt) in degrees. Default: 30.
     */
    setPitch(pitch: number): void;

    /**
     * Set the zoom factor scaling the auto-fitted camera distance
     * (1.0 = frame the whole model; larger = further away). Default: 1.0.
     */
    setZoom(zoom: number): void;

    /**
     * Set the vertical field of view in degrees (perspective projection
     * only). Default: 45.
     */
    setFov(fov: number): void;

    /**
     * Set a solid RGBA clear color (linear 0.0–1.0). Alpha < 1.0 yields a
     * transparent PNG. Ignored when HDRI is enabled.
     */
    setBackground(r: number, g: number, b: number, a: number): void;

    /**
     * Clear the custom background — revert to default sky / HDRI.
     */
    clearBackground(): void;

    /**
     * Enable (`true`) or disable orthographic projection.
     */
    setOrthographic(orthographic: boolean): void;

    /**
     * Configure a true isometric view: orthographic at yaw 45° /
     * pitch ≈35.264° (preserves the current width/height).
     */
    setIsometric(): void;
}