// generated by diplomat-tool
import { NucleationError } from "./NucleationError.mjs"
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";

const RenderConfig_box_destroy_registry = new FinalizationRegistry((ptr) => {
    wasm.RenderConfig_destroy(ptr);
});

/**
 * Camera / output configuration for rendering.
 */
export class RenderConfig {
    // Internal ptr reference:
    #ptr = null;

    // Lifetimes are only to keep dependencies alive.
    // Since JS won't garbage collect until there are no incoming edges.
    #selfEdge = [];

    #internalConstructor(symbol, ptr, selfEdge) {
        if (symbol !== diplomatRuntime.internalConstructor) {
            console.error("RenderConfig is an Opaque type. You cannot call its constructor.");
            return;
        }
        this.#ptr = ptr;
        this.#selfEdge = selfEdge;

        // Are we being borrowed? If not, we can register.
        if (this.#selfEdge.length === 0) {
            RenderConfig_box_destroy_registry.register(this, this.#ptr);
        }

        return this;
    }
    /** @internal */
    get ffiValue() {
        return this.#ptr;
    }


    /**
     * Create a config with the given output size in pixels. Camera starts
     * at the defaults: yaw 45°, pitch 30°, zoom 1.0, fov 45°, perspective
     * projection, default sky background.
     */
    static create(width, height) {

        const result = wasm.RenderConfig_create(width, height);

        try {
            return new RenderConfig(diplomatRuntime.internalConstructor, result, []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    /**
     * Set the camera yaw (horizontal orbit angle) in degrees. Default: 45.
     */
    setYaw(yaw) {
    wasm.RenderConfig_set_yaw(this.ffiValue, yaw);

        try {}

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    /**
     * Set the camera pitch (downward tilt) in degrees. Default: 30.
     */
    setPitch(pitch) {
    wasm.RenderConfig_set_pitch(this.ffiValue, pitch);

        try {}

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    /**
     * Set the zoom factor applied to the auto-fitted framing
     * (1.0 = frame the whole model; 2.0 = twice as close; 0.5 = twice
     * as far). Default: 1.0.
     */
    setZoom(zoom) {
    wasm.RenderConfig_set_zoom(this.ffiValue, zoom);

        try {}

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    /**
     * Fit the camera to the model's bounding sphere instead of its
     * yaw-dependent silhouette. The sphere is rotation invariant, so
     * orbiting cameras (turntables) keep a constant distance instead
     * of pulsing as the silhouette changes. Frames slightly looser
     * than the default fit. Default: false.
     */
    setSphereFit(sphereFit) {
    wasm.RenderConfig_set_sphere_fit(this.ffiValue, sphereFit);

        try {}

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    /**
     * Set the vertical field of view in degrees (perspective projection
     * only). Default: 45.
     */
    setFov(fov) {
    wasm.RenderConfig_set_fov(this.ffiValue, fov);

        try {}

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    /**
     * Set the world-space directional light and its non-negative intensity.
     */
    setDirectionalLight(x, y, z, intensity) {
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);


        const result = wasm.RenderConfig_set_directional_light(diplomatReceive.buffer, this.ffiValue, x, y, z, intensity);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new NucleationError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('NucleationError.' + cause.value, { cause });
            }
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            diplomatReceive.free();
        }
    }

    /**
     * Set the unlit floor for non-HDRI rendering, in `0..=1`.
     */
    setAmbientLight(ambient) {
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);


        const result = wasm.RenderConfig_set_ambient_light(diplomatReceive.buffer, this.ffiValue, ambient);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new NucleationError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('NucleationError.' + cause.value, { cause });
            }
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            diplomatReceive.free();
        }
    }

    /**
     * Set a solid RGBA clear color (linear 0.0–1.0). Alpha < 1.0 yields a
     * transparent PNG. Ignored when HDRI is enabled.
     */
    setBackground(r, g, b, a) {
    wasm.RenderConfig_set_background(this.ffiValue, r, g, b, a);

        try {}

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    /**
     * Clear the custom background — revert to default sky / HDRI.
     */
    clearBackground() {
    wasm.RenderConfig_clear_background(this.ffiValue);

        try {}

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    /**
     * Configure a one-block world grid. Models are centred on integer
     * schematic coordinates, so grid lines are placed on half-integer
     * block boundaries automatically.
     */
    setGrid(halfExtent, spacing, planeY, showAxes, red, green, blue, alpha) {
    wasm.RenderConfig_set_grid(this.ffiValue, halfExtent, spacing, planeY, showAxes, red, green, blue, alpha);

        try {}

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    /**
     * Configure a compact grid fitted to half-integer block boundaries.
     */
    setFittedGrid(margin, spacing, planeY, showAxes, red, green, blue, alpha) {
    wasm.RenderConfig_set_fitted_grid(this.ffiValue, margin, spacing, planeY, showAxes, red, green, blue, alpha);

        try {}

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    clearGrid() {
    wasm.RenderConfig_clear_grid(this.ffiValue);

        try {}

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    /**
     * Enable (`true`) or disable orthographic projection.
     */
    setOrthographic(orthographic) {
    wasm.RenderConfig_set_orthographic(this.ffiValue, orthographic);

        try {}

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    /**
     * Configure a true isometric view: orthographic at yaw 45° /
     * pitch ≈35.264° (preserves the current width/height).
     */
    setIsometric() {
    wasm.RenderConfig_set_isometric(this.ffiValue);

        try {}

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    constructor(symbol, ptr, selfEdge) {
        return this.#internalConstructor(...arguments)
    }
}