// generated by diplomat-tool
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * Ordered list of raw resource-pack ZIP buffers, lowest priority first.
 * Feed it to {@link ResourcePack::from_list}.
 */
export class ResourcePackList {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    /**
     * Create an empty resource-pack list.
     */
    static create(): ResourcePackList;

    /**
     * Append one resource-pack ZIP buffer. Later buffers overlay earlier
     * ones on per-key collision (Minecraft pack-ordering semantics).
     */
    add(data: Array<number>): void;

    /**
     * Number of pack buffers added so far.
     */
    len(): number;
}