// generated by diplomat-tool
import type { NucleationError } from "./NucleationError"
import type { Schematic } from "./Schematic"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * Namespace for the script-runner free functions of the old ABI
 * (`run_lua_script`, `run_js_script`, `run_script`).
 */
export class Scripting {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    /**
     * Run a Lua script file. Returns the schematic the script assigns to
     * `result`; `NotFound` if it produced none, `Parse` if it failed, and
     * `InvalidArgument` when built without the `scripting-lua` feature.
     */
    static runLuaScript(path: string): Schematic;

    /**
     * Run a JS script file. Returns the schematic the script assigns to
     * `result`; `NotFound` if it produced none, `Parse` if it failed, and
     * `InvalidArgument` when built without the `scripting-js` feature.
     */
    static runJsScript(path: string): Schematic;

    /**
     * Run a script file, auto-detecting the engine by extension (`.lua` or
     * `.js`). Returns the schematic the script assigns to `result`; `NotFound`
     * if it produced none, `Parse` if it failed (including unsupported
     * extensions).
     */
    static runScript(path: string): Schematic;
}