// generated by diplomat-tool
import { NucleationError } from "./NucleationError.mjs"
import { Schematic } from "./Schematic.mjs"
import { SdfAxis } from "./SdfAxis.mjs"
import { SdfBounds } from "./SdfBounds.mjs"
import { SdfCellMode } from "./SdfCellMode.mjs"
import { SdfNormal } from "./SdfNormal.mjs"
import { Shape } from "./Shape.mjs"
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";

const Sdf_box_destroy_registry = new FinalizationRegistry((ptr) => {
    wasm.Sdf_destroy(ptr);
});

/**
 * An immutable, composable signed-distance-field expression graph.
 *
 * Primitive constructors and every combinator return a new graph, so values
 * can be shared safely between Flow nodes and across Kotlin/Java, JavaScript,
 * and Python bindings. JSON is retained only for explicit import/export and
 * the legacy sampling helpers.
 */
export class Sdf {
    // Internal ptr reference:
    #ptr = null;

    // Lifetimes are only to keep dependencies alive.
    // Since JS won't garbage collect until there are no incoming edges.
    #selfEdge = [];

    #internalConstructor(symbol, ptr, selfEdge) {
        if (symbol !== diplomatRuntime.internalConstructor) {
            console.error("Sdf is an Opaque type. You cannot call its constructor.");
            return;
        }
        this.#ptr = ptr;
        this.#selfEdge = selfEdge;

        // Are we being borrowed? If not, we can register.
        if (this.#selfEdge.length === 0) {
            Sdf_box_destroy_registry.register(this, this.#ptr);
        }

        return this;
    }
    /** @internal */
    get ffiValue() {
        return this.#ptr;
    }


    static sphere(radius) {
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);


        const result = wasm.Sdf_sphere(diplomatReceive.buffer, radius);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new NucleationError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('NucleationError.' + cause.value, { cause });
            }
            return new Sdf(diplomatRuntime.internalConstructor, diplomatRuntime.ptrRead(wasm, diplomatReceive.buffer), []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            diplomatReceive.free();
        }
    }

    /**
     * Axis-aligned rounded box, centered at the origin.
     */
    static boxShape(halfX, halfY, halfZ, rounding) {
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);


        const result = wasm.Sdf_box_shape(diplomatReceive.buffer, halfX, halfY, halfZ, rounding);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new NucleationError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('NucleationError.' + cause.value, { cause });
            }
            return new Sdf(diplomatRuntime.internalConstructor, diplomatRuntime.ptrRead(wasm, diplomatReceive.buffer), []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            diplomatReceive.free();
        }
    }

    static ellipsoid(radiusX, radiusY, radiusZ) {
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);


        const result = wasm.Sdf_ellipsoid(diplomatReceive.buffer, radiusX, radiusY, radiusZ);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new NucleationError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('NucleationError.' + cause.value, { cause });
            }
            return new Sdf(diplomatRuntime.internalConstructor, diplomatRuntime.ptrRead(wasm, diplomatReceive.buffer), []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            diplomatReceive.free();
        }
    }

    static torus(majorRadius, minorRadius) {
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);


        const result = wasm.Sdf_torus(diplomatReceive.buffer, majorRadius, minorRadius);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new NucleationError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('NucleationError.' + cause.value, { cause });
            }
            return new Sdf(diplomatRuntime.internalConstructor, diplomatRuntime.ptrRead(wasm, diplomatReceive.buffer), []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            diplomatReceive.free();
        }
    }

    static capsule(ax, ay, az, bx, by, bz, radius) {
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);


        const result = wasm.Sdf_capsule(diplomatReceive.buffer, ax, ay, az, bx, by, bz, radius);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new NucleationError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('NucleationError.' + cause.value, { cause });
            }
            return new Sdf(diplomatRuntime.internalConstructor, diplomatRuntime.ptrRead(wasm, diplomatReceive.buffer), []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            diplomatReceive.free();
        }
    }

    static cappedCylinder(radius, halfHeight) {
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);


        const result = wasm.Sdf_capped_cylinder(diplomatReceive.buffer, radius, halfHeight);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new NucleationError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('NucleationError.' + cause.value, { cause });
            }
            return new Sdf(diplomatRuntime.internalConstructor, diplomatRuntime.ptrRead(wasm, diplomatReceive.buffer), []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            diplomatReceive.free();
        }
    }

    static cappedCone(halfHeight, bottomRadius, topRadius) {
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);


        const result = wasm.Sdf_capped_cone(diplomatReceive.buffer, halfHeight, bottomRadius, topRadius);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new NucleationError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('NucleationError.' + cause.value, { cause });
            }
            return new Sdf(diplomatRuntime.internalConstructor, diplomatRuntime.ptrRead(wasm, diplomatReceive.buffer), []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            diplomatReceive.free();
        }
    }

    static plane(normalX, normalY, normalZ, offset) {
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);


        const result = wasm.Sdf_plane(diplomatReceive.buffer, normalX, normalY, normalZ, offset);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new NucleationError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('NucleationError.' + cause.value, { cause });
            }
            return new Sdf(diplomatRuntime.internalConstructor, diplomatRuntime.ptrRead(wasm, diplomatReceive.buffer), []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            diplomatReceive.free();
        }
    }

    static octahedron(size) {
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);


        const result = wasm.Sdf_octahedron(diplomatReceive.buffer, size);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new NucleationError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('NucleationError.' + cause.value, { cause });
            }
            return new Sdf(diplomatRuntime.internalConstructor, diplomatRuntime.ptrRead(wasm, diplomatReceive.buffer), []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            diplomatReceive.free();
        }
    }

    static hexPrism(radius, halfHeight) {
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);


        const result = wasm.Sdf_hex_prism(diplomatReceive.buffer, radius, halfHeight);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new NucleationError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('NucleationError.' + cause.value, { cause });
            }
            return new Sdf(diplomatRuntime.internalConstructor, diplomatRuntime.ptrRead(wasm, diplomatReceive.buffer), []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            diplomatReceive.free();
        }
    }

    static superPrism(halfX, halfY, halfZ, exponent) {
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);


        const result = wasm.Sdf_super_prism(diplomatReceive.buffer, halfX, halfY, halfZ, exponent);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new NucleationError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('NucleationError.' + cause.value, { cause });
            }
            return new Sdf(diplomatRuntime.internalConstructor, diplomatRuntime.ptrRead(wasm, diplomatReceive.buffer), []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            diplomatReceive.free();
        }
    }

    static cells(frequency, seed, jitter, mode, threshold) {
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);


        const result = wasm.Sdf_cells(diplomatReceive.buffer, frequency, seed, jitter, mode.ffiValue, threshold);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new NucleationError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('NucleationError.' + cause.value, { cause });
            }
            return new Sdf(diplomatRuntime.internalConstructor, diplomatRuntime.ptrRead(wasm, diplomatReceive.buffer), []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            diplomatReceive.free();
        }
    }

    unionWith(other) {

        const result = wasm.Sdf_union_with(this.ffiValue, other.ffiValue);

        try {
            return new Sdf(diplomatRuntime.internalConstructor, result, []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    intersectionWith(other) {

        const result = wasm.Sdf_intersection_with(this.ffiValue, other.ffiValue);

        try {
            return new Sdf(diplomatRuntime.internalConstructor, result, []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    subtract(other) {

        const result = wasm.Sdf_subtract(this.ffiValue, other.ffiValue);

        try {
            return new Sdf(diplomatRuntime.internalConstructor, result, []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    smoothUnion(other, radius) {
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);


        const result = wasm.Sdf_smooth_union(diplomatReceive.buffer, this.ffiValue, other.ffiValue, radius);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new NucleationError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('NucleationError.' + cause.value, { cause });
            }
            return new Sdf(diplomatRuntime.internalConstructor, diplomatRuntime.ptrRead(wasm, diplomatReceive.buffer), []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            diplomatReceive.free();
        }
    }

    smoothSubtract(other, radius) {
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);


        const result = wasm.Sdf_smooth_subtract(diplomatReceive.buffer, this.ffiValue, other.ffiValue, radius);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new NucleationError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('NucleationError.' + cause.value, { cause });
            }
            return new Sdf(diplomatRuntime.internalConstructor, diplomatRuntime.ptrRead(wasm, diplomatReceive.buffer), []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            diplomatReceive.free();
        }
    }

    smoothIntersection(other, radius) {
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);


        const result = wasm.Sdf_smooth_intersection(diplomatReceive.buffer, this.ffiValue, other.ffiValue, radius);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new NucleationError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('NucleationError.' + cause.value, { cause });
            }
            return new Sdf(diplomatRuntime.internalConstructor, diplomatRuntime.ptrRead(wasm, diplomatReceive.buffer), []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            diplomatReceive.free();
        }
    }

    rounded(radius) {
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);


        const result = wasm.Sdf_rounded(diplomatReceive.buffer, this.ffiValue, radius);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new NucleationError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('NucleationError.' + cause.value, { cause });
            }
            return new Sdf(diplomatRuntime.internalConstructor, diplomatRuntime.ptrRead(wasm, diplomatReceive.buffer), []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            diplomatReceive.free();
        }
    }

    shell(thickness) {
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);


        const result = wasm.Sdf_shell(diplomatReceive.buffer, this.ffiValue, thickness);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new NucleationError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('NucleationError.' + cause.value, { cause });
            }
            return new Sdf(diplomatRuntime.internalConstructor, diplomatRuntime.ptrRead(wasm, diplomatReceive.buffer), []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            diplomatReceive.free();
        }
    }

    translate(x, y, z) {
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);


        const result = wasm.Sdf_translate(diplomatReceive.buffer, this.ffiValue, x, y, z);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new NucleationError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('NucleationError.' + cause.value, { cause });
            }
            return new Sdf(diplomatRuntime.internalConstructor, diplomatRuntime.ptrRead(wasm, diplomatReceive.buffer), []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            diplomatReceive.free();
        }
    }

    rotate(xDegrees, yDegrees, zDegrees) {
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);


        const result = wasm.Sdf_rotate(diplomatReceive.buffer, this.ffiValue, xDegrees, yDegrees, zDegrees);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new NucleationError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('NucleationError.' + cause.value, { cause });
            }
            return new Sdf(diplomatRuntime.internalConstructor, diplomatRuntime.ptrRead(wasm, diplomatReceive.buffer), []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            diplomatReceive.free();
        }
    }

    scale(factor) {
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);


        const result = wasm.Sdf_scale(diplomatReceive.buffer, this.ffiValue, factor);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new NucleationError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('NucleationError.' + cause.value, { cause });
            }
            return new Sdf(diplomatRuntime.internalConstructor, diplomatRuntime.ptrRead(wasm, diplomatReceive.buffer), []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            diplomatReceive.free();
        }
    }

    mirror(axis) {

        const result = wasm.Sdf_mirror(this.ffiValue, axis.ffiValue);

        try {
            return new Sdf(diplomatRuntime.internalConstructor, result, []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    repeatInfinite(spacingX, spacingY, spacingZ) {
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);


        const result = wasm.Sdf_repeat_infinite(diplomatReceive.buffer, this.ffiValue, spacingX, spacingY, spacingZ);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new NucleationError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('NucleationError.' + cause.value, { cause });
            }
            return new Sdf(diplomatRuntime.internalConstructor, diplomatRuntime.ptrRead(wasm, diplomatReceive.buffer), []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            diplomatReceive.free();
        }
    }

    repeatCounted(spacingX, spacingY, spacingZ, countX, countY, countZ) {
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);


        const result = wasm.Sdf_repeat_counted(diplomatReceive.buffer, this.ffiValue, spacingX, spacingY, spacingZ, countX, countY, countZ);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new NucleationError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('NucleationError.' + cause.value, { cause });
            }
            return new Sdf(diplomatRuntime.internalConstructor, diplomatRuntime.ptrRead(wasm, diplomatReceive.buffer), []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            diplomatReceive.free();
        }
    }

    displace(amplitude, frequency, seed, octaves) {
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);


        const result = wasm.Sdf_displace(diplomatReceive.buffer, this.ffiValue, amplitude, frequency, seed, octaves);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new NucleationError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('NucleationError.' + cause.value, { cause });
            }
            return new Sdf(diplomatRuntime.internalConstructor, diplomatRuntime.ptrRead(wasm, diplomatReceive.buffer), []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            diplomatReceive.free();
        }
    }

    warp(amplitude, frequency, seed) {
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);


        const result = wasm.Sdf_warp(diplomatReceive.buffer, this.ffiValue, amplitude, frequency, seed);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new NucleationError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('NucleationError.' + cause.value, { cause });
            }
            return new Sdf(diplomatRuntime.internalConstructor, diplomatRuntime.ptrRead(wasm, diplomatReceive.buffer), []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            diplomatReceive.free();
        }
    }

    evalAt(x, y, z) {

        const result = wasm.Sdf_eval_at(this.ffiValue, x, y, z);

        try {
            return result;
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    normal(x, y, z, epsilon) {
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 13, 4, true);


        const result = wasm.Sdf_normal(diplomatReceive.buffer, this.ffiValue, x, y, z, epsilon);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new NucleationError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('NucleationError.' + cause.value, { cause });
            }
            return SdfNormal._fromFFI(diplomatRuntime.internalConstructor, diplomatReceive.buffer);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            diplomatReceive.free();
        }
    }

    bounds() {
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 25, 4, true);


        const result = wasm.Sdf_bounds(diplomatReceive.buffer, this.ffiValue);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new NucleationError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('NucleationError.' + cause.value, { cause });
            }
            return SdfBounds._fromFFI(diplomatRuntime.internalConstructor, diplomatReceive.buffer);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            diplomatReceive.free();
        }
    }

    toShape() {
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);


        const result = wasm.Sdf_to_shape(diplomatReceive.buffer, this.ffiValue);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new NucleationError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('NucleationError.' + cause.value, { cause });
            }
            return new Shape(diplomatRuntime.internalConstructor, diplomatRuntime.ptrRead(wasm, diplomatReceive.buffer), []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            diplomatReceive.free();
        }
    }

    toShapeBounded(minX, minY, minZ, maxX, maxY, maxZ) {
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);


        const result = wasm.Sdf_to_shape_bounded(diplomatReceive.buffer, this.ffiValue, minX, minY, minZ, maxX, maxY, maxZ);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new NucleationError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('NucleationError.' + cause.value, { cause });
            }
            return new Shape(diplomatRuntime.internalConstructor, diplomatRuntime.ptrRead(wasm, diplomatReceive.buffer), []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            diplomatReceive.free();
        }
    }

    static fromJsonString(json) {
        let functionCleanupArena = new diplomatRuntime.CleanupArena();

        const jsonSlice = functionCleanupArena.alloc(diplomatRuntime.DiplomatBuf.sliceWrapper(wasm, diplomatRuntime.DiplomatBuf.str8(wasm, json)));
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);


        const result = wasm.Sdf_from_json_string(diplomatReceive.buffer, jsonSlice.ptr);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new NucleationError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('NucleationError.' + cause.value, { cause });
            }
            return new Sdf(diplomatRuntime.internalConstructor, diplomatRuntime.ptrRead(wasm, diplomatReceive.buffer), []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            functionCleanupArena.free();

            diplomatReceive.free();
        }
    }

    toJson() {
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);

        const write = new diplomatRuntime.DiplomatWriteBuf(wasm);


        const result = wasm.Sdf_to_json(diplomatReceive.buffer, this.ffiValue, write.buffer);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new NucleationError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('NucleationError.' + cause.value, { cause });
            }
            return write.readString8();
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            diplomatReceive.free();
            write.free();
        }
    }

    /**
     * Legacy JSON-first terrain helper. Prefer typed constructors and
     * `to_shape()` with `BuildingTool.fill()` for new code.
     */
    static schematicFromSdfAuto(sdfJson, rulesJson) {
        let functionCleanupArena = new diplomatRuntime.CleanupArena();

        const sdfJsonSlice = functionCleanupArena.alloc(diplomatRuntime.DiplomatBuf.sliceWrapper(wasm, diplomatRuntime.DiplomatBuf.str8(wasm, sdfJson)));
        const rulesJsonSlice = functionCleanupArena.alloc(diplomatRuntime.DiplomatBuf.sliceWrapper(wasm, diplomatRuntime.DiplomatBuf.str8(wasm, rulesJson)));
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);


        const result = wasm.Sdf_schematic_from_sdf_auto(diplomatReceive.buffer, sdfJsonSlice.ptr, rulesJsonSlice.ptr);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new NucleationError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('NucleationError.' + cause.value, { cause });
            }
            return new Schematic(diplomatRuntime.internalConstructor, diplomatRuntime.ptrRead(wasm, diplomatReceive.buffer), []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            functionCleanupArena.free();

            diplomatReceive.free();
        }
    }

    /**
     * Legacy JSON-first terrain helper with optional explicit bounds.
     */
    static schematicFromSdf(sdfJson, rulesJson, hasBounds, minX, minY, minZ, maxX, maxY, maxZ) {
        let functionCleanupArena = new diplomatRuntime.CleanupArena();

        const sdfJsonSlice = functionCleanupArena.alloc(diplomatRuntime.DiplomatBuf.sliceWrapper(wasm, diplomatRuntime.DiplomatBuf.str8(wasm, sdfJson)));
        const rulesJsonSlice = functionCleanupArena.alloc(diplomatRuntime.DiplomatBuf.sliceWrapper(wasm, diplomatRuntime.DiplomatBuf.str8(wasm, rulesJson)));
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);


        const result = wasm.Sdf_schematic_from_sdf(diplomatReceive.buffer, sdfJsonSlice.ptr, rulesJsonSlice.ptr, hasBounds, minX, minY, minZ, maxX, maxY, maxZ);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new NucleationError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('NucleationError.' + cause.value, { cause });
            }
            return new Schematic(diplomatRuntime.internalConstructor, diplomatRuntime.ptrRead(wasm, diplomatReceive.buffer), []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            functionCleanupArena.free();

            diplomatReceive.free();
        }
    }

    /**
     * Legacy JSON-first evaluator. Prefer `Sdf.from_json_string(...).eval_at(...)`.
     */
    static eval(sdfJson, x, y, z) {
        let functionCleanupArena = new diplomatRuntime.CleanupArena();

        const sdfJsonSlice = functionCleanupArena.alloc(diplomatRuntime.DiplomatBuf.sliceWrapper(wasm, diplomatRuntime.DiplomatBuf.str8(wasm, sdfJson)));
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);


        const result = wasm.Sdf_eval(diplomatReceive.buffer, sdfJsonSlice.ptr, x, y, z);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new NucleationError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('NucleationError.' + cause.value, { cause });
            }
            return (new Float32Array(wasm.memory.buffer, diplomatReceive.buffer, 1))[0];
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            functionCleanupArena.free();

            diplomatReceive.free();
        }
    }

    constructor(symbol, ptr, selfEdge) {
        return this.#internalConstructor(...arguments)
    }
}