// generated by diplomat-tool
import { NucleationError } from "./NucleationError.mjs"
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";

const SortStrategy_box_destroy_registry = new FinalizationRegistry((ptr) => {
    wasm.SortStrategy_destroy(ptr);
});

/**
 * Ordering applied to region positions before bit assignment
 * (PORTING rule 10).
 */
export class SortStrategy {
    // Internal ptr reference:
    #ptr = null;

    // Lifetimes are only to keep dependencies alive.
    // Since JS won't garbage collect until there are no incoming edges.
    #selfEdge = [];

    #internalConstructor(symbol, ptr, selfEdge) {
        if (symbol !== diplomatRuntime.internalConstructor) {
            console.error("SortStrategy is an Opaque type. You cannot call its constructor.");
            return;
        }
        this.#ptr = ptr;
        this.#selfEdge = selfEdge;

        // Are we being borrowed? If not, we can register.
        if (this.#selfEdge.length === 0) {
            SortStrategy_box_destroy_registry.register(this, this.#ptr);
        }

        return this;
    }
    /** @internal */
    get ffiValue() {
        return this.#ptr;
    }


    /**
     * Sort by Y ascending, then X, then Z (default Minecraft layer
     * order). The first position after sorting is bit 0 (LSB).
     */
    static yxz() {

        const result = wasm.SortStrategy_yxz();

        try {
            return new SortStrategy(diplomatRuntime.internalConstructor, result, []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    /**
     * Sort by X ascending, then Y, then Z.
     */
    static xyz() {

        const result = wasm.SortStrategy_xyz();

        try {
            return new SortStrategy(diplomatRuntime.internalConstructor, result, []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    /**
     * Sort by Z ascending, then Y, then X.
     */
    static zyx() {

        const result = wasm.SortStrategy_zyx();

        try {
            return new SortStrategy(diplomatRuntime.internalConstructor, result, []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    /**
     * Sort by Y descending, then X ascending, then Z ascending.
     */
    static yDescXz() {

        const result = wasm.SortStrategy_y_desc_xz();

        try {
            return new SortStrategy(diplomatRuntime.internalConstructor, result, []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    /**
     * Sort by X descending, then Y ascending, then Z ascending.
     */
    static xDescYz() {

        const result = wasm.SortStrategy_x_desc_yz();

        try {
            return new SortStrategy(diplomatRuntime.internalConstructor, result, []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    /**
     * Sort by Z descending, then Y ascending, then X ascending.
     */
    static zDescYx() {

        const result = wasm.SortStrategy_z_desc_yx();

        try {
            return new SortStrategy(diplomatRuntime.internalConstructor, result, []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    /**
     * Old ABI name: `sort_strategy_descending`.
     */
    static descending() {

        const result = wasm.SortStrategy_descending();

        try {
            return new SortStrategy(diplomatRuntime.internalConstructor, result, []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    /**
     * Sort by Euclidean distance from the reference point, closest
     * first (ties broken by Y, X, Z ascending).
     */
    static distanceFrom(x, y, z) {

        const result = wasm.SortStrategy_distance_from(x, y, z);

        try {
            return new SortStrategy(diplomatRuntime.internalConstructor, result, []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    /**
     * Sort by Euclidean distance from the reference point, farthest
     * first (ties broken by Y, X, Z descending).
     */
    static distanceFromDesc(x, y, z) {

        const result = wasm.SortStrategy_distance_from_desc(x, y, z);

        try {
            return new SortStrategy(diplomatRuntime.internalConstructor, result, []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    /**
     * Keep positions in the order they were added (no sorting). Useful
     * when positions were ordered manually or box order matters.
     */
    static preserve() {

        const result = wasm.SortStrategy_preserve();

        try {
            return new SortStrategy(diplomatRuntime.internalConstructor, result, []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    /**
     * Reverse of the order positions were added.
     */
    static reverse() {

        const result = wasm.SortStrategy_reverse();

        try {
            return new SortStrategy(diplomatRuntime.internalConstructor, result, []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    /**
     * Parse from a name (e.g. "yxz", "descending", "preserve").
     */
    static fromString(s) {
        let functionCleanupArena = new diplomatRuntime.CleanupArena();

        const sSlice = functionCleanupArena.alloc(diplomatRuntime.DiplomatBuf.sliceWrapper(wasm, diplomatRuntime.DiplomatBuf.str8(wasm, s)));
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);


        const result = wasm.SortStrategy_from_string(diplomatReceive.buffer, sSlice.ptr);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new NucleationError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('NucleationError.' + cause.value, { cause });
            }
            return new SortStrategy(diplomatRuntime.internalConstructor, diplomatRuntime.ptrRead(wasm, diplomatReceive.buffer), []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            functionCleanupArena.free();

            diplomatReceive.free();
        }
    }

    /**
     * The strategy name.
     */
    name() {
        const write = new diplomatRuntime.DiplomatWriteBuf(wasm);

    wasm.SortStrategy_name(this.ffiValue, write.buffer);

        try {
            return write.readString8();
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            write.free();
        }
    }

    constructor(symbol, ptr, selfEdge) {
        return this.#internalConstructor(...arguments)
    }
}