// generated by diplomat-tool
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";

export type TextureInfo_obj = {
    width: number;
    height: number;
    animated: boolean;
    frameCount: number;
};



/**
 * Texture size/animation metadata for one texture in a resource pack.
 */
export class TextureInfo {
    get width(): number;
    set width(value: number);
    get height(): number;
    set height(value: number);
    get animated(): boolean;
    set animated(value: boolean);
    get frameCount(): number;
    set frameCount(value: number);
    /** @internal */
    static fromFields(structObj : TextureInfo_obj) : TextureInfo;

    /**
    * Create `TextureInfo` from an object that contains all of `TextureInfo`s fields.
    * Optional fields do not need to be included in the provided object.
    */
    constructor(structObj: TextureInfo_obj);

}