// generated by diplomat-tool
import type { MeshConfig } from "./MeshConfig"
import type { NucleationError } from "./NucleationError"
import type { ResourcePack } from "./ResourcePack"
import type { Schematic } from "./Schematic"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * A packed texture atlas. Wraps {@link schematic_mesher::TextureAtlas}.
 */
export class TextureAtlas {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    /**
     * Build a single shared atlas from every unique block state in the
     * schematic (old ABI: `schematic_build_global_atlas`).
     */
    static buildGlobal(schematic: Schematic, pack: ResourcePack, config: MeshConfig): TextureAtlas;

    /**
     * Atlas width in pixels.
     */
    width(): number;

    /**
     * Atlas height in pixels.
     */
    height(): number;

    /**
     * Raw RGBA atlas pixels, base64-encoded.
     */
    rgbaDataB64(): string;
}