// generated by diplomat-tool
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";



/**
 * How the loaded structure is settled before tick 0.
 */
export class TickSettleMode {
    #value = undefined;

    static #values = new Map([
        ["Placement", 0],
        ["Quiet", 1],
        ["InWorld", 2]
    ]);

    static getAllEntries() {
        return TickSettleMode.#values.entries();
    }

    #internalConstructor(value) {
        if (arguments.length > 1 && arguments[0] === diplomatRuntime.internalConstructor) {
            // We pass in two internalConstructor arguments to create *new*
            // instances of this type, otherwise the enums are treated as singletons.
            if (arguments[1] === diplomatRuntime.internalConstructor ) {
                this.#value = arguments[2];
                return this;
            }
            return TickSettleMode.#objectValues[arguments[1]];
        }

        if (value instanceof TickSettleMode) {
            return value;
        }

        let intVal = TickSettleMode.#values.get(value);

        // Nullish check, checks for null or undefined
        if (intVal != null) {
            return TickSettleMode.#objectValues[intVal];
        }

        throw TypeError(value + " is not a TickSettleMode and does not correspond to any of its enumerator values.");
    }

    /** @internal */
    static fromValue(value) {
        return new TickSettleMode(value);
    }

    get value(){
        return [...TickSettleMode.#values.keys()][this.#value];
    }

    /** @internal */
    get ffiValue(){
        return this.#value;
    }
    static #objectValues = [
        new TickSettleMode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 0),
        new TickSettleMode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 1),
        new TickSettleMode(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 2),
    ];

    /**
     * Vanilla placement pass + ordered settle — a build saved at rest.
     */
    static Placement = TickSettleMode.#objectValues[0];
    /**
     * `onPlace` only, no settle — a knownShape capture.
     */
    static Quiet = TickSettleMode.#objectValues[1];
    /**
     * Neither — a build recorded mid-state in the world it stood in.
     */
    static InWorld = TickSettleMode.#objectValues[2];


    constructor(value) {
        return this.#internalConstructor(...arguments)
    }
}