// generated by diplomat-tool
import type { NucleationError } from "./NucleationError"
import type { Palette } from "./Palette"
import type { Schematic } from "./Schematic"
import type { Shape } from "./Shape"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * Namespace for the mesh-voxelization entry points (GLB/OBJ → shapes
 * and textured schematics).
 */
export class Voxelizer {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    /**
     * Load a binary glTF (`.glb`, embedded buffers/images) and voxelize
     * it into a fillable Shape: the model is uniformly scaled so its
     * largest dimension equals `target_size` voxels, centered on x/z
     * with its base resting at y = 0. Solidity is a parity test at each
     * voxel center (robust on closed meshes; open meshes are
     * best-effort). Errors with `Parse` on malformed/triangle-less GLB
     * and `InvalidArgument` on a non-positive `target_size`.
     */
    static shapeFromGlb(data: Array<number>, targetSize: number): Shape;

    /**
     * Load a Wavefront OBJ (`v`/`vt`/`f` lines; polygon faces are
     * fan-triangulated, negative indices supported, materials ignored)
     * and voxelize it into a fillable Shape, fitted exactly like
     * `shape_from_glb`. Errors with `Parse` on malformed/triangle-less
     * OBJ and `InvalidArgument` on invalid UTF-8 or a non-positive
     * `target_size`.
     */
    static shapeFromObj(text: string, targetSize: number): Shape;

    /**
     * Load a binary glTF and voxelize it directly into a textured
     * schematic named `name`: every solid voxel becomes the `palette`
     * block closest to its nearest-surface texture color (interior
     * voxels inherit the nearest surface color; voxels without texture
     * info snap to mid-gray). Errors with `Parse` on malformed GLB and
     * `InvalidArgument` on invalid UTF-8 or a non-positive
     * `target_size`.
     */
    static schematicFromGlbTextured(data: Array<number>, targetSize: number, palette: Palette, name: string): Schematic;
}