// generated by diplomat-tool
import { NucleationError } from "./NucleationError.mjs"
import { Palette } from "./Palette.mjs"
import { Schematic } from "./Schematic.mjs"
import { Shape } from "./Shape.mjs"
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";

const Voxelizer_box_destroy_registry = new FinalizationRegistry((ptr) => {
    wasm.Voxelizer_destroy(ptr);
});

/**
 * Namespace for the mesh-voxelization entry points (GLB/OBJ → shapes
 * and textured schematics).
 */
export class Voxelizer {
    // Internal ptr reference:
    #ptr = null;

    // Lifetimes are only to keep dependencies alive.
    // Since JS won't garbage collect until there are no incoming edges.
    #selfEdge = [];

    #internalConstructor(symbol, ptr, selfEdge) {
        if (symbol !== diplomatRuntime.internalConstructor) {
            console.error("Voxelizer is an Opaque type. You cannot call its constructor.");
            return;
        }
        this.#ptr = ptr;
        this.#selfEdge = selfEdge;

        // Are we being borrowed? If not, we can register.
        if (this.#selfEdge.length === 0) {
            Voxelizer_box_destroy_registry.register(this, this.#ptr);
        }

        return this;
    }
    /** @internal */
    get ffiValue() {
        return this.#ptr;
    }


    /**
     * Load a binary glTF (`.glb`, embedded buffers/images) and voxelize
     * it into a fillable Shape: the model is uniformly scaled so its
     * largest dimension equals `target_size` voxels, centered on x/z
     * with its base resting at y = 0. Solidity is a parity test at each
     * voxel center (robust on closed meshes), plus — when `shell` > 0 —
     * every voxel whose center is within `shell` blocks of the surface,
     * which rescues thin walls and hollow vessels (0.7–1.0 closes
     * single-voxel shells; 0 = pure parity; a *negative* `shell` is
     * surface-only — a skin |shell| blocks thick with no interior fill,
     * for open sheets/ribbons that dip or self-overlap). Errors with `Parse` on
     * malformed/triangle-less GLB and `InvalidArgument` on a
     * non-positive `target_size`.
     */
    static shapeFromGlb(data, targetSize, shell) {
        let functionCleanupArena = new diplomatRuntime.CleanupArena();

        const dataSlice = functionCleanupArena.alloc(diplomatRuntime.DiplomatBuf.sliceWrapper(wasm, diplomatRuntime.DiplomatBuf.slice(wasm, data, "u8")));
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);


        const result = wasm.Voxelizer_shape_from_glb(diplomatReceive.buffer, dataSlice.ptr, targetSize, shell);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new NucleationError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('NucleationError.' + cause.value, { cause });
            }
            return new Shape(diplomatRuntime.internalConstructor, diplomatRuntime.ptrRead(wasm, diplomatReceive.buffer), []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            functionCleanupArena.free();

            diplomatReceive.free();
        }
    }

    /**
     * Load a Wavefront OBJ (`v`/`vt`/`f` lines; polygon faces are
     * fan-triangulated, negative indices supported, materials ignored)
     * and voxelize it into a fillable Shape, fitted and shelled exactly
     * like `shape_from_glb`. Errors with `Parse` on malformed/triangle-less
     * OBJ and `InvalidArgument` on invalid UTF-8 or a non-positive
     * `target_size`.
     */
    static shapeFromObj(text, targetSize, shell) {
        let functionCleanupArena = new diplomatRuntime.CleanupArena();

        const textSlice = functionCleanupArena.alloc(diplomatRuntime.DiplomatBuf.sliceWrapper(wasm, diplomatRuntime.DiplomatBuf.str8(wasm, text)));
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);


        const result = wasm.Voxelizer_shape_from_obj(diplomatReceive.buffer, textSlice.ptr, targetSize, shell);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new NucleationError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('NucleationError.' + cause.value, { cause });
            }
            return new Shape(diplomatRuntime.internalConstructor, diplomatRuntime.ptrRead(wasm, diplomatReceive.buffer), []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            functionCleanupArena.free();

            diplomatReceive.free();
        }
    }

    /**
     * Load a binary glTF and voxelize it directly into a textured
     * schematic named `name`: every solid voxel becomes the `palette`
     * block closest to its nearest-surface texture color (interior
     * voxels inherit the nearest surface color; voxels without texture
     * info snap to mid-gray). `shell` behaves as in `shape_from_glb` —
     * use ~0.7 for thin-walled models. Errors with `Parse` on malformed GLB and
     * `InvalidArgument` on invalid UTF-8 or a non-positive
     * `target_size`.
     */
    static schematicFromGlbTextured(data, targetSize, shell, palette, name) {
        let functionCleanupArena = new diplomatRuntime.CleanupArena();

        const dataSlice = functionCleanupArena.alloc(diplomatRuntime.DiplomatBuf.sliceWrapper(wasm, diplomatRuntime.DiplomatBuf.slice(wasm, data, "u8")));
        const nameSlice = functionCleanupArena.alloc(diplomatRuntime.DiplomatBuf.sliceWrapper(wasm, diplomatRuntime.DiplomatBuf.str8(wasm, name)));
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);


        const result = wasm.Voxelizer_schematic_from_glb_textured(diplomatReceive.buffer, dataSlice.ptr, targetSize, shell, palette.ffiValue, nameSlice.ptr);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new NucleationError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('NucleationError.' + cause.value, { cause });
            }
            return new Schematic(diplomatRuntime.internalConstructor, diplomatRuntime.ptrRead(wasm, diplomatReceive.buffer), []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            functionCleanupArena.free();

            diplomatReceive.free();
        }
    }

    constructor(symbol, ptr, selfEdge) {
        return this.#internalConstructor(...arguments)
    }
}