// generated by diplomat-tool
import type { NucleationError } from "./NucleationError"
import type { Schematic } from "./Schematic"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * A single decoded chunk (or a from-scratch chunk under construction).
 */
export class WorldChunkView {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    /**
     * Create an empty chunk view at the given chunk coordinates — the
     * starting point for generating worlds from scratch. Sections are
     * created on demand by `set_block`. Serialized with
     * `status = "minecraft:full"` (Minecraft will not regenerate over it)
     * and the default data version.
     */
    static create(cx: number, cz: number): WorldChunkView;

    /**
     * The chunk X coordinate (in chunk units).
     */
    cx(): number;

    /**
     * The chunk Z coordinate (in chunk units).
     */
    cz(): number;

    /**
     * Convert the chunk view to a standalone schematic.
     */
    toSchematic(): Schematic;

    /**
     * Set a block at absolute world coordinates inside this chunk view.
     * `block_name` must be a valid Minecraft block identifier (e.g.
     * `minecraft:stone`). Errors with `InvalidArgument` if (x, z) is outside
     * this chunk's column.
     */
    setBlock(x: number, y: number, z: number, blockName: string): void;

    /**
     * Overwrite the biome of every currently-present section of the chunk
     * view with `biome_name` (e.g. `minecraft:desert`). Sections are created
     * lazily by `set_block`, so call this AFTER placing blocks.
     */
    setBiome(biomeName: string): void;

    /**
     * Deduped union of all sections' biome palette entries, in order of
     * first appearance, written as a JSON array string (`[]` if no section
     * carries biome data).
     */
    biomePaletteJson(): string;
}