// generated by diplomat-tool
import type { NucleationError } from "./NucleationError"
import type { WorldChunkView } from "./WorldChunkView"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * A streaming iterator over the chunks of a world.
 */
export class WorldStream {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    /**
     * Open a streaming iterator over a world directory.
     */
    static openDir(path: string): WorldStream;

    /**
     * Open a streaming iterator over a world directory, bounded to the given
     * block-coordinate box `[min_x..max_x, min_y..max_y, min_z..max_z]`.
     */
    static openDirBounded(path: string, minX: number, minY: number, minZ: number, maxX: number, maxY: number, maxZ: number): WorldStream;

    /**
     * Open a streaming iterator from a zip archive in memory.
     */
    static fromZip(data: Array<number>): WorldStream;

    /**
     * Open a bounded streaming iterator from a zip archive in memory.
     */
    static fromZipBounded(data: Array<number>, minX: number, minY: number, minZ: number, maxX: number, maxY: number, maxZ: number): WorldStream;

    /**
     * Advance the iterator and return the next chunk view. Errors with
     * `NotFound` at end-of-stream (the old ABI returned NULL). Corrupt
     * chunks are silently skipped, matching the old ABI.
     */
    next(): WorldChunkView;
}