// generated by diplomat-tool
import type { NucleationError } from "./NucleationError"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * A pinned {@link WorldProfile}(crate::world_segment::profile::WorldProfile):
 * the substrate palette + Y band derived (or supplied) once per world and
 * reused across every segmentation run against it.
 */
export class WsProfile {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    /**
     * Derive a profile from up to `sample` tiles (regions) of a world
     * directory, in ascending `(x, z)` region order. `coverage` is
     * `ProfileParams::min_slab_coverage`; every other `ProfileParams`
     * field uses its default (`sample_stride: 1`, `y_scan: (-64, 320)`).
     */
    static deriveFromDir(worldDir: string, minY: number, maxY: number, sample: number, coverage: number): WsProfile;

    /**
     * The derived substrate Y band's lower bound (inclusive).
     */
    bandMin(): number;

    /**
     * The derived substrate Y band's upper bound (inclusive).
     */
    bandMax(): number;

    /**
     * Number of distinct block names in the substrate palette.
     */
    paletteLen(): number;

    /**
     * The substrate palette as a JSON array of block-name strings.
     */
    writePaletteJson(): string;
}