#!/usr/bin/env python3
"""Extract the 1.13 Flattening data tables from the DataConverter Java sources
into a generated Rust file (`flattening/data.rs`).

Sources:
  * HelperBlockFlatteningV1450.java   -> REGISTRATIONS (block-state table)
  * ConverterFlattenItemStack.java    -> FLATTEN_ITEM_MAP + ITEMS_WITH_DAMAGE
  * ConverterFlattenSpawnEgg.java      -> SPAWN_EGG_MAP
  * ConverterFlattenEntity.java        -> ENTITY_BLOCK_NAME_TO_ID
"""
import re, sys

JAVA = "/Users/andrews/Desktop/item-layout-tool/DataConverterJava/src/main/java/ca/spottedleaf/dataconverter/minecraft"
HELPER = JAVA + "/converters/helpers/HelperBlockFlatteningV1450.java"
ITEM = JAVA + "/converters/itemstack/ConverterFlattenItemStack.java"
EGG = JAVA + "/converters/itemstack/ConverterFlattenSpawnEgg.java"
ENTITY = JAVA + "/converters/entity/ConverterFlattenEntity.java"
ITEMNAME = JAVA + "/converters/helpers/HelperItemNameV102.java"
EGGNAME = JAVA + "/converters/helpers/HelperSpawnEggNameV105.java"
OUT = "/Users/andrews/Desktop/item-layout-tool/nucleation/src/dataconverter/flattening/data.rs"


def rs_str(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'


def parse_state(snbt):
    """Parse `{Name:'minecraft:x'}` or `{Name:'minecraft:x',Properties:{k:'v',...}}`
    into (name, sorted [(k, v)])."""
    nm = re.search(r"Name:'([^']*)'", snbt)
    if not nm:
        raise ValueError("no Name in " + snbt)
    name = nm.group(1)
    props = []
    pm = re.search(r"Properties:\{([^}]*)\}", snbt)
    if pm:
        body = pm.group(1)
        for kv in body.split(','):
            kv = kv.strip()
            if not kv:
                continue
            k, v = kv.split(':', 1)
            props.append((k.strip(), v.strip().strip("'")))
    props.sort()
    return name, props


def emit_state(name, props):
    inner = ", ".join("(%s, %s)" % (rs_str(k), rs_str(v)) for k, v in props)
    return "FlatState { name: %s, props: &[%s] }" % (rs_str(name), inner)


# --- block flattening table -------------------------------------------------
regs = []
seen_ids = set()
with open(HELPER) as f:
    for line in f:
        s = line.strip()
        m = re.match(r"register\((\d+)\s*,(.*)\);\s*$", s)
        if not m:
            continue
        bid = int(m.group(1))
        rest = m.group(2)
        strings = re.findall(r'"([^"]*)"', rest)
        if not strings:
            raise ValueError("no flattened string for id %d: %s" % (bid, s))
        if bid in seen_ids:
            raise ValueError("duplicate id %d" % bid)
        seen_ids.add(bid)
        flat = parse_state(strings[0])
        pres = [parse_state(x) for x in strings[1:]]
        regs.append((bid, flat, pres))

# sanity: ascending order (Java relies on it for BLOCK_DEFAULTS)
ids = [r[0] for r in regs]
assert ids == sorted(ids), "register() ids are NOT in ascending source order!"

# --- item flatten map -------------------------------------------------------
item_map = []
with open(ITEM) as f:
    txt = f.read()
for k, v in re.findall(r'FLATTEN_MAP\.put\("([^"]+)",\s*"([^"]+)"\)', txt):
    item_map.append((k, v))
# ITEMS_WITH_DAMAGE: the Arrays.asList(...) block
dmg_block = re.search(r"ITEMS_WITH_DAMAGE\s*=\s*new HashSet<>\(Arrays\.asList\((.*?)\)\)", txt, re.S)
items_with_damage = re.findall(r'"([^"]+)"', dmg_block.group(1))

# --- spawn egg map ----------------------------------------------------------
egg_map = []
with open(EGG) as f:
    for k, v in re.findall(r'ENTITY_ID_TO_NEW_EGG_ID\.put\("([^"]+)",\s*"([^"]+)"\)', f.read()):
        egg_map.append((k, v))

# --- entity block-name -> id ------------------------------------------------
ent_map = []
with open(ENTITY) as f:
    for k, v in re.findall(r'BLOCK_NAME_TO_ID\.put\("([^"]+)",\s*(\d+)\)', f.read()):
        ent_map.append((k, int(v)))

# --- numeric item id -> name (HelperItemNameV102, jukebox Record) -----------
item_names = []
potion_names = []
with open(ITEMNAME) as f:
    txt = f.read()
for v, k in re.findall(r'ITEM_NAMES\.put\((\d+),\s*"([^"]+)"\)', txt):
    item_names.append((int(v), k))
# POTION_NAMES[idx] = "name";  (null entries omitted -> accessor returns None)
for idx, name in re.findall(r'POTION_NAMES\[(\d+)\]\s*=\s*"([^"]+)"', txt):
    potion_names.append((int(idx), name))

# --- legacy spawn-egg damage -> entity name (HelperSpawnEggNameV105, V105) ---
spawn_egg_names = []
with open(EGGNAME) as f:
    for idx, name in re.findall(r'ID_TO_STRING\[(\d+)\]\s*=\s*"([^"]+)"', f.read()):
        spawn_egg_names.append((int(idx), name))

# --- emit -------------------------------------------------------------------
out = []
out.append("//! GENERATED by tools/extract_flattening.py — do not edit by hand.")
out.append("//!")
out.append("//! 1.13 \"Flattening\" data tables, extracted verbatim from")
out.append("//! `HelperBlockFlatteningV1450.java`, `ConverterFlattenItemStack.java`,")
out.append("//! `ConverterFlattenSpawnEgg.java`, and `ConverterFlattenEntity.java`.")
out.append("")
out.append("use super::{FlatState, Registration};")
out.append("")
out.append("/// `register(id, flattened, preFlattenings…)` table, in ascending-id")
out.append("/// source order (BLOCK_DEFAULTS relies on it).")
out.append("pub(super) static REGISTRATIONS: &[Registration] = &[")
for bid, flat, pres in regs:
    pres_s = ", ".join(emit_state(n, p) for n, p in pres)
    out.append("    Registration { id: %d, flat: %s, pres: &[%s] }," % (bid, emit_state(*flat), pres_s))
out.append("];")
out.append("")
out.append('/// `FLATTEN_MAP`: "id.damage" -> flattened item id.')
out.append("pub(super) static FLATTEN_ITEM_MAP: &[(&str, &str)] = &[")
for k, v in item_map:
    out.append("    (%s, %s)," % (rs_str(k), rs_str(v)))
out.append("];")
out.append("")
out.append("/// `ITEMS_WITH_DAMAGE`: ids whose Damage is real durability, not a subtype.")
out.append("pub(super) static ITEMS_WITH_DAMAGE: &[&str] = &[")
for k in items_with_damage:
    out.append("    %s," % rs_str(k))
out.append("];")
out.append("")
out.append("/// `ENTITY_ID_TO_NEW_EGG_ID`: entity id -> spawn-egg item id.")
out.append("pub(super) static SPAWN_EGG_MAP: &[(&str, &str)] = &[")
for k, v in egg_map:
    out.append("    (%s, %s)," % (rs_str(k), rs_str(v)))
out.append("];")
out.append("")
out.append("/// `BLOCK_NAME_TO_ID`: legacy block name -> numeric block id (entity flatten).")
out.append("pub(super) static ENTITY_BLOCK_NAME_TO_ID: &[(&str, i32)] = &[")
for k, v in ent_map:
    out.append("    (%s, %d)," % (rs_str(k), v))
out.append("];")
out.append("")
out.append("/// `HelperItemNameV102.ITEM_NAMES`: numeric item id -> name (jukebox Record).")
out.append("pub(super) static ITEM_NAMES_BY_ID: &[(i32, &str)] = &[")
for v, k in item_names:
    out.append("    (%d, %s)," % (v, rs_str(k)))
out.append("];")
out.append("")
out.append("/// `HelperItemNameV102.POTION_NAMES`: numeric potion id (& 127) -> name (null entries omitted).")
out.append("pub(super) static POTION_NAMES_BY_ID: &[(i32, &str)] = &[")
for idx, name in potion_names:
    out.append("    (%d, %s)," % (idx, rs_str(name)))
out.append("];")
out.append("")
out.append("/// `HelperSpawnEggNameV105.ID_TO_STRING`: legacy spawn-egg damage (& 255) -> entity name.")
out.append("pub(super) static SPAWN_EGG_NAME_BY_ID: &[(i32, &str)] = &[")
for idx, name in spawn_egg_names:
    out.append("    (%d, %s)," % (idx, rs_str(name)))
out.append("];")
out.append("")

with open(OUT, "w") as f:
    f.write("\n".join(out))

print("REGISTRATIONS:", len(regs))
print("FLATTEN_ITEM_MAP:", len(item_map))
print("ITEMS_WITH_DAMAGE:", len(items_with_damage))
print("SPAWN_EGG_MAP:", len(egg_map))
print("ENTITY_BLOCK_NAME_TO_ID:", len(ent_map))
print("ITEM_NAMES_BY_ID:", len(item_names))
print("POTION_NAMES_BY_ID:", len(potion_names))
print("wrote", OUT)
