#include "diplomat_nanobind_common.hpp"


#include "Schematic.hpp"

namespace nucleation {
void add_Schematic_binding(nb::module_ mod) {
    PyType_Slot nucleation_Schematic_slots[] = {
        {Py_tp_free, (void *)nucleation::Schematic::operator delete },
        {Py_tp_dealloc, (void *)diplomat_tp_dealloc},
        {0, nullptr}};
    
    nb::class_<nucleation::Schematic> opaque(mod, "Schematic", nb::type_slots(nucleation_Schematic_slots));
    opaque
        .def("add_entity", &nucleation::Schematic::add_entity, "id"_a, "x"_a, "y"_a, "z"_a, "nbt_json"_a)
        .def("add_entity_from_snbt", &nucleation::Schematic::add_entity_from_snbt, "snbt"_a)
        .def("all_palettes_json", &nucleation::Schematic::all_palettes_json)
        .def("allocated_dimensions", &nucleation::Schematic::allocated_dimensions)
        .def("author", &nucleation::Schematic::author)
        .def_static("available_schematic_versions_json", &nucleation::Schematic::available_schematic_versions_json)
        .def("block_count", &nucleation::Schematic::block_count)
        .def("bounding_box_json", &nucleation::Schematic::bounding_box_json)
        .def_static("canonical_data_version", &nucleation::Schematic::canonical_data_version)
        .def("compile_insign_json", &nucleation::Schematic::compile_insign_json)
        .def("convert_to_data_version", &nucleation::Schematic::convert_to_data_version, "target_data_version"_a, "source_data_version"_a)
        .def("convert_to_version", &nucleation::Schematic::convert_to_version, "target_data_version"_a)
        .def("copy_region", &nucleation::Schematic::copy_region, "source"_a, "min_x"_a, "min_y"_a, "min_z"_a, "max_x"_a, "max_y"_a, "max_z"_a, "target_x"_a, "target_y"_a, "target_z"_a, "excluded_blocks_json"_a)
        .def_static("create", std::move(maybe_op_unwrap(&nucleation::Schematic::create)), "name"_a)
        .def("created", &nucleation::Schematic::created)
        .def("debug_info", &nucleation::Schematic::debug_info)
        .def("debug_json_string", &nucleation::Schematic::debug_json_string)
        .def("debug_string", &nucleation::Schematic::debug_string)
        .def("default_region_palette_json", &nucleation::Schematic::default_region_palette_json)
        .def("description", &nucleation::Schematic::description)
        .def("dimensions", &nucleation::Schematic::dimensions)
        .def("entity_count", &nucleation::Schematic::entity_count)
        .def("extract_signs_json", &nucleation::Schematic::extract_signs_json)
        .def("fill_cuboid", &nucleation::Schematic::fill_cuboid, "min_x"_a, "min_y"_a, "min_z"_a, "max_x"_a, "max_y"_a, "max_z"_a, "block_name"_a)
        .def("fill_sphere", &nucleation::Schematic::fill_sphere, "cx"_a, "cy"_a, "cz"_a, "radius"_a, "block_name"_a)
        .def("flip_region_x", &nucleation::Schematic::flip_region_x, "region_name"_a)
        .def("flip_region_y", &nucleation::Schematic::flip_region_y, "region_name"_a)
        .def("flip_region_z", &nucleation::Schematic::flip_region_z, "region_name"_a)
        .def("flip_x", &nucleation::Schematic::flip_x)
        .def("flip_y", &nucleation::Schematic::flip_y)
        .def("flip_z", &nucleation::Schematic::flip_z)
        .def_static("from_data", std::move(maybe_op_unwrap(&nucleation::Schematic::from_data)), "data"_a)
        .def_static("from_litematic", std::move(maybe_op_unwrap(&nucleation::Schematic::from_litematic)), "data"_a)
        .def_static("from_mca", std::move(maybe_op_unwrap(&nucleation::Schematic::from_mca)), "data"_a)
        .def_static("from_mca_bounded", std::move(maybe_op_unwrap(&nucleation::Schematic::from_mca_bounded)), "data"_a, "min_x"_a, "min_y"_a, "min_z"_a, "max_x"_a, "max_y"_a, "max_z"_a)
        .def_static("from_mcstructure", std::move(maybe_op_unwrap(&nucleation::Schematic::from_mcstructure)), "data"_a)
        .def_static("from_schematic", std::move(maybe_op_unwrap(&nucleation::Schematic::from_schematic)), "data"_a)
        .def_static("from_snapshot", std::move(maybe_op_unwrap(&nucleation::Schematic::from_snapshot)), "data"_a)
        .def_static("from_world_directory", std::move(maybe_op_unwrap(&nucleation::Schematic::from_world_directory)), "path"_a)
        .def_static("from_world_directory_bounded", std::move(maybe_op_unwrap(&nucleation::Schematic::from_world_directory_bounded)), "path"_a, "min_x"_a, "min_y"_a, "min_z"_a, "max_x"_a, "max_y"_a, "max_z"_a)
        .def_static("from_world_zip", std::move(maybe_op_unwrap(&nucleation::Schematic::from_world_zip)), "data"_a)
        .def_static("from_world_zip_bounded", std::move(maybe_op_unwrap(&nucleation::Schematic::from_world_zip_bounded)), "data"_a, "min_x"_a, "min_y"_a, "min_z"_a, "max_x"_a, "max_y"_a, "max_z"_a)
        .def("get_all_block_entities_json", &nucleation::Schematic::get_all_block_entities_json)
        .def("get_all_block_entities_snbt_json", &nucleation::Schematic::get_all_block_entities_snbt_json)
        .def("get_all_blocks_json", &nucleation::Schematic::get_all_blocks_json)
        .def("get_block_entity_json", &nucleation::Schematic::get_block_entity_json, "x"_a, "y"_a, "z"_a)
        .def("get_block_entity_snbt", &nucleation::Schematic::get_block_entity_snbt, "x"_a, "y"_a, "z"_a)
        .def("get_block_name", &nucleation::Schematic::get_block_name, "x"_a, "y"_a, "z"_a)
        .def("get_block_string", &nucleation::Schematic::get_block_string, "x"_a, "y"_a, "z"_a)
        .def("get_block_with_properties", std::move(maybe_op_unwrap(&nucleation::Schematic::get_block_with_properties)), "x"_a, "y"_a, "z"_a)
        .def("get_blocks_json", &nucleation::Schematic::get_blocks_json, "positions"_a)
        .def("get_chunk_blocks_json", &nucleation::Schematic::get_chunk_blocks_json, "offset_x"_a, "offset_y"_a, "offset_z"_a, "width"_a, "height"_a, "length"_a)
        .def("get_chunks_json", &nucleation::Schematic::get_chunks_json, "chunk_width"_a, "chunk_height"_a, "chunk_length"_a)
        .def("get_chunks_with_strategy_json", &nucleation::Schematic::get_chunks_with_strategy_json, "chunk_width"_a, "chunk_height"_a, "chunk_length"_a, "strategy"_a, "camera_x"_a, "camera_y"_a, "camera_z"_a)
        .def("get_entities_json", &nucleation::Schematic::get_entities_json)
        .def("get_entities_snbt_json", &nucleation::Schematic::get_entities_snbt_json)
        .def("lm_version", &nucleation::Schematic::lm_version)
        .def_static("load_from_file", std::move(maybe_op_unwrap(&nucleation::Schematic::load_from_file)), "path"_a)
        .def("mc_version", &nucleation::Schematic::mc_version)
        .def("modified", &nucleation::Schematic::modified)
        .def("name", &nucleation::Schematic::name)
        .def("palette_json", &nucleation::Schematic::palette_json)
        .def("place", &nucleation::Schematic::place, "x"_a, "y"_a, "z"_a, "palette_index"_a)
        .def("prepare_block", &nucleation::Schematic::prepare_block, "block_name"_a)
        .def("print_schematic_string", &nucleation::Schematic::print_schematic_string)
        .def("print_string", &nucleation::Schematic::print_string)
        .def("region_bounding_box_json", &nucleation::Schematic::region_bounding_box_json, "region_name"_a)
        .def("region_names_json", &nucleation::Schematic::region_names_json)
        .def("region_palette_json", &nucleation::Schematic::region_palette_json, "region_name"_a)
        .def("remove_block_entity", &nucleation::Schematic::remove_block_entity, "x"_a, "y"_a, "z"_a)
        .def("remove_entity", &nucleation::Schematic::remove_entity, "index"_a)
        .def("rotate_region_x", &nucleation::Schematic::rotate_region_x, "region_name"_a, "degrees"_a)
        .def("rotate_region_y", &nucleation::Schematic::rotate_region_y, "region_name"_a, "degrees"_a)
        .def("rotate_region_z", &nucleation::Schematic::rotate_region_z, "region_name"_a, "degrees"_a)
        .def("rotate_x", &nucleation::Schematic::rotate_x, "degrees"_a)
        .def("rotate_y", &nucleation::Schematic::rotate_y, "degrees"_a)
        .def("rotate_z", &nucleation::Schematic::rotate_z, "degrees"_a)
        .def("save_as_b64", &nucleation::Schematic::save_as_b64, "format"_a, "version"_a, "settings"_a)
        .def("save_to_file", &nucleation::Schematic::save_to_file, "path"_a)
        .def("save_to_file_with_format", &nucleation::Schematic::save_to_file_with_format, "path"_a, "format"_a, "version"_a)
        .def("save_world", &nucleation::Schematic::save_world, "directory"_a, "options_json"_a)
        .def("set_author", &nucleation::Schematic::set_author, "author"_a)
        .def("set_block", &nucleation::Schematic::set_block, "x"_a, "y"_a, "z"_a, "block_name"_a)
        .def("set_block_entity", &nucleation::Schematic::set_block_entity, "x"_a, "y"_a, "z"_a, "id"_a, "snbt"_a)
        .def("set_block_from_string", &nucleation::Schematic::set_block_from_string, "x"_a, "y"_a, "z"_a, "block_string"_a)
        .def("set_block_in_region", &nucleation::Schematic::set_block_in_region, "region_name"_a, "x"_a, "y"_a, "z"_a, "block_name"_a)
        .def("set_block_with_nbt", &nucleation::Schematic::set_block_with_nbt, "x"_a, "y"_a, "z"_a, "block_name"_a, "nbt_json"_a)
        .def("set_block_with_properties", &nucleation::Schematic::set_block_with_properties, "x"_a, "y"_a, "z"_a, "block_name"_a, "properties_json"_a)
        .def("set_blocks", &nucleation::Schematic::set_blocks, "positions"_a, "block_name"_a)
        .def("set_created", &nucleation::Schematic::set_created, "created"_a)
        .def("set_description", &nucleation::Schematic::set_description, "description"_a)
        .def("set_lm_version", &nucleation::Schematic::set_lm_version, "version"_a)
        .def("set_mc_version", &nucleation::Schematic::set_mc_version, "version"_a)
        .def("set_modified", &nucleation::Schematic::set_modified, "modified"_a)
        .def("set_name", &nucleation::Schematic::set_name, "name"_a)
        .def("set_source_data_version", &nucleation::Schematic::set_source_data_version, "version"_a)
        .def("set_we_version", &nucleation::Schematic::set_we_version, "version"_a)
        .def("source_data_version", &nucleation::Schematic::source_data_version)
        .def("tight_bounds_max", &nucleation::Schematic::tight_bounds_max)
        .def("tight_bounds_min", &nucleation::Schematic::tight_bounds_min)
        .def("tight_dimensions", &nucleation::Schematic::tight_dimensions)
        .def("to_litematic_b64", &nucleation::Schematic::to_litematic_b64)
        .def("to_litematic_for_version_json", &nucleation::Schematic::to_litematic_for_version_json, "target_data_version"_a)
        .def("to_mcstructure_b64", &nucleation::Schematic::to_mcstructure_b64)
        .def("to_schematic_b64", &nucleation::Schematic::to_schematic_b64)
        .def("to_schematic_version_b64", &nucleation::Schematic::to_schematic_version_b64, "version"_a)
        .def("to_snapshot_b64", &nucleation::Schematic::to_snapshot_b64)
        .def("to_world_json", &nucleation::Schematic::to_world_json, "options_json"_a)
        .def("to_world_zip_b64", &nucleation::Schematic::to_world_zip_b64, "options_json"_a)
        .def("volume", &nucleation::Schematic::volume)
        .def("we_version", &nucleation::Schematic::we_version);
}

} 